### ISSUE TITLE
Can't drop default column family

### ISSUE THREAD

**Issue by LGouellec** [facebook/rocksdb#10138]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior

Authorize to drop the default column family if another column family is present inside the rocksdb instance.

### Actual behavior

Let's suppose you have a rocksdb database with 2 column families the default column family and another one. Suppose you want to drop the default column family because this one is empty and all the data is present inside the second column family.

If you call `db.dropColumnFamily(defaultColumnFamilyHandle)`, a RocksDbException is thrown : 

``` log
Exception in thread "main" org.rocksdb.RocksDBException: Can't drop default column family
	at org.rocksdb.RocksDB.dropColumnFamily(Native Method)
	at org.rocksdb.RocksDB.dropColumnFamily(RocksDB.java:767)
```

<img width="752" alt="image" src="https://user-images.githubusercontent.com/3295357/172789399-1826736c-a669-4668-a06f-5b4f17220f58.png">

### Steps to reproduce the behavior

Little bootstrap java application to reproduce 
``` java
public class RockDbReproducer {

    private static final CompressionType COMPRESSION_TYPE = CompressionType.NO_COMPRESSION;
    private static final CompactionStyle COMPACTION_STYLE = CompactionStyle.UNIVERSAL;
    private static final long WRITE_BUFFER_SIZE = 16 * 1024 * 1024L;
    private static final long BLOCK_CACHE_SIZE = 50 * 1024 * 1024L;
    private static final long BLOCK_SIZE = 4096L;
    private static final int MAX_WRITE_BUFFERS = 3;
    private static final String DB_FILE_DIR = "rocksdb";

    private File dbDir;
    private RocksDB db;

    public static void main(String[] args) throws RocksDBException, IOException {
        RockDbReproducer reproducer = new RockDbReproducer();
        reproducer.openDB(new File(System.getProperty("java.io.tmpdir"), "reproducer-rocksdb"));
    }

    void openDB(final File stateDir)
            throws IOException,
            RocksDBException {

        // initialize the default rocksdb options
        final DBOptions dbOptions = new DBOptions();
        final ColumnFamilyOptions columnFamilyOptions = new ColumnFamilyOptions();

        final BlockBasedTableConfig tableConfig = new BlockBasedTableConfig();
        LRUCache cache = new LRUCache(BLOCK_CACHE_SIZE);
        tableConfig.setBlockCache(cache);
        tableConfig.setBlockSize(BLOCK_SIZE);

        BloomFilter filter = new BloomFilter();
        tableConfig.setFilterPolicy(filter);

        columnFamilyOptions.optimizeFiltersForHits();
        columnFamilyOptions.setTableFormatConfig(tableConfig);
        columnFamilyOptions.setWriteBufferSize(WRITE_BUFFER_SIZE);
        columnFamilyOptions.setCompressionType(COMPRESSION_TYPE);
        columnFamilyOptions.setCompactionStyle(COMPACTION_STYLE);
        columnFamilyOptions.setMaxWriteBufferNumber(MAX_WRITE_BUFFERS);
        dbOptions.setCreateIfMissing(true);
        dbOptions.setErrorIfExists(false);
        dbOptions.setInfoLogLevel(InfoLogLevel.ERROR_LEVEL);
        dbOptions.setIncreaseParallelism(Math.max(Runtime.getRuntime().availableProcessors(), 2));

        dbDir = new File(stateDir, DB_FILE_DIR);
        Files.createDirectories(dbDir.getParentFile().toPath());
        Files.createDirectories(dbDir.getAbsoluteFile().toPath());

        final List<ColumnFamilyDescriptor> columnFamilyDescriptors = asList(
                new ColumnFamilyDescriptor(RocksDB.DEFAULT_COLUMN_FAMILY, columnFamilyOptions),
                new ColumnFamilyDescriptor("keyValueWithTimestamp".getBytes(StandardCharsets.UTF_8), columnFamilyOptions));
        final List<ColumnFamilyHandle> columnFamilies = new ArrayList<>(columnFamilyDescriptors.size());

        try {
            db = RocksDB.open(dbOptions, dbDir.getAbsolutePath(), columnFamilyDescriptors, columnFamilies);
        } catch (final RocksDBException e) {
            if ("Column family not found: keyValueWithTimestamp".equals(e.getMessage())) {
                    db = RocksDB.open(dbOptions, dbDir.getAbsolutePath(), columnFamilyDescriptors.subList(0, 1), columnFamilies);
                    columnFamilies.add(db.createColumnFamily(columnFamilyDescriptors.get(1)));
            } else {
                throw e;
            }
        }

        db.dropColumnFamily(columnFamilies.get(0));
    }

}
```

**Comment by riversand963** [comment]
I don't think it's allowed to drop default column family, and there is currently no plan to change this assumption/design.
