### ISSUE TITLE
rocksdbjni 7.5.3 + Alpine arm64 errors with "libstdc++.so.6: cannot open shared object file"

### ISSUE THREAD

**Issue by davidmelia** [facebook/rocksdb#10651]
Hi,

When initialising rocksdbjni 7.5.3 on Alpine arm 64 
`(Linux dbf2dddea346 5.10.124-linuxkit #1 SMP PREEMPT Thu Jun 30 08:18:26 UTC 2022 aarch64 Linux) `

this errors with

`libstdc++.so.6: cannot open shared object file: No such file or directory`

### Expected behavior

Rocks DB on alpine arm64 should load the rocksdb native libraries.

### Actual behavior

```
java.lang.UnsatisfiedLinkError: /tmp/librocksdbjni5890853752640758745.so: libstdc++.so.6: cannot open shared object file: No such file or directory
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
	at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.base/java.lang.Runtime.load0(Unknown Source)
	at java.base/java.lang.System.load(Unknown Source)
	at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:102)
	at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:82)
	at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:70)
	at org.rocksdb.RocksDB.<clinit>(RocksDB.java:39)
```

### Steps to reproduce the behavior

I have a very simple Java 17 rocksdbjni 7.5.3 GitHub docker project https://github.com/davidmelia/rocksdb-aarch64alpine-issue  to illustrate this issue where I have an amd64 container (which works)  versus arm64 container which errors.

Invoking the amd64 via _./buildAndRunAmd64.sh_ works fine giving
```
Attempting to load RocksDB
Loaded RocksDB JNI
```

Invoking arm64 via _./buildAndRunArm64.sh_ errors with

```
Attempting to load RocksDB
java.lang.UnsatisfiedLinkError: /tmp/librocksdbjni2970121315890144650.so: libstdc++.so.6: cannot open shared object file: No such file or directory
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
	at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.base/java.lang.Runtime.load0(Unknown Source)
	at java.base/java.lang.System.load(Unknown Source)
	at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:102)
	at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:82)
	at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:70)
	at org.rocksdb.RocksDB.<clinit>(RocksDB.java:39)
	at Run.main(Run.java:8)
```

Thanks

**Comment by DRoppelt** [comment]
I replied in the other ticket, but I think it makes sense to add my response here in case someone finds their way here via google.

`libstdc++.so.6: cannot open shared object file: No such file or directory` hints that the required OS depdency libstdc++ is missing. As alpine is pretty bare-bones, it has to be added. Can you try `apk add libstdc++`?

**Comment by davidmelia** [comment]
@DRoppelt I did try that at the time.  Further to this I have updated my prototype https://github.com/davidmelia/rocksdb-aarch64alpine-issue to show `apk add libstdc++` has no effect and the error remains :-( 

The reason I think this is a bug with RocksDB is alpine linux amd64 works fine but alpine linux arm64 has the error.

Thanks

**Comment by adamretter** [comment]
@davidmelia So you should find inside the .jar files:

1. `librocksdbjni-linux-aarch64-musl.so` - this is the Arm64 architecture version for muslc (as used in Alpine).
2. `librocksdbjni-linux-aarch64.so` - this is the x86_64 architecture version for glibc.

The Docker image that we use for producing `librocksdbjni-linux-aarch64-musl.so` is `evolvedbinary/rocksjava:alpine3_arm64v8-be` which you can find on DockerHub, or the Dockerfile is available here - https://github.com/evolvedbinary/docker-rocksjava/blob/main/alpine3_arm64v8/Dockerfile

We build this in the above Docker image of `alpine:3.10` running on a physical Arm64 machine.

Running `ldd librocksdbjni-linux-aarch64-musl.so` inside `alpine 3.10` for Arm64 reveals:

```
# ldd librocksdbjni-linux-aarch64-musl.so
	/lib/ld-musl-aarch64.so.1 (0xffffac690000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0xffffabb41000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0xffffabb1f000)
	libc.musl-aarch64.so.1 => /lib/ld-musl-aarch64.so.1 (0xffffac690000)
```

@davidmelia is that helpful?

**Comment by davidmelia** [comment]
@adamretter thanks for that.  I'm not a Linux expert but when I log into the container I can see all those files are there:

```
/ # ls -la /lib/ld-musl-aarch64.so.1 /usr/lib/libstdc++.so.6 /usr/lib/libgcc_s.so.1 
-rwxr-xr-x    1 root     root        633200 Apr  8  2022 /lib/ld-musl-aarch64.so.1
-rw-r--r--    1 root     root         83656 Apr 11  2022 /usr/lib/libgcc_s.so.1
lrwxrwxrwx    1 root     root            19 Oct 17 18:41 /usr/lib/libstdc++.so.6 -> libstdc++.so.6.0.29
```
ldd gives

```
/tmp # ldd librocksdbjni-linux-aarch64-musl.so 
        /lib/ld-musl-aarch64.so.1 (0xffffbae27000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0xffffba278000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0xffffba253000)
        libc.musl-aarch64.so.1 => /lib/ld-musl-aarch64.so.1 (0xffffbae27000)
```
and invoking musl gives
```
/tmp # /lib/ld-musl-aarch64.so.1
musl libc (aarch64)
Version 1.2.3
Dynamic Program Loader
```

**Comment by alanpaxton** [comment]
Hi @davidmelia if you use `FROM bellsoft/liberica-openjre-alpine-musl` instead of `FROM bellsoft/liberica-openjre-alpine` it works for both architectures (but each needs `RUN apk add libstdc++` as well). It looks as if the `bellsoft/liberica-openjre-alpine` image for amd64 has a `libstdc++` in usr/glibc/lib, while the image for arm64 does not, which seems wrong, but I don't know enough to understand for certain why. But in any event it appears coherent for the `-musl` rocksdbjni to work with the `-musl` distribution after `libstdc++` has been installed. Does that help ?

**Comment by davidmelia** [comment]
Thanks @alanpaxton  your suggested fix works fine.

**Comment by krishnangovindraj** [comment]
I did encounter a `libstdc++.so.6` not found on the  aarch64 version of `bellsoft/liberica-openjdk-alpine:21`. Running Simply running the glibc `ldconfig` seems to have fixed it.


```Dockerfile
FROM bellsoft/liberica-openjdk-alpine:21
RUN apk update
RUN apk add libstdc++ 
RUN /usr/glibc/sbin/ldconfig
...
```
