### ISSUE TITLE
include librocksdbjni-win64.dll in maven package

### ISSUE THREAD

**Issue by plaksina** [facebook/rocksdb#1177]
It would be very helpful if you could include the dll for windows support in the maven package , we are having trouble building it

**Comment by adamretter** [comment]
Related to - https://github.com/facebook/rocksdb/issues/703#issuecomment-206027819

**Comment by plaksina** [comment]
after reading the related comment and building the dll from the source we get the following error with stack trace @adamretter 

`Exception in thread "StreamThread-1" java.lang.UnsatisfiedLinkError: org.rocksdb.Options.newOptions()V

       at org.rocksdb.Options.newOptions(Native Method)

       at org.rocksdb.Options.<init>(Options.java:31)

       at org.apache.kafka.streams.state.internals.RocksDBStore.<init>(RocksDBStore.java:127)

       at org.apache.kafka.streams.state.internals.RocksDBStore.<init>(RocksDBStore.java:113)

       at org.apache.kafka.streams.state.internals.RocksDBKeyValueStoreSupplier.get(RocksDBKeyValueStoreSupplier.java:56)

       at org.apache.kafka.streams.processor.internals.AbstractTask.initializeStateStores(AbstractTask.java:80)

       at org.apache.kafka.streams.processor.internals.StreamTask.<init>(StreamTask.java:115)

       at org.apache.kafka.streams.processor.internals.StreamThread.createStreamTask(StreamThread.java:550)

       at org.apache.kafka.streams.processor.internals.StreamThread.addStreamTasks(StreamThread.java:577)

       at org.apache.kafka.streams.processor.internals.StreamThread.access$000(StreamThread.java:68)

       at org.apache.kafka.streams.processor.internals.StreamThread$1.onPartitionsAssigned(StreamThread.java:123)

       at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.onJoinComplete(ConsumerCoordinator.java:222)

       at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$1.onSuccess(AbstractCoordinator.java:232)

       at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$1.onSuccess(AbstractCoordinator.java:227)

       at org.apache.kafka.clients.consumer.internals.RequestFuture.fireSuccess(RequestFuture.java:133)

       at org.apache.kafka.clients.consumer.internals.RequestFuture.complete(RequestFuture.java:107)

       at org.apache.kafka.clients.consumer.internals.RequestFuture$2.onSuccess(RequestFuture.java:182)

       at org.apache.kafka.clients.consumer.internals.RequestFuture.fireSuccess(RequestFuture.java:133)

       at org.apache.kafka.clients.consumer.internals.RequestFuture.complete(RequestFuture.java:107)

       at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$SyncGroupResponseHandler.handle(AbstractCoordinator.java:436)

       at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$SyncGroupResponseHandler.handle(AbstractCoordinator.java:422)

       at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$CoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:679)

       at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$CoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:658)

       at org.apache.kafka.clients.consumer.internals.RequestFuture$1.onSuccess(RequestFuture.java:167)

       at org.apache.kafka.clients.consumer.internals.RequestFuture.fireSuccess(RequestFuture.java:133)

       at org.apache.kafka.clients.consumer.internals.RequestFuture.complete(RequestFuture.java:107)

       at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient$RequestFutureCompletionHandler.onComplete(ConsumerNetworkClient.java:426)

       at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:278)

       at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.clientPoll(ConsumerNetworkClient.java:360)

       at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:224)

       at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:192)

       at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:163)

       at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureActiveGroup(AbstractCoordinator.java:243)

       at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.ensurePartitionAssignment(ConsumerCoordinator.java:345)

       at org.apache.kafka.clients.consumer.KafkaConsumer.pollOnce(KafkaConsumer.java:977)

       at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:937)

       at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:295)

       at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:218)`

**Comment by davispw** [comment]
Workaround here, but it is quite horrible -- appears that RocksDB only looks inside its own jar for native libraries, and inserting the .dll into the jar breaks Maven.  Any progress on this?

https://mail-archives.apache.org/mod_mbox/kafka-users/201608.mbox/%3CCAJikTEXmn2UxkoKc0P4JsXqqwcNeP3pFfm2j5=eZH9pdgQaOvA@mail.gmail.com%3E

**Comment by adamretter** [comment]
@davispw If you want to patch it, you can take a RocksDB Jar from Maven Central, modify the Jar by inserting the .dll or whatever else you need in there and then creating your own Maven artifact from that; There is nothing about that process that "*beaks Maven*".

However, I am hoping to release RocksJava 4.9 this evening. This should contain a DLL for Windows in the Jar file and appear on Maven Central shortly after.

**Comment by davispw** [comment]
Great news about 4.9 release!  Will look forward to it. 

By "breaks maven" I meant at my organization (I don't think I'm alone) it is quite difficult to inject a customized jar that doesn't follow the normal process, aside from the pain of putting together a Windows build at a Java shop. A bureaucratic issue, not a technical one.  Sorry for inflammatory characterization!

**Comment by adamretter** [comment]
@davispw I just published 4.9.0 to Maven Central, it should be available within the next two hours (according to Sonatype's synchronisation rules).

**Comment by davispw** [comment]
You rock @adamretter!  Working now with 4.9.0.

**Comment by kobikis** [comment]
@adamretter while using 4.9.0 on Win7 (on vm) I got this error, (the dll exists) any idea?

Caused by: java.lang.UnsatisfiedLinkError: C:\Users\kobi\AppData\Local\Temp\librocksdbjni3993939733537201067.dll: Can't find dependent libraries
at java.lang.ClassLoader$NativeLibrary.load(Native Method)
at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1965)
at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1890)
at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1851)
at java.lang.Runtime.load0(Runtime.java:795)
at java.lang.System.load(System.java:1062)
at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:78)
at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:56)
at org.rocksdb.RocksDB.<clinit>(RocksDB.java:23)
at org.rocksdb.ColumnFamilyOptions.<clinit>(ColumnFamilyOptions.java:22)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:526)

**Comment by adamretter** [comment]
@kobikis can you please open a new issue for this instead

**Comment by kobikis** [comment]
sure

**Comment by twiechert** [comment]
I'm getting the same error, also using Kafka but running on a ppc64 architecture. I've configured Kafka to use rocksdbhni 4.9.0 and pass the location of my native build using `-Djava.library.path=.`..
Still I'm facing this problem. Andy ideas?

**Comment by adamretter** [comment]
@twiechert Let's move that conversation to https://github.com/facebook/rocksdb/issues/1317
