### ISSUE TITLE
WriteBufferManager Stalls

### ISSUE THREAD

**Issue by vjeko** [facebook/rocksdb#11780]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior

The application should not deadlock. 

### Actual behavior

A write never finishes.

### Steps to reproduce the behavior

Using v8.3.2 branch. According to the documentation (https://github.com/facebook/rocksdb/wiki/Write-Buffer-Manager) WriteBufferManager is suppose to control the total memory used by memtables across multiple column families and/or DB instances. I've been using it with `allow_stall = true` so that the memory is always bounded. I initially observed this issue in Java, but ended up reproducing it in a C++, albeit with a slightly different behavior. Note that the issue is not observed when WriteBufferManager is not used.

The test:
1) Opens 100 tables with WriteBufferManager set to 500MB.
```

  OptimisticTransactionTest() {
    WriteBufferManager wbm(500 * 1024 * 1024, nullptr, true);
    options.create_if_missing = true;
    options.write_buffer_manager.reset(&wbm);

    pid_t pid = getpid();
    std::cout << "Current process ID: " << pid << std::endl;

    for (int i = 0; i < 100; i++) {
      dbname = test::PerThreadDBPath("optimistic_transaction_testdb" + std::to_string(i));
      EXPECT_OK(DestroyDB(dbname, options));
    }

    std::cout << "Opening... "<< std::endl;
    for (int i = 0; i < 100; i++) {
      dbname = test::PerThreadDBPath("optimistic_transaction_testdb" + std::to_string(i));
      dbs.push_back(Open(dbname));
    }
    std::cout << "Done " << std::endl;
  }

  static std::shared_ptr<rocksdb::OptimisticTransactionDB> OpenImpl(const Options& options,
                       const OptimisticTransactionDBOptions& occ_opts,
                       const std::string& dbname,
                       std::shared_ptr<OptimisticTransactionDB>* txn_db) {
    OptimisticTransactionDB* raw_txn_db = nullptr;
    Status s = OptimisticTransactionDB::Open(
        options, dbname, &raw_txn_db);

    return std::shared_ptr<rocksdb::OptimisticTransactionDB>(raw_txn_db);
  }

  std::shared_ptr<rocksdb::OptimisticTransactionDB> Open(std::string name) {
    return OpenImpl(options, occ_opts, name, &txn_db);
  }
```

2) Perform 100 puts on each table with 1MB payload:

```
TEST_P(OptimisticTransactionTest, SuccessTest) {
  WriteOptions write_options;
  std::string value = generate_random_string(1 * 1024 * 1024);

  for (auto& table : dbs) {
    std::cout << "Writing to " << table->GetName() << std::endl;
    for (int i = 0; i < 100; i++) {
      table->Put(write_options, std::to_string(i), value);
    }
  }
}
```

The behavior that I was initially observing was that a write would deadlock once the limit was reached. In the unit test this issue was observed much sooner with identical back trace:

```
Thread 1 (Thread 0x7f2b23285c00 (LWP 2800024) "optimistic_tran"):
#0  futex_wait (private=0, expected=2, futex_word=0x7fffd5cc0bb0) at ../sysdeps/nptl/futex-internal.h:146
#1  __GI___lll_lock_wait (futex=futex@entry=0x7fffd5cc0bb0, private=0) at ./nptl/lowlevellock.c:49
#2  0x00007f2b210a9682 in lll_mutex_lock_optimized (mutex=0x7fffd5cc0bb0) at ./nptl/pthread_mutex_lock.c:48
#3  ___pthread_mutex_lock (mutex=0x7fffd5cc0bb0) at ./nptl/pthread_mutex_lock.c:93
#4  0x00007f2b2249d330 in __gthread_mutex_lock (__mutex=0x7fffd5cc0bb0) at /usr/include/x86_64-linux-gnu/c++/13/bits/gthr-default.h:749
#5  0x00007f2b2249e372 in std::mutex::lock (this=0x7fffd5cc0bb0) at /usr/include/c++/13/bits/std_mutex.h:113
#6  0x00007f2b2249f9eb in std::unique_lock<std::mutex>::lock (this=0x7fffd5cbfc30) at /usr/include/c++/13/bits/unique_lock.h:141
#7  0x00007f2b2249ebbf in std::unique_lock<std::mutex>::unique_lock (this=0x7fffd5cbfc30, __m=...) at /usr/include/c++/13/bits/unique_lock.h:71
#8  0x00007f2b228fd476 in rocksdb::WriteBufferManager::BeginWriteStall (this=0x7fffd5cc0b40, wbm_stall=0x556309f9b4a0) at /home/vjeko/dev/rocksdb/memtable/write_buffer_manager.cc:125
#9  0x00007f2b2265c480 in rocksdb::DBImpl::WriteBufferManagerStallWrites (this=0x556309f8c240) at /home/vjeko/dev/rocksdb/db/db_impl/db_impl_write.cc:1919
#10 0x00007f2b22658be4 in rocksdb::DBImpl::PreprocessWrite (this=0x556309f8c240, write_options=..., log_context=0x7fffd5cc02c0, write_context=0x7fffd5cc02e0) at /home/vjeko/dev/rocksdb/db/db_impl/db_impl_write.cc:1225
#11 0x00007f2b22653ebf in rocksdb::DBImpl::WriteImpl (this=0x556309f8c240, write_options=..., my_batch=0x7fffd5cc0af0, callback=0x0, log_used=0x0, log_ref=0, disable_memtable=false, seq_used=0x0, batch_cnt=0, pre_release_callback=0x0, post_memtable_callback=0x0) at /home/vjeko/dev/rocksdb/db/db_impl/db_impl_write.cc:384
#12 0x00007f2b22652cb0 in rocksdb::DBImpl::Write (this=0x556309f8c240, write_options=..., my_batch=0x7fffd5cc0af0) at /home/vjeko/dev/rocksdb/db/db_impl/db_impl_write.cc:146
#13 0x00007f2b2265e664 in rocksdb::DB::Put (this=0x556309f8c240, opt=..., column_family=0x556309fc4b80, key=..., value=...) at /home/vjeko/dev/rocksdb/db/db_impl/db_impl_write.cc:2335
#14 0x00007f2b226523c0 in rocksdb::DBImpl::Put (this=0x556309f8c240, o=..., column_family=0x556309fc4b80, key=..., val=...) at /home/vjeko/dev/rocksdb/db/db_impl/db_impl_write.cc:28
#15 0x00007f2b22bc7038 in rocksdb::StackableDB::Put (this=0x55630a020190, options=..., column_family=0x556309fc4b80, key=..., val=...) at /home/vjeko/dev/rocksdb/include/rocksdb/utilities/stackable_db.h:82
#16 0x00007f2b225e8bbc in rocksdb::DB::Put (this=0x55630a020190, options=..., key=..., value=...) at /home/vjeko/dev/rocksdb/include/rocksdb/db.h:404
#17 0x00005563085664d8 in rocksdb::OptimisticTransactionTest_SuccessTest_Test::TestBody (this=0x556309f81110) at /home/vjeko/dev/rocksdb/utilities/transactions/optimistic_transaction_test.cc:118

```
I am also observing two additional issues that were not observed through JNI. The test would fail either with:

`C++ exception with description "Invalid argument" thrown in the test body.`

Or:

`Fatal glibc error: tpp.c:83 (__pthread_tpp_change_priority): assertion failed: new_prio == -1 || (new_prio >= fifo_min_prio && new_prio <= fifo_max_prio)`

**Comment by ajkr** [comment]
> This bug can be depicted more generally, a write targeting at a specific DB gets blocked by a WriteBufferManager and if the DB is NOT the dominant contributor to the memory pressure, the write hangs.

Agreed with one additional condition: the dominant contributors to the memory pressure do not receive writes so do not flush their memtables.

I think Speedb tackled this problem with their "Proactive Flushing" feature: https://github.com/speedb-io/documentation/blob/main/speedb-features/proactive-flushing.md

> if a write cause a run out of memory quota, a FlushJob is scheduled, which at least picks that write, so eventually, the memory pressure will be relieved.

It sounds like the write that gets flushed is the one that was hanging before the suggested change. Flushing one write at a time is technically making forward progress, but I think it's a situation we would still need to configure RocksDB to avoid.

**Comment by coltmcnealy-lh** [comment]
We ran into this issue. Is there any plan to fix it?
