### ISSUE TITLE
 Transaction could not check for conflicts for operation at SequenceNumber

### ISSUE THREAD

**Issue by siddhsql** [facebook/rocksdb#11822]
Hello, I used 

```
<dependency>
    <groupId>org.rocksdb</groupId>
    <artifactId>rocksdbjni</artifactId>
    <version>8.5.3</version>
</dependency>
```

to test RocksDB on MacOS AArch64. I have a test that does following:

1. Insert 10M records and measure time to insert
2. Insert one more record and measure time

My objective was to ensure that it is not saving all the data every time.

### Expected behavior

no error

### Actual behavior

I get error when I try to commit my second transaction (Step 2)

```
.opening DB
Time: 253 ms
DB Size = 26932 bytes
inserting 10000000 records
Time: 97944 ms
DB Size = 1190284377 bytes
closing DB
Time: 34 ms
DB Size = 1190284563 bytes
opening DB
Time: 23452 ms
DB Size = 1249077827 bytes
inserting 1 records
E
Time: 121.708
There was 1 failure:
1) test1(com.mycompany.app.TestRocksDBWith10MRecords)
org.rocksdb.RocksDBException: Transaction could not check for conflicts for operation at SequenceNumber 10000000 as the MemTable only contains changes newer than SequenceNumber 10000001.  Increasing the value of the max_write_buffer_size_to_maintain option could reduce the frequency of this error.
	at org.rocksdb.Transaction.commit(Native Method)
	at org.rocksdb.Transaction.commit(Transaction.java:207)
	at com.mycompany.app.TestRocksDBWith10MRecords.putRecords(TestRocksDBWith10MRecords.java:65)
	at com.mycompany.app.TestRocksDBWith10MRecords.test1(TestRocksDBWith10MRecords.java:33)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runners.Suite.runChild(Suite.java:127)
	at org.junit.runners.Suite.runChild(Suite.java:26)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:117)
	at org.junit.runner.JUnitCore.runMain(JUnitCore.java:96)
	at org.junit.runner.JUnitCore.runMainAndExit(JUnitCore.java:47)
	at org.junit.runner.JUnitCore.main(JUnitCore.java:40)
```

### Steps to reproduce the behavior

please see my complete code at https://gist.github.com/siddhsql/3ce7ca0d905be12863fbc4e315a30ead

also see: https://github.com/facebook/rocksdb/issues/1431

**Comment by thatsafunnyname** [comment]
I can also reproduce this using the attached C++ 
 
[test_seq_cc.txt](https://github.com/facebook/rocksdb/files/12662249/test_seq_cc.txt)
 

```
inserting 500000 records
inserting 1 record
Failed to commit 1 put records. Error: Operation failed. Try again.: Transaction could not check for conflicts 
for operation at SequenceNumber 500000 as the MemTable only contains changes newer than SequenceNumber 500001.  
Increasing the value of the max_write_buffer_size_to_maintain option could reduce the frequency of this error.
```

It reproduces using gcc 8.5.0 on AlmaLinux 8.8 with rocksdb-6.17.3 , rocksdb-7.10.2 and rocksdb-8.5.3 .
 
I am wondering if it could be an off-by-one error (for the sequence number) similar to the already mentioned https://github.com/facebook/rocksdb/issues/1431 , and https://github.com/facebook/rocksdb/pull/1458 .

**Comment by thatsafunnyname** [comment]
Running the C++ test with RocksDB version 4.8

```
> ./test.sh
inserting 500000 records
rocksdb-4.8/db/db_impl.cc:1419 CreateNewMemtable max_sequence=500000
rocksdb-4.8/db/db_impl.cc:1452 SetLastSequence(500000)
inserting 1 record
```

and 4.9
 
```
> ./test.sh
inserting 500000 records
rocksdb-4.9/db/db_impl.cc:1533 CreateNewMemtable next_sequence=500001
rocksdb-4.9/db/db_impl.cc:1567 SetLastSequence(500000)
inserting 1 record
Failed to commit 1 put records. Error: Operation failed. Try again.: Transaction could not check for conflicts for operation at SequenceNumber 500000 as the MemTable only contains changes newer than SequenceNumber 500001.  Increasing the value of the max_write_buffer_number_to_maintain option could reduce the frequency of
```

after this change to db/db_impl.cc in v4.9 :

```
cfd->CreateNewMemtable(*cfd->GetLatestMutableCFOptions(),
<<                       *next_sequence);
>>                       *next_sequence - 1);
```

```
> ./test.sh
inserting 500000 records
rocksdb-4.9/db/db_impl.cc:1533 CreateNewMemtable next_sequence - 1 =500000
rocksdb-4.9/db/db_impl.cc:1567 SetLastSequence(500000)
inserting 1 record
```
 
Xref:
 
https://github.com/facebook/rocksdb/pull/11861
 
All 40 PR checks passed.
