### ISSUE TITLE
Error while building RocksJava

### ISSUE THREAD

**Issue by areyohrahul** [facebook/rocksdb#11998]
Hi, I cloned the repo and checked out to tag v8.5.4

After this I ran  `make jclean clean rocksdbjavastaticreleasedocker` command. But, I'm getting the below error:

```
make[1]: Leaving directory '/rocksdb-local-build'
make rocksdbjavastatic_javalib
make[1]: Entering directory '/rocksdb-local-build'
$DEBUG_LEVEL is 0, $LIB_MODE is shared
cd java; make javalib
make[2]: Entering directory '/rocksdb-local-build/java'
echo 'Java version is Error: A JNI error has occurred, please check your installation and try again Exception in thread "main" java.lang.ExceptionInInitializerError    at java.util.Locale.getDefault(Locale.java:836)   at java.text.MessageFormat.<init>(MessageFormat.java:361)       at java.text.MessageFormat.format(MessageFormat.java:840)       at sun.launcher.LauncherHelper.getLocalizedMessage(LauncherHelper.java:426)       at sun.launcher.LauncherHelper.abort(LauncherHelper.java:547)   at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:653)       at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:632) Caused by: java.lang.ArrayIndexOutOfBoundsException: 0   at java.util.Locale$1.<clinit>(Locale.java:836)         ... 7 more, minimum required version is 8'
cp -v ~/.m2/repository/junit/junit/4.13.1/junit-4.13.1.jar test-libs
Java version is Error: A JNI error has occurred, please check your installation and try again Exception in thread "main" java.lang.ExceptionInInitializerError  at java.util.Locale.getDefault(Locale.java:836)   at java.text.MessageFormat.<init>(MessageFormat.java:361)       at java.text.MessageFormat.format(MessageFormat.java:840)       at sun.launcher.LauncherHelper.getLocalizedMessage(LauncherHelper.java:426)       at sun.launcher.LauncherHelper.abort(LauncherHelper.java:547)   at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:653)       at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:632) Caused by: java.lang.ArrayIndexOutOfBoundsException: 0   at java.util.Locale$1.<clinit>(Locale.java:836)         ... 7 more, minimum required version is 8
exit 1
make[2]: *** [Makefile:315: java-version] Error 1
make[2]: *** Waiting for unfinished jobs....
`/root/.m2/repository/junit/junit/4.13.1/junit-4.13.1.jar' -> `test-libs/junit-4.13.1.jar'
make[2]: Leaving directory '/rocksdb-local-build/java'
make[1]: *** [Makefile:2282: rocksdbjavastatic_javalib] Error 2
make[1]: Leaving directory '/rocksdb-local-build'
make: *** [Makefile:2244: rocksdbjavastatic] Error 2
make: *** [rocksdbjavastaticdockerx86] Error 2
```

Java version  - "1.8.0_381"
Os - M2 OSx Monterey

Can someone please tell me what am I doing wrong?

P.S - This happens after OSX build is complete and rocksddbjni-x.y.z_osx.jar is built

**Comment by areyohrahul** [comment]
I also tried running `make jclean clean rocksdbjavastaticdockerx86_64` but got the following error

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (safepoint.cpp:388), pid=21298, tid=0x0000004063812700
#  guarantee(PageArmed == 0) failed: invariant
#
# JRE version: OpenJDK Runtime Environment (8.0_275-b01) (build 1.8.0_275-b01)
# Java VM: OpenJDK 64-Bit Server VM (25.275-b01 mixed mode linux-amd64 compressed oops)
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /rocksdb-local-build/java/hs_err_pid21298.log
#
# If you would like to submit a bug report, please visit:
#   https://bugzilla.redhat.com/enter_bug.cgi?product=Red%20Hat%20Enterprise%20Linux%206&component=java-1.8.0-openjdk
#
qemu: uncaught target signal 6 (Aborted) - core dumped
make[2]: *** [Makefile:332: javadocs] Aborted
make[2]: Leaving directory '/rocksdb-local-build/java'
make[1]: *** [Makefile:2282: rocksdbjavastatic_javalib] Error 2
make[1]: Leaving directory '/rocksdb-local-build'
make: *** [Makefile:2244: rocksdbjavastatic] Error 2
make: *** [rocksdbjavastaticdockerx86_64] Error 2

```

**Comment by gywndi** [comment]
I think this issue is not sovled yet.
```
$ make jclean clean rocksdbjavastaticreleasedocker

.. skip ..

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (safepoint.cpp:388), pid=22994, tid=0x94d9db70
#  guarantee(PageArmed == 0) failed: invariant
#
# JRE version: OpenJDK Runtime Environment (8.0_275-b01) (build 1.8.0_275-b01)
# Java VM: OpenJDK Server VM (25.275-b01 mixed mode linux-x86 )
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /rocksdb-local-build/java/hs_err_pid22994.log
#
# If you would like to submit a bug report, please visit:
#   https://bugzilla.redhat.com/enter_bug.cgi?product=Red%20Hat%20Enterprise%20Linux%206&component=java-1.8.0-openjdk
#
qemu: uncaught target signal 6 (Aborted) - core dumped
make[2]: *** [Makefile:453: java_test] Aborted
make[2]: Leaving directory '/rocksdb-local-build/java'
make[1]: *** [Makefile:2332: rocksdbjavastatic_javalib] Error 2
make[1]: Leaving directory '/rocksdb-local-build'
make: *** [Makefile:2294: rocksdbjavastatic] Error 2
make: *** [rocksdbjavastaticdockerx86] Error 2
```

Is there any problems with dockers on arm macbook?? (my pc is M3)
