### ISSUE TITLE
org.rocksdb.RocksDBException: Compaction sees out-of-order keys

### ISSUE THREAD

**Issue by alnzng** [facebook/rocksdb#12119]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

We have observed that our applications failed with Rocksdb `Compaction sees out-of-order keys` issue after we bumped the Java Rocksdb client version from `6.6.4` to `7.0.3`. The issue is similar as this existing reported issue  [8248](https://github.com/facebook/rocksdb/issues/8248) 

We noticed that since the version `6.14` Rocksdb added [a new feature](https://github.com/facebook/rocksdb/commit/750817555867a43f0e7b73dffa44756a9136c808) `check_flush_compaction_key_order`, and I'm suspecting this feature caused our applications failed because the new feature is enabled by default.

I wanted to see if I can use Java Rocksdb client to disable this new feature, but seems there is no method available like `options.setCheckFlushCompactionKeyOrder(false)` for testing.

I would like to check with Rocksdb community a few questions:

- What kind of scenarios that Rocksdb can produce such out-of-order keys? 
- Can this feature `check_flush_compaction_key_order ` cause the error `Compaction sees out-of-order keys`?
- Do we support a way to disable this `check_flush_compaction_key_order` feature in Java Rocksdb client?

### Expected behavior
The application should not be failed with this issue after Rocksdb version bump

### Actual behavior
The application failed with below exception after bumped up Rocksdb version from `6.6.4` to `7.0.3`

```
Caused by: org.rocksdb.RocksDBException: Compaction sees out-of-order keys.
	at org.rocksdb.RocksDB.write0(Native Method) ~[org.rocksdb-rocksdbjni-7.0.3.jar:?]
	at org.rocksdb.RocksDB.write(RocksDB.java:1706) ~[org.rocksdb-rocksdbjni-7.0.3.jar:?]
	at org.apache.samza.storage.kv.RocksDbKeyValueStore.$anonfun$putAll$1(RocksDbKeyValueStore.scala:206) ~[com.linkedin.samza-li-samza-kv-rocksdb_2.12-323.1085.2.13.jar:?]
	at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23) ~[org.scala-lang-scala-library-2.12.11.jar:?]
	at org.apache.samza.storage.kv.RocksDbKeyValueStore.org$apache$samza$storage$kv$RocksDbKeyValueStore$$ifOpen(RocksDbKeyValueStore.scala:290) ~[com.linkedin.samza-li-samza-kv-rocksdb_2.12-323.1085.2.13.jar:?]
	at org.apache.samza.storage.kv.RocksDbKeyValueStore.putAll(RocksDbKeyValueStore.scala:187) ~[com.linkedin.samza-li-samza-kv-rocksdb_2.12-323.1085.2.13.jar:?] 
```

**Comment by ajkr** [comment]
> What kind of scenarios that Rocksdb can produce such out-of-order keys? 

Some scenarios: the input files have out-of-order keys, memory corruption (either by RocksDB itself or the application corrupting RocksDB's memory), known bugs in older versions like https://github.com/facebook/rocksdb/issues/7405#issuecomment-694595587, unknown bugs, and hardware errors.

> Can this feature check_flush_compaction_key_order  cause the error Compaction sees out-of-order keys?

It can surface existing corruptions and prevent some new corruptions from being written. The original cause of the corruption is likely elsewhere.

> Do we support a way to disable this check_flush_compaction_key_order feature in Java Rocksdb client?

I think the property-based API should allow you to disable it: https://javadoc.io/doc/org.rocksdb/rocksdbjni/latest/org/rocksdb/ColumnFamilyOptions.html#getColumnFamilyOptionsFromProps-java.util.Properties-

**Comment by alnzng** [comment]
Thanks for answering my questions @ajkr , and the answers are very helpful! A few follow up questions:

>the input files have out-of-order keys

My understanding is that Rocksdb maintain these keys internally. If my application has only a single thread to write data into a Rocksdb store, we should not see out-of-order keys happened, and this problem can only occur if multiple threads access the same Rocksdb store. Right?

>It can surface existing corruptions and prevent some new corruptions from being written. The original cause of the corruption is likely elsewhere.

That makes sense. But I was actually just checking if this specific exception message was thrown with this feature enabled.

**Comment by alnzng** [comment]
It would be great if we can support full Rocksdb options in the Java client, BTW.

**Comment by swikar1** [comment]
@alnzng I am interested to take a look at this issue. As I am new here. Do you mind navigating me to specific src, class, folder java where this issue relates to?  Thanks.

**Comment by alnzng** [comment]
@swikar1 The error was thrown from a [Samza](https://github.com/apache/samza) application, from above stacktrace you can see the Java class(`RocksDB.java:1706` in rocksdb repo) where has the out-of-order keys check.

Is this what you were looking for?
