### ISSUE TITLE
rockdbjni loadLibraryFromJarToTemp fails when file is already present

### ISSUE THREAD

**Issue by clumsy** [facebook/rocksdb#1228]
```
Caused by: java.lang.RuntimeException: File: ...\librocksdbjni-win64.dll could not be created.
	at org.rocksdb.NativeLibraryLoader.loadLibraryFromJarToTemp(NativeLibraryLoader.java:91)
	at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:78)
	at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:56)
	at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:47)
	at org.rocksdb.RocksDB.<clinit>(RocksDB.java:23)
	... 37 more
```

Proposed fix:

```
...
File loadLibraryFromJarToTemp(final String tmpDir) throws IOException {
    final File temp;
    if (tmpDir == null || tmpDir.isEmpty()) {
      temp = File.createTempFile(tempFilePrefix, tempFileSuffix);
    } else {
      temp = new File(tmpDir, jniLibraryFileName);
      if (temp.exists() && !temp.delete()) {
        throw new RuntimeException("File: " + temp.getAbsolutePath() + " already exists and cannot be removed.");
      }
      if (!temp.createNewFile()) {
        throw new RuntimeException("File: " + temp.getAbsolutePath() + " could not be created.");
      }
    }
...
```

**Comment by adamretter** [comment]
Closed by https://github.com/facebook/rocksdb/pull/1232

**Comment by serioga** [comment]
```
      if (temp.exists() && !temp.delete()) {
        throw new RuntimeException("File: " + temp.getAbsolutePath() + " already exists and cannot be removed.");
      }
```
Looks like this fix does not play well if I start multiple apps on the same Windows machine.
So the first started app does not allow the second one to start xtdb node.
Very frustrating...

**Comment by serioga** [comment]
@adamretter The issue #12780 has been opened.
