### ISSUE TITLE
RocksDB on windows (librocksdbjni-win64.dll)- Can't find dependent libraries

### ISSUE THREAD

**Issue by kobikis** [facebook/rocksdb#1302]
While using 4.9.0 on Win7 (on vm) I got this error, (the dll exists)

```
Caused by: java.lang.UnsatisfiedLinkError: C:\Users\kobi\AppData\Local\Temp\librocksdbjni3993939733537201067.dll: Can't find dependent libraries
at java.lang.ClassLoader$NativeLibrary.load(Native Method)
at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1965)
at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1890)
at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1851)
at java.lang.Runtime.load0(Runtime.java:795)
at java.lang.System.load(System.java:1062)
at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:78)
at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:56)
at org.rocksdb.RocksDB.(RocksDB.java:23)
at org.rocksdb.ColumnFamilyOptions.(ColumnFamilyOptions.java:22)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
```

**Comment by adamretter** [comment]
@kobikis Can you find out what the missing dependencies are by running Dependency Walker as described here please: http://stackoverflow.com/questions/6092200/how-to-fix-an-unsatisfiedlinkerror-cant-find-dependent-libraries-in-a-jni-pro

**Comment by kobikis** [comment]
@adamretter these are all the missing dependencies from Dependency Walker:

API-MS-WIN-CRT-CONVERT-L1-1-0.DLL
API-MS-WIN-CRT-ENVIRONMENT-L1-1-0.DLL
API-MS-WIN-CRT-FILESYSTEM-L1-1-0.DLL
API-MS-WIN-CRT-HEAP-L1-1-0.DLL
API-MS-WIN-CRT-MATH-L1-1-0.DLL
API-MS-WIN-CRT-RUNTIME-L1-1-0.DLL
API-MS-WIN-CRT-STDIO-L1-1-0.DLL
API-MS-WIN-CRT-STRING-L1-1-0.DLL
API-MS-WIN-CRT-TIME-L1-1-0.DLL
MSVCP140.DLL
VCRUNTIME140.DLL
IESHIMS.DLL

**Comment by adamretter** [comment]
@kobikis I think you might need the Visual C++ runtime for Visual Studio 2015 installed, you can find it here https://www.microsoft.com/en-us/download/details.aspx?id=48145.

Can you install that and let me know if it fixes the issue please?

**Comment by kobikis** [comment]
Thanks @adamretter  my code is working well on Windows 7 without Snappy compression.

**Comment by habdank** [comment]
In which version whis and #1177 bug was closed? I have version 4.8.0 and it is also ending with:
Caused by: java.lang.RuntimeException: librocksdbjni-win64.dll was not found inside JAR.
	at org.rocksdb.NativeLibraryLoader.loadLibraryFromJarToTemp(NativeLibraryLoader.java:106)
	at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:78)
	at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:56)
	at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:47)
	at org.rocksdb.RocksDB.<clinit>(RocksDB.java:23)
	... 37 more

**Comment by adamretter** [comment]
@habdank as it says in #1177 version 4.9 was the first to include a Windows build of RocksDB.

**Comment by cgantzhorn** [comment]
For those of you suffering from this problem still (RocksDB 5.0.1):

1. Native libraries can only be loaded from special paths, configured and initialized by the VM
2. The RocksDB DLL for your version of Windows must be located in a folder that is already in the PATH environment variable
3. The current RocksDB temp-file-DLL-extraction process will not work, unless the temporary file is created in a folder that is already in the PATH

There are a few ways around this, but none are ideal:
1. You can configure the java.library.path System property to control which folders are used for native library loading, but you may run into issues and conflicts depending on what other native libraries you need
2. A native library can be loaded from a JAR provided the JAR is signed and the library is named the same as the JAR (IIRC, not completely sure)

IMO, these types of work-arounds for a Java library violate the intent of a language like Java.  One shouldn't have to go through platform-specific workarounds to use a JAR.  Having said that, I don't really have a solution for this problem.

**Comment by egn1** [comment]
Can it be that rocksdb binary is compiled with debug?

**Comment by adamretter** [comment]
Is this still an issue with 5.8.6?

**Comment by egn1** [comment]
I don't know what version the lib is. It seems to be delivered together with [opendedup](http://opendedup.org/odd/overview/). 

I have all redistributables installed. The strange thing is that there seems to be kind of circular dependency.N

![grafik](https://user-images.githubusercontent.com/7036868/33198240-334c9c26-d0ea-11e7-940d-b98a2910db6a.png)

**Comment by sandeeptiet** [comment]
Hi, 

I am Window 7 user and using kafka-streams 1.1.0 (Latest) version. When I am executing my code, I am getting the issue "StreamThread-1" **java.lang.UnsatisfiedLinkError:** C:\Users\sandeep\AppData\Local\Temp\librocksdbjni4271925274440341234.dll:  âÑX". Earlier I was using 0.11.0.0 version, and was getting "RocksDB on windows (librocksdbjni-win64.dll)- Can't find dependent libraries". Then as per your this thread I downloaded and installed **Visual C++ runtime for Visual Studio 2015** and upgraded  the kafka-stream version from 0.11.0.0 to 1.1.0. But still I am getting the same exception (java.lang.UnsatisfiedLinkError). Only thing changed is that instead of "Can't find dependent libraries" now I am getting  "âÑX" ( a strange expression). 

Also I checked that in my maven dependencies I am using RocksDbJni version 5.7.3 and it contains "librocksdbjni-win64.dll" file as well. 

Please find below the exception, I am getting (with kafka-streams version 1.1.0) :  - 

Exception in thread "streams-starter-app-862326ca-30c0-468d-898c-e40d4578f1c7-StreamThread-1" java.lang.UnsatisfiedLinkError: C:\Users\sandeep\AppData\Local\Temp\librocksdbjni4271925274440341234.dll:  âÑX
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1929)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1814)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1083)
	at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:78)
	at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:56)
	at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:64)
	at org.rocksdb.RocksDB.<clinit>(RocksDB.java:35)
	at org.rocksdb.Options.<clinit>(Options.java:25)
	at org.apache.kafka.streams.state.internals.RocksDBStore.openDB(RocksDBStore.java:116)
	at org.apache.kafka.streams.state.internals.RocksDBStore.init(RocksDBStore.java:167)
	at org.apache.kafka.streams.state.internals.ChangeLoggingKeyValueBytesStore.init(ChangeLoggingKeyValueBytesStore.java:40)
	at org.apache.kafka.streams.state.internals.CachingKeyValueStore.init(CachingKeyValueStore.java:63)
	at org.apache.kafka.streams.state.internals.InnerMeteredKeyValueStore.init(InnerMeteredKeyValueStore.java:160)
	at org.apache.kafka.streams.state.internals.MeteredKeyValueBytesStore.init(MeteredKeyValueBytesStore.java:102)
	at org.apache.kafka.streams.processor.internals.AbstractTask.registerStateStores(AbstractTask.java:225)
	at org.apache.kafka.streams.processor.internals.StreamTask.initializeStateStores(StreamTask.java:162)
	at org.apache.kafka.streams.processor.internals.AssignedTasks.initializeNewTasks(AssignedTasks.java:88)
	at org.apache.kafka.streams.processor.internals.TaskManager.updateNewAndRestoringTasks(TaskManager.java:316)
	at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:789)
	at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:750)
	at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:720)
INFO stream-client [streams-starter-app-862326ca-30c0-468d-898c-e40d4578f1c7] State transition from ERROR to PENDING_SHUTDOWN (org.apache.kafka.streams.KafkaStreams:261) 


Please find below the exception, (with kafka-streams version 0.11.0.0 and prior to installing "Visual C++ runtime for Visual Studio 2015") : - 

WARN stream-thread [streams-starter-app-4be266bc-fcc9-4c1e-93be-807e3736d6cb-StreamThread-1] Unexpected state transition from ASSIGNING_PARTITIONS to DEAD. (org.apache.kafka.streams.processor.internals.StreamThread:978) 
INFO stream-client [streams-starter-app-4be266bc-fcc9-4c1e-93be-807e3736d6cb] State transition from REBALANCING to PENDING_SHUTDOWN. (org.apache.kafka.streams.KafkaStreams:229) 
java.lang.UnsatisfiedLinkError: C:\Users\sandeep\AppData\Local\Temp\librocksdbjni6620964825573124271.dll: Can't find dependent libraries
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1929)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1814)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1083)
	at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:78)
	at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:56)
	at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:64)
	at org.rocksdb.RocksDB.<clinit>(RocksDB.java:35)
	at org.rocksdb.Options.<clinit>(Options.java:22)
	at org.apache.kafka.streams.state.internals.RocksDBStore.openDB(RocksDBStore.java:121)
	at org.apache.kafka.streams.state.internals.RocksDBStore.init(RocksDBStore.java:173)
	at org.apache.kafka.streams.state.internals.ChangeLoggingKeyValueBytesStore.init(ChangeLoggingKeyValueBytesStore.java:40)
	at org.apache.kafka.streams.state.internals.MeteredKeyValueStore$7.run(MeteredKeyValueStore.java:99)
	at org.apache.kafka.streams.processor.internals.StreamsMetricsImpl.measureLatencyNs(StreamsMetricsImpl.java:187)
	at org.apache.kafka.streams.state.internals.MeteredKeyValueStore.init(MeteredKeyValueStore.java:130)
	at org.apache.kafka.streams.state.internals.CachingKeyValueStore.init(CachingKeyValueStore.java:58)
	at org.apache.kafka.streams.processor.internals.AbstractTask.initializeStateStores(AbstractTask.java:201)
	at org.apache.kafka.streams.processor.internals.StreamTask.<init>(StreamTask.java:140)
	at org.apache.kafka.streams.processor.internals.StreamThread.createStreamTask(StreamThread.java:1234)
	at org.apache.kafka.streams.processor.internals.StreamThread$TaskCreator.createTask(StreamThread.java:294)
	at org.apache.kafka.streams.processor.internals.StreamThread$AbstractTaskCreator.retryWithBackoff(StreamThread.java:254)
	at org.apache.kafka.streams.processor.internals.StreamThread.addStreamTasks(StreamThread.java:1313)
	at org.apache.kafka.streams.processor.internals.StreamThread.access$1100(StreamThread.java:73)
	at org.apache.kafka.streams.processor.internals.StreamThread$RebalanceListener.onPartitionsAssigned(StreamThread.java:183)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.onJoinComplete(ConsumerCoordinator.java:265)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.joinGroupIfNeeded(AbstractCoordinator.java:363)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureActiveGroup(AbstractCoordinator.java:310)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:297)
	at org.apache.kafka.clients.consumer.KafkaConsumer.pollOnce(KafkaConsumer.java:1078)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1043)
	at org.apache.kafka.streams.processor.internals.StreamThread.pollRequests(StreamThread.java:582)
	at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:553)
	at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:527)
INFO stream-thread [streams-starter-app-4be266bc-fcc9-4c1e-93be-807e3736d6cb-StreamThread-1] Informed thread to shut down (org.apache.kafka.streams.processor.internals.StreamThread:900) 
WARN stream-thread [streams-starter-app-4be266bc-fcc9-4c1e-93be-807e3736d6cb-StreamThread-1] Unexpected state transition from DEAD to PENDING_SHUTDOWN. (org.apache.kafka.streams.processor.internals.StreamThread:978) 
INFO stream-client [streams-starter-app-4be266bc-fcc9-4c1e-93be-807e3736d6cb] Stopped Kafka Streams process. (org.apache.kafka.streams.KafkaStreams:514) 
INFO stream-client [streams-starter-app-4be266bc-fcc9-4c1e-93be-807e3736d6cb] State transition from PENDING_SHUTDOWN to NOT_RUNNING. (org.apache.kafka.streams.KafkaStreams:229) 

I think, the bug(#1302) reported here in this thread is still not fixed. Can someone help me in fixing this issue. As I am not able to proceed my first program in kafka-streams.

With Thanks and Regards,
Sandeep Kapoor
