### ISSUE TITLE
RocksDB JNI reads x64 build on ppc64 architecture

### ISSUE THREAD

**Issue by twiechert** [facebook/rocksdb#1317]
When running on a ppc64 architecture, the JNI wrapper should not try to use the pre-built librocksdbjni-linux64.so, which only runs on x64 architectures. Consequently, the shared library naming convention should consider the whole architecture name (e.g. X64/PPC64 instead of only 64).

**Comment by adamretter** [comment]
@twiechert Interesting! I can fix this pretty easily, but I need to know what the filename should be on:

a) PPC Linux?
b) PPC AIX?

Any ideas?

**Comment by twiechert** [comment]
I would suggest the default values returned by JVM property 'os.name'+ 'os.arch':
http://lopica.sourceforge.net/os.html

**Comment by bharatviswa504** [comment]
@adamretter Is ppc64 supported dll is it available in rocksdbJNI.jar?

**Comment by bharatviswa504** [comment]
@adamretter Would it be possible to include rockdbjni for ppc64 linux dll or could you please provide me instuctions to compile and include that dll in the jar?

**Comment by bharatviswa504** [comment]
@twiechert You have any instructions to make it work on ppc64?

**Comment by adamretter** [comment]
@twiechert I don't think that is sufficient, see http://stackoverflow.com/questions/29495805/best-practice-naming-strategy-for-native-library-locations-targetting-various-pr

Can anyone tell me what the JNI library name should be on Linux PPC 64?

**Comment by adamretter** [comment]
@bhamodi The issue is that we do not have a system on which we can build a PPC64 Linux library. If someone was able to provide me with a Linux PPC system of access to such a system with a suitable OS (we use CentOS 5 on x64), then I would be happy to include PPC64 builds.

**Comment by bharatviswa504** [comment]
@adamretter on linux ppc64 the library name can be librocksdbjni-ppc64.so similar to what we have now for linux32 bit librocksdbjni-linux32.so.

We have cluster's but we cannot access outside our VPN. It would be greatly helpful if we provide instructions for us for compilation, and after that I can send that library back to you.

Can we add similar code in Environment.java so that now it will have architecturename in native library name.

 public static boolean isPPC() {
    return (ARCH.contains("ppc"));
  }

if (isUnix()) {
 if(isPPC()) {
   return String.format("%sjni-%s", name, ARCH);
 }
 return String.format("%sjni-linux%s", name, ARCH);
}

**Comment by bharatviswa504** [comment]
@adamretter Could you please provide any information on the above comment.

Thanks,
Bharat

**Comment by adamretter** [comment]
@bharatviswa504 I just added a PR as you requested. I have also been in touch with IBM as an Open Source developer to try and get access to a POWER Linux system for testing this on. Hoping to hear back from them shortly...

**Comment by bharatviswa504** [comment]
@adamretter I am able to compile and test on power PC machine. 
Ohh that's great for contacting IBM. Hope they will provide and so that the PPC libraries will be accessible to community.  I think we need to consider about ppc64le also, as we have little endian format machine also. (the arch type will be ppc64le).

**Comment by adamretter** [comment]
@bharatviswa504 Okay so the I now have access to a `ppc64le` machine with RHEL 7.1 courtesy of IBM. As such I should be able to package RocksJava binaries for that too. Do we really need to also support `ppc64`, I did ask IBM if I could access to one of those also and their response seems to imply that `ppc64` would really only be relevant for AIX or much older Linux distros, their response to me:

> The majority of work being done on Community distributions is also for the Little Endian architecture - as is the development done by most Open Source Developers. This is why the Open Source Developer access only supports ppc64le instances.
 
> The ppc64 architecture is Big Endian - and is primarily used for our UNIX distribution, AIX. It is also used by older versions of Linux (RHEL 6.x, SLES 11).
 
> If you have a specific need to port your application to the ppc64 architecture, then we can arrange this...

**Comment by bharatviswa504** [comment]
@adamretter Ya we too are working for ppc64le machine for our release. So, from which version of rocksdb we will have PPC support?

**Comment by adamretter** [comment]
@bharatviswa504 I was just able to build the HEAD of RocksDB master branch on a IBM Power8 ppc64le system.

At the moment, I have a naming conflict though as the .so file generated is called `librocksdbjni-linux64.so` and the .jar file is `rocksdbjni-5.0.0-linux64.jar` which will clash with the x86_64 versions. So I need to give some thought to how we can work around that.

The main issue is that when you call `System.loadLibrary("rocksdb")` on either `x86_64` or `ppc64le` Linux platforms, they both expect a file called `librocksdbjni-linux64.so` in `java.library.path`; I think perhaps we could package them into the multi-platform jar with different names, and rename them when we extract them using `NativeLibraryLoader`, but I need to do some testing.

**Comment by adamretter** [comment]
@bharatviswa504 Does `make jtest` work for you on your ppc64le system? On the Power8 system I am getting:

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: /tmp/librocksdbjni5712817188350882327.so: /lib64/ld64.so.2: version `GLIBC_2.22' not found (required by /tmp/librocksdbjni5712817188350882327.so)
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1965)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1890)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1851)
        at java.lang.Runtime.load0(Runtime.java:795)
        at java.lang.System.load(System.java:1062)
        at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:78)
        at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:56)
        at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:64)
        at org.rocksdb.RocksDB.<clinit>(RocksDB.java:35)
        at org.rocksdb.RocksMemoryResource.<clinit>(RocksMemoryResource.java:16)
        at org.rocksdb.BackupableDBOptionsTest.<clinit>(BackupableDBOptionsTest.java:23)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:195)
        at org.rocksdb.test.RocksJunitRunner.main(RocksJunitRunner.java:58)
```

**Comment by bharatviswa504** [comment]
@adamretter I have not got any exceptions, but I have got some warnings
WARNING in native method: JNI call made without checking exceptions when required to from CallStaticVoidMethod
	at java.lang.Class.isInstance(Native Method)
	at org.junit.runners.model.TestClass.getAnnotatedFieldValues(TestClass.java:231)
	at org.junit.runners.ParentRunner.classRules(ParentRunner.java:255)
	at org.junit.runners.ParentRunner.withClassRules(ParentRunner.java:244)
	at org.junit.runners.ParentRunner.classBlock(ParentRunner.java:194)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:362)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:105)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:94)
	at org.rocksdb.test.RocksJunitRunner.main(RocksJunitRunner.java:60)
Run: org.rocksdb.BackupEngineTest testing now -> deleteBackup

**Comment by bharatviswa504** [comment]
@adamretter 

try {
        System.loadLibrary(sharedLibraryName); //trys to load rocksdbjni name from java.library.path
    } catch(final UnsatisfiedLinkError ule1) {
      try {
        System.loadLibrary(jniLibraryName); //trys to load jni library using architecture specific from java.library.path, because jniLibraryName uses getJniLibraryName(final String name) 
      } catch(final UnsatisfiedLinkError ule2) {
        loadLibraryFromJar(tmpDir); //from jar extracted native library
      }

So, i have not got where will be the conflict of loading on x86_64 and ppc?

**Comment by adamretter** [comment]
@bharatviswa504 How are you building RocksDB on PowerPC and what Hardware and OS versions do you have?

I am using RHEL 7.1 on a Power8 ppc64le, when I run the following:

```
$ git clone https://github.com/facebook/rocksdb.git
$ cd rocksdb
$ make clean jclean
$ make rocksdbjava
$ make jtest
```

I get the following error:

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: /tmp/librocksdbjni3037318745070348002.so: /lib64/ld64.so.2: version `GLIBC_2.22' not found (required by /tmp/librocksdbjni3037318745070348002.so)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1965)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1890)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1851)
	at java.lang.Runtime.load0(Runtime.java:795)
	at java.lang.System.load(System.java:1062)
	at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:78)
	at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:56)
	at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:64)
	at org.rocksdb.RocksDB.<clinit>(RocksDB.java:35)
	at org.rocksdb.RocksMemoryResource.<clinit>(RocksMemoryResource.java:16)
	at org.rocksdb.BackupableDBOptionsTest.<clinit>(BackupableDBOptionsTest.java:23)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:195)
	at org.rocksdb.test.RocksJunitRunner.main(RocksJunitRunner.java:58)
```

If I examine the .so file with ldd then I see:

```
linux-vdso64.so.1 (0x00003fff98b10000)
	libpthread.so.0 => /opt/at10.0/lib64/libpthread.so.0 (0x00003fff98470000)
	librt.so.1 => /opt/at10.0/lib64/librt.so.1 (0x00003fff98440000)
	libz.so.1 => /opt/at10.0/lib64/libz.so.1 (0x00003fff98400000)
	libtbb.so.2 => /opt/at10.0/lib64/libtbb.so.2 (0x00003fff983a0000)
	libtcmalloc.so.4 => /opt/at10.0/lib64/libtcmalloc.so.4 (0x00003fff98300000)
	libstdc++.so.6 => /opt/at10.0/lib64/libstdc++.so.6 (0x00003fff980d0000)
	libm.so.6 => /opt/at10.0/lib64/libm.so.6 (0x00003fff97fe0000)
	libgcc_s.so.1 => /opt/at10.0/lib64/libgcc_s.so.1 (0x00003fff97fa0000)
	libc.so.6 => /opt/at10.0/lib64/libc.so.6 (0x00003fff97db0000)
	/opt/at10.0/lib64/ld64.so.2 (0x00000000519d0000)
	libdl.so.2 => /opt/at10.0/lib64/libdl.so.2 (0x00003fff97d80000)
```

Any ideas why I can't run `make jtest` and you can?

**Comment by bharatviswa504** [comment]
@adamretter Are you able to compile, I did few changes in the makefile to download snappy other compression jars. As some links are broken. I have compiled rocksdb v4.9.

**Comment by adamretter** [comment]
I am reopening as we still have problems...

**Comment by adamretter** [comment]
@bharatviswa504 I am using the `master` branch of RocksDB. Can you try and build that with the command `make jcheck`.

Regards the JNI warnings you are getting, you need JDK 1.7.0 for compilation and not 1.8.0

**Comment by bharatviswa504** [comment]
@adamretter is still issues with trunk, if it is i can give a try tomorrow, and let you know on our PPC machines?

**Comment by adamretter** [comment]
@bharatviswa504 Yes, please try with the `HEAD` of the `master` branch.

**Comment by ayappanec** [comment]
@adamretter I think you are building rocksdb using Advanced Toolchain (AT) in ppc64le machine. Java couldn't able to find the AT provided "glibc". I think with the system provided toolchain, you won't get the problem. 

 By the way, i built the master branch and got the below error while running "make jtest"

Exception in thread "main" java.lang.ExceptionInInitializerError
        at org.rocksdb.RocksMemoryResource.<clinit>(RocksMemoryResource.java:16)
        at org.rocksdb.BackupableDBOptionsTest.<clinit>(BackupableDBOptionsTest.java:23)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:195)
        at org.rocksdb.test.RocksJunitRunner.main(RocksJunitRunner.java:58)
Caused by: java.lang.RuntimeException: librocksdbjni-linux-ppc64.so was not found inside JAR.
        at org.rocksdb.NativeLibraryLoader.loadLibraryFromJarToTemp(NativeLibraryLoader.java:110)
        at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:78)
        at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:56)
        at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:64)
        at org.rocksdb.RocksDB.<clinit>(RocksDB.java:35)
        ... 5 more
make[1]: *** [run_test] Error 1
make[1]: Leaving directory `/home/ayappan/rocksdb/java'
make: *** [jtest] Error 2

Apparently,  the jar file contains librocksdbjni-linux64.so ( not librocksdbjni-linux-ppc64.so )

**Comment by adamretter** [comment]
@ayappanec Do I need to switch between the Advanced Toolchain (AT) and system provided toolchain? If so, how do I do that? or is there something else I should do?

This is my first experience with ppc linux on Power8 ;-)

**Comment by ayappanec** [comment]
There is no need to switch between AT and system toolchain. You need to build it using system toolchain only. By removing "/opt/at10.0.." from the PATH env variable, we can make sure we build using system provided toolchain. And also check for LD_LIBRARY_PATH env variable. It should not have "/opt/at10.0.." . It's always  better to build using system toolchain if the library make it to maven central repository.

**Comment by ayappanec** [comment]
@adamretter Are you able to build using system toolchain ?

**Comment by ayappanec** [comment]
IBM actively pursues PowerPC64 Big-Endian architecture also in RHEL distros. May be one day, rocksdb can be ported to this architecture as well. So we have to particular about the library name. "os.arch" returns ppc64 in Big-Endian & ppc64le in Little-Endian. #1845 needs correction. It's better we get os.arch and append it directly to the library name like "librocksdbjni-linux-ppc64le" [ In intel, it will be librocksdbjni-linux-x86_64 ]

**Comment by ayappanec** [comment]
Right now, building rocksdbjava in PowerPC is broken due to JNI library name. I made a patch that fixes the issue in both PowerPC64 LE & BE. The commit here ->  https://github.com/ibmsoe/rocksdb/commit/457be9d9d85789915b45502a9abe33b9861708c2
"uname -m" and java's os.arch matches in PowerPC architecture. I made use of this advantage to fix the issue.

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
