### ISSUE TITLE
[Exception] Log file missed when using flush if WAL is enabled on HDFS.

### ISSUE THREAD

**Issue by dorispan** [facebook/rocksdb#1864]
We are using env_hdfs to save data on HDFS persistently, but a call to flush method will result in an Exception if WAL is enabled.

Here is the test code:
```cpp
  DB* db;
  Options options;
  // create the DB if it's not already present
  options.create_if_missing = true;

  Env* env = new rocksdb::HdfsEnv("hdfs://hdfs.host:9000");
  options.env = env;

  //  open DB
  Status s = DB::Open(options, kDBPath, &db);
  assert(s.ok());

 // Put key-value
  WriteOptions writeOptions;
  writeOptions.disableWAL=false;
  s = db->Put(writeOptions, "key1", "value1");
  s = db->Put(writeOptions, "key2", "value2");
  s = db->Put(writeOptions, "key3", "value3");
  s = db->Put(writeOptions, "sxxx3", "sxxxxxxxxxx3");
  assert(s.ok());
  std::string value;

  FlushOptions flush_options;
  flush_options.wait = true;
  db->Flush(flush_options);

  delete db;
  return 0;
```

Here is the error code and stack trace.
```
FSDataOutputStream#close error:
org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.hdfs.server.namenode.LeaseExpiredException): No lease on /user/lily.lk/one_ssd/rocksdb_simple_example/000103.log (inode 81364421): File does not exist. [Lease.  Holder: DFSClient_NONMAPREDUCE_1335839497_1, pendingcreates: 3]
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.checkLease(FSNamesystem.java:3559)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.completeFileInternal(FSNamesystem.java:3647)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.completeFile(FSNamesystem.java:3617)
        at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.complete(NameNodeRpcServer.java:704)
        at org.apache.hadoop.hdfs.server.namenode.AuthorizationProviderProxyClientProtocol.complete(AuthorizationProviderProxyClientProtocol.java:243)
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.complete(ClientNamenodeProtocolServerSideTranslatorPB.java:527)
        at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:619)
        at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1060)
        at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2044)
        at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2040)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:415)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1671)
        at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2038)

        at org.apache.hadoop.ipc.Client.call(Client.java:1468)
        at org.apache.hadoop.ipc.Client.call(Client.java:1399)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:232)
        at com.sun.proxy.$Proxy14.complete(Unknown Source)
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.complete(ClientNamenodeProtocolTranslatorPB.java:443)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:187)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)
        at com.sun.proxy.$Proxy15.complete(Unknown Source)
        at org.apache.hadoop.hdfs.DFSOutputStream.completeFile(DFSOutputStream.java:2283)
        at org.apache.hadoop.hdfs.DFSOutputStream.close(DFSOutputStream.java:2267)
        at org.apache.hadoop.fs.FSDataOutputStream$PositionCache.close(FSDataOutputStream.java:72)
        at org.apache.hadoop.fs.FSDataOutputStream.close(FSDataOutputStream.java:106)FSDataOutputStream#close error:
java.lang.NullPointerException
```

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
