### ISSUE TITLE
Getting java.lang.UnsatisfiedLinkError: Cannot load module /tmp/librocksdbjni858257496864179953.so

### ISSUE THREAD

**Issue by manishbansal8843** [facebook/rocksdb#2071]
Hi Team,

I am using kafka_2.11-0.10.2.0. I have downloaded the binaries directly from apache which contains rocksdbjni-5.0.1.jar. I am developing kafka streaming application. It is using RocksDB for internal purpose. However, during my application run, getting below error.

Exception in thread "StreamThread-1" java.lang.UnsatisfiedLinkError: /tmp/librocksdbjni858257496864179953.so (  0509-022 Cannot load module /tmp/librocksdbjni858257496864179953.so.
        0509-026 System error: Cannot run a file that does not have a valid format.)
        at java.lang.ClassLoader.loadLibraryWithPath(ClassLoader.java:1213)
        at java.lang.System.load(System.java:517)
        at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:78)
        at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:56)
        at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:64)
        at org.rocksdb.RocksDB.<clinit>(RocksDB.java:35)
        at java.lang.J9VMInternals.initializeImpl(Native Method)
        at java.lang.J9VMInternals.initialize(J9VMInternals.java:236)
        at org.rocksdb.Options.<clinit>(Options.java:22)
        at java.lang.J9VMInternals.initializeImpl(Native Method)
        at java.lang.J9VMInternals.initialize(J9VMInternals.java:236)
        at org.apache.kafka.streams.state.internals.RocksDBStore.openDB(RocksDBStore.java:115)

Platform: AIX 6.1 64 bit

**Comment by adamretter** [comment]
@manishbansal8843 We don't provide builds of the native component for AIX in the Jar file. As you are on AIX you will need to build your own.
