### ISSUE TITLE
repair coredump

### ISSUE THREAD

**Issue by siddontang** [facebook/rocksdb#2712]
Hi

I try ldb repair but meet coredump with error msg 

```
[WARN] [db/repair.cc:426] Table #65188: ignoring Corruption: LZ4 not supported or corrupted LZ4 compressed block contents
[WARN] [db/repair.cc:426] Table #65500: ignoring Corruption: LZ4 not supported or corrupted LZ4 compressed block contents
[WARN] [db/repair.cc:426] Table #64867: ignoring Corruption: LZ4 not supported or corrupted LZ4 compressed block contents
L0 files seqno 0 5718950487 vs. 0 5718783871
```

The coredump stack is:

```
#0  0x00007f11baaab1d7 in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install glibc-2.17-157.el7_3.5.x86_64 libgcc-4.8.5-11.el7.x86_64 libstdc++-4.8.5-11.el7.x86_64 zlib-1.2.7-17.el7.x86_64
(gdb) bt
#0  0x00007f11baaab1d7 in raise () from /lib64/libc.so.6
#1  0x00007f11baaac8c8 in abort () from /lib64/libc.so.6
#2  0x00000000006172c6 in CheckConsistency (vstorage=<optimized out>, this=<optimized out>) at db/version_builder.cc:167
#3  SaveTo (vstorage=0x2f1a5a0, this=<optimized out>) at db/version_builder.cc:271
#4  rocksdb::VersionBuilder::SaveTo (this=this@entry=0x2f1a360, vstorage=vstorage@entry=0x2f1a5a0) at db/version_builder.cc:399
#5  0x000000000063206f in rocksdb::VersionSet::LogAndApply (this=this@entry=0x7fffc08d8950, column_family_data=column_family_data@entry=0x308ee80, mutable_cf_options=..., edit_list=...,
    mu=mu@entry=0x7fffc08d8ab0, db_directory=db_directory@entry=0x0, new_descriptor_log=new_descriptor_log@entry=false, new_cf_options=new_cf_options@entry=0x0) at db/version_set.cc:2457
#6  0x000000000060e02f in LogAndApply (column_family_options=0x0, new_descriptor_log=false, db_directory=0x0, mu=0x7fffc08d8ab0, edit=0x7fffc08d7350, mutable_cf_options=..., column_family_data=0x308ee80,
    this=0x7fffc08d8950) at ./db/version_set.h:639
#7  AddTables (this=0x7fffc08d7ff0) at db/repair.cc:554
#8  rocksdb::(anonymous namespace)::Repairer::Run (this=this@entry=0x7fffc08d7ff0) at db/repair.cc:195
```

Does it mean that the database has already been corrupted?

**Comment by yiwu-arbug** [comment]
Can you double check if your ldb binary is linked with LZ4? If so, seems likely the db is corrupted.

**Comment by siddontang** [comment]
@yiwu-arbug 

I think the DB is corrupted because I can even see the data deleted before.
