### ISSUE TITLE
Rocksdb dependency issue

### ISSUE THREAD

**Issue by stonelazy** [facebook/rocksdb#2918]
```
 java.lang.ExceptionInInitializerError
at org.rocksdb.Options.<clinit>(Options.java:22)
	at org.apache.kafka.streams.state.internals.RocksDBStore.openDB(RocksDBStore.java:121)
	at org.apache.kafka.streams.state.internals.Segment.openDB(Segment.java:40)
	at org.apache.kafka.streams.state.internals.Segments.getOrCreateSegment(Segments.java:86)
	at org.apache.kafka.streams.state.internals.RocksDBSegmentedBytesStore.put(RocksDBSegmentedBytesStore.java:81)
	at org.apache.kafka.streams.state.internals.ChangeLoggingSegmentedBytesStore.put(ChangeLoggingSegmentedBytesStore.java:58)
	at org.apache.kafka.streams.state.internals.MeteredSegmentedBytesStore.put(MeteredSegmentedBytesStore.java:105)
	at org.apache.kafka.streams.state.internals.RocksDBWindowStore.put(RocksDBWindowStore.java:107)
	at org.apache.kafka.streams.state.internals.RocksDBWindowStore.put(RocksDBWindowStore.java:100)
	at org.apache.kafka.streams.kstream.internals.KStreamJoinWindow$KStreamJoinWindowProcessor.process(KStreamJoinWindow.java:64)
	at org.apache.kafka.streams.processor.internals.ProcessorNode$1.run(ProcessorNode.java:47)
	at org.apache.kafka.streams.processor.internals.StreamsMetricsImpl.measureLatencyNs(StreamsMetricsImpl.java:187)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:133)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:82)
	at org.apache.kafka.streams.processor.internals.SourceNode.process(SourceNode.java:80)
	at org.apache.kafka.streams.processor.internals.StreamTask.process(StreamTask.java:190)
	at org.apache.kafka.streams.processor.internals.StreamThread.processAndPunctuate(StreamThread.java:671)
	at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:549)
	at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:519)

> Caused by: java.lang.NullPointerException
> 	at org.rocksdb.NativeLibraryLoader.loadLibraryFromJarToTemp(NativeLibraryLoader.java:107)
> 	at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:78)
> 	at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:56)
> 	at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:64)
> 	at org.rocksdb.RocksDB.<clinit>(RocksDB.java:35)
```

**Comment by stonelazy** [comment]
Am working in MAC.. been trying to debug for some days.. can someone please help me ?

**Comment by publicocean0** [comment]
it seams you have not the library for mac os .Go in debug in loadLibraryFromJarToTemp function. You can check it

**Comment by adamretter** [comment]
@stonelazy did you get to the bottom of your issue?

**Comment by sagar0** [comment]
@stonelazy @publicocean0 @adamretter 
It would be great if you could move this discussion to the RocksDB dev group: https://www.facebook.com/groups/rocksdb.dev . You should get more help from the RocksDB community there. We plan to use Github Issues as a place for bugs-only going forward. 
I sincerely apologize for closing this issue.
