### ISSUE TITLE
write stall , background job bug ?

### ISSUE THREAD

**Issue by mm304321141** [facebook/rocksdb#3058]
for testing mongo-rocks , set `write_buffer_size=65536` , run `jstests/core/*.js`
finally write stall at `jstests/core/index_big1.js`

```
-rw-r--r--. 1 terark terark  66M 2017-10-23 15:36 002889.sst
-rw-r--r--. 1 terark terark  11K 2017-10-23 15:36 002890.sst
-rw-r--r--. 1 terark terark  67M 2017-10-23 15:36 002891.sst
-rw-r--r--. 1 terark terark  14M 2017-10-23 15:36 002892.sst
-rw-r--r--. 1 terark terark   16 2017-10-23 15:31 CURRENT
-rw-r--r--. 1 terark terark   37 2017-10-23 15:31 IDENTITY
drwxr-xr-x. 2 terark terark 4.0K 2017-10-23 15:36 journal
-rw-r--r--. 1 terark terark    0 2017-10-23 15:31 LOCK
-rw-rw-r--. 1 terark terark 4.2M 2017-10-23 15:36 LOG
-rw-rw-r--. 1 terark terark  14K 2017-10-23 15:31 LOG.old.1508743903009543
-rw-rw-r--. 1 terark terark  21K 2017-10-23 15:31 LOG.old.1508743903029611
-rw-r--r--. 1 terark terark 136K 2017-10-23 15:36 MANIFEST-000010
-rw-r--r--. 1 terark terark 6.3K 2017-10-23 15:31 OPTIONS-000010
-rw-r--r--. 1 terark terark 6.3K 2017-10-23 15:31 OPTIONS-000013

journal:
-rw-r--r--. 1 terark terark 58K 2017-10-23 15:36 002888.log
-rw-r--r--. 1 terark terark 59K 2017-10-23 15:36 002893.log
-rw-r--r--. 1 terark terark 56K 2017-10-23 15:36 002894.log
-rw-r--r--. 1 terark terark 57K 2017-10-23 15:36 002895.log
-rw-r--r--. 1 terark terark   0 2017-10-23 15:36 002896.log
```

4  log files , but all BGThreads are waiting cv
```
#0  0x00007ff79a1746d5 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00000000021423dc in __gthread_cond_wait (__mutex=<optimized out>, __cond=__cond@entry=0x4326958) at /data/software/gcc/build/x86_64-unknown-linux-gnu/libstdc++-v3/include/x86_64-unknown-linux-gnu/bits/gthr-default.h:864
#2  std::condition_variable::wait (this=this@entry=0x4326958, __lock=...) at ../../../../../gcc-4.8.5/libstdc++-v3/src/c++11/condition_variable.cc:52
#3  0x00000000010afaa3 in rocksdb::ThreadPoolImpl::Impl::BGThread (this=this@entry=0x43268c0, thread_id=thread_id@entry=3) at util/threadpool_imp.cc:179
#4  0x00000000010afe1d in rocksdb::ThreadPoolImpl::Impl::BGThreadWrapper (arg=0x4152740) at util/threadpool_imp.cc:260
#5  0x0000000002145d70 in std::(anonymous namespace)::execute_native_thread_routine (__p=<optimized out>) at ../../../../../gcc-4.8.5/libstdc++-v3/src/c++11/thread.cc:84
#6  0x00007ff79a170dc5 in start_thread () from /lib64/libpthread.so.0
#7  0x00007ff799e9f76d in clone () from /lib64/libc.so.6
```

this is `tail -n 100 LOG`
```
2017/10/23-15:36:09.971601 7f361cba5700 (Original Log Time 2017/10/23-15:36:09.971521) [default] Level-0 commit table #2878: memtable #1 done
2017/10/23-15:36:09.971606 7f361cba5700 (Original Log Time 2017/10/23-15:36:09.971542) EVENT_LOG_v1 {"time_micros": 1508744169971532, "job": 2317, "event": "flush_finished", "lsm_state": [4, 0, 0, 0, 0, 0, 3], "immutable_memtables": 0}
2017/10/23-15:36:09.971611 7f361cba5700 (Original Log Time 2017/10/23-15:36:09.971567) [default] Level summary: base level 6 max bytes base 536870913 files[4 0 0 0 0 0 3] max score 1.00
2017/10/23-15:36:09.971621 7f361cba5700 [JOB 2317] Try to delete WAL files size 57803, prev total WAL file size 58977, number of live WAL files 2.
2017/10/23-15:36:09.971667 7f361d3a6700 [default] [JOB 2318] Compacting 4@0 + 3@6 files to L6, score 1.00
2017/10/23-15:36:09.971686 7f361d3a6700 [default] Compaction start summary: Base version 1553 Base level 0, inputs: [2878(45KB) 2876(58KB) 2874(58KB) 2872(58KB)], [2754(65MB) 2763(66MB) 2870(12MB)]
2017/10/23-15:36:09.971713 7f361d3a6700 EVENT_LOG_v1 {"time_micros": 1508744169971697, "job": 2318, "event": "compaction_started", "files_L0": [2878, 2876, 2874, 2872], "files_L6": [2754, 2763, 2870], "score": 1, "input_data_size": 151772206}
2017/10/23-15:36:10.301174 7f361d3a6700 [default] [JOB 2318] Generated table #2879: 122096 keys, 68708752 bytes
2017/10/23-15:36:10.301225 7f361d3a6700 EVENT_LOG_v1 {"time_micros": 1508744170301197, "cf_name": "default", "job": 2318, "event": "table_file_creation", "file_number": 2879, "file_size": 68708752, "table_properties": {"data_size": 68696875, "index_size": 10967, "filter_size": 0, "raw_key_size": 2822264, "raw_average_key_size": 23, "raw_value_size": 66957429, "raw_average_value_size": 548, "num_data_blocks": 322, "num_entries": 122096, "filter_policy_name": "rocksdb.BuiltinBloomFilter", "kDeletedKeys": "0", "kMergeOperands": "0"}}
2017/10/23-15:36:10.672770 7f361d3a6700 [default] [JOB 2318] Generated table #2880: 1494 keys, 69330876 bytes
2017/10/23-15:36:10.672816 7f361d3a6700 EVENT_LOG_v1 {"time_micros": 1508744170672788, "cf_name": "default", "job": 2318, "event": "table_file_creation", "file_number": 2880, "file_size": 69330876, "table_properties": {"data_size": 69327458, "index_size": 2511, "filter_size": 0, "raw_key_size": 29718, "raw_average_key_size": 19, "raw_value_size": 69303045, "raw_average_value_size": 46387, "num_data_blocks": 75, "num_entries": 1494, "filter_policy_name": "rocksdb.BuiltinBloomFilter", "kDeletedKeys": "0", "kMergeOperands": "0"}}
2017/10/23-15:36:10.734227 7f3617cfd700 [default] New memtable created with log file: #2882. Immutable memtables: 0.
2017/10/23-15:36:10.734316 7f361c3a4700 [JOB 2319] Syncing log #2877
2017/10/23-15:36:10.735231 7f361c3a4700 (Original Log Time 2017/10/23-15:36:10.734302) Calling FlushMemTableToOutputFile with column family [default], flush slots available 2, compaction slots allowed 1, compaction slots scheduled 0
2017/10/23-15:36:10.735240 7f361c3a4700 [default] [JOB 2319] Flushing memtable with next log file: 2882
2017/10/23-15:36:10.735263 7f361c3a4700 EVENT_LOG_v1 {"time_micros": 1508744170735252, "job": 2319, "event": "flush_started", "num_memtables": 1, "num_entries": 950, "num_deletes": 4, "memory_usage": 65792}
2017/10/23-15:36:10.735270 7f361c3a4700 [default] [JOB 2319] Level-0 flush table #2883: started
2017/10/23-15:36:10.737659 7f361c3a4700 EVENT_LOG_v1 {"time_micros": 1508744170737627, "cf_name": "default", "job": 2319, "event": "table_file_creation", "file_number": 2883, "file_size": 41456, "table_properties": {"data_size": 39192, "index_size": 85, "filter_size": 1221, "raw_key_size": 17228, "raw_average_key_size": 18, "raw_value_size": 26285, "raw_average_value_size": 28, "num_data_blocks": 3, "num_entries": 928, "filter_policy_name": "rocksdb.BuiltinBloomFilter", "kDeletedKeys": "4", "kMergeOperands": "0"}}
2017/10/23-15:36:10.737684 7f361c3a4700 [default] [JOB 2319] Level-0 flush table #2883: 41456 bytes OK
2017/10/23-15:36:10.738154 7f361c3a4700 [WARN] More existing levels in DB than needed. max_bytes_for_level_multiplier may not be guaranteed.
2017/10/23-15:36:10.738680 7f361c3a4700 [WARN] [default] Increasing compaction threads because we have 5 level-0 files 
2017/10/23-15:36:10.738715 7f361c3a4700 (Original Log Time 2017/10/23-15:36:10.738124) [default] Level-0 commit table #2883 started
2017/10/23-15:36:10.738721 7f361c3a4700 (Original Log Time 2017/10/23-15:36:10.738650) [default] Level-0 commit table #2883: memtable #1 done
2017/10/23-15:36:10.738725 7f361c3a4700 (Original Log Time 2017/10/23-15:36:10.738670) EVENT_LOG_v1 {"time_micros": 1508744170738661, "job": 2319, "event": "flush_finished", "lsm_state": [5, 0, 0, 0, 0, 0, 3], "immutable_memtables": 0}
2017/10/23-15:36:10.738730 7f361c3a4700 (Original Log Time 2017/10/23-15:36:10.738700) [default] Level summary: base level 6 max bytes base 536870913 files[5 0 0 0 0 0 3] max score 0.25
2017/10/23-15:36:10.738742 7f361c3a4700 [JOB 2319] Try to delete WAL files size 51877, prev total WAL file size 52945, number of live WAL files 2.
2017/10/23-15:36:10.856105 7f361d3a6700 [default] [JOB 2318] Generated table #2881: 201584 keys, 13722663 bytes
2017/10/23-15:36:10.856138 7f361d3a6700 EVENT_LOG_v1 {"time_micros": 1508744170856120, "cf_name": "default", "job": 2318, "event": "table_file_creation", "file_number": 2881, "file_size": 13722663, "table_properties": {"data_size": 13694739, "index_size": 27013, "filter_size": 0, "raw_key_size": 4438664, "raw_average_key_size": 22, "raw_value_size": 10467169, "raw_average_value_size": 51, "num_data_blocks": 831, "num_entries": 201584, "filter_policy_name": "rocksdb.BuiltinBloomFilter", "kDeletedKeys": "0", "kMergeOperands": "0"}}
2017/10/23-15:36:10.856791 7f361d3a6700 [default] [JOB 2318] Compacted 4@0 + 3@6 files to L6 => 151762291 bytes
2017/10/23-15:36:10.856834 7f361d3a6700 [WARN] More existing levels in DB than needed. max_bytes_for_level_multiplier may not be guaranteed.
2017/10/23-15:36:10.857403 7f361d3a6700 (Original Log Time 2017/10/23-15:36:10.857330) [default] compacted to: base level 6 max bytes base 536870913 files[1 0 0 0 0 0 3] max score 0.25, MB/sec: 171.5 rd, 171.5 wr, level 6, files in(4, 3) out(3) MB in(0.2, 144.5) out(144.7), read-write-amplify(1346.4) write-amplify(673.2) OK, records in: 325256, records dropped: 82
2017/10/23-15:36:10.857410 7f361d3a6700 (Original Log Time 2017/10/23-15:36:10.857364) EVENT_LOG_v1 {"time_micros": 1508744170857349, "job": 2318, "event": "compaction_finished", "compaction_time_micros": 885033, "output_level": 6, "num_output_files": 3, "total_output_size": 151762291, "num_input_records": 325256, "num_output_records": 325174, "num_subcompactions": 1, "num_single_delete_mismatches": 0, "num_single_delete_fallthrough": 0, "lsm_state": [1, 0, 0, 0, 0, 0, 3]}
2017/10/23-15:36:11.737866 7f3617cfd700 EVENT_LOG_v1 {"time_micros": 1508744171737857, "job": 0, "event": "table_file_deletion", "file_number": 2878}
2017/10/23-15:36:11.737977 7f3617cfd700 EVENT_LOG_v1 {"time_micros": 1508744171737973, "job": 0, "event": "table_file_deletion", "file_number": 2876}
2017/10/23-15:36:11.738049 7f3617cfd700 EVENT_LOG_v1 {"time_micros": 1508744171738046, "job": 0, "event": "table_file_deletion", "file_number": 2874}
2017/10/23-15:36:11.738113 7f3617cfd700 EVENT_LOG_v1 {"time_micros": 1508744171738110, "job": 0, "event": "table_file_deletion", "file_number": 2872}
2017/10/23-15:36:11.743136 7f3617cfd700 EVENT_LOG_v1 {"time_micros": 1508744171743132, "job": 0, "event": "table_file_deletion", "file_number": 2870}
2017/10/23-15:36:11.765721 7f3617cfd700 EVENT_LOG_v1 {"time_micros": 1508744171765717, "job": 0, "event": "table_file_deletion", "file_number": 2763}
2017/10/23-15:36:11.785616 7f3617cfd700 EVENT_LOG_v1 {"time_micros": 1508744171785612, "job": 0, "event": "table_file_deletion", "file_number": 2754}
2017/10/23-15:36:13.467837 7f3617cfd700 [default] New memtable created with log file: #2884. Immutable memtables: 0.
2017/10/23-15:36:13.467946 7f361cba5700 [JOB 2320] Syncing log #2882
2017/10/23-15:36:13.468592 7f361cba5700 (Original Log Time 2017/10/23-15:36:13.467930) Calling FlushMemTableToOutputFile with column family [default], flush slots available 2, compaction slots allowed 1, compaction slots scheduled 1
2017/10/23-15:36:13.468604 7f361cba5700 [default] [JOB 2320] Flushing memtable with next log file: 2884
2017/10/23-15:36:13.468631 7f361cba5700 EVENT_LOG_v1 {"time_micros": 1508744173468618, "job": 2320, "event": "flush_started", "num_memtables": 1, "num_entries": 531, "num_deletes": 114, "memory_usage": 65800}
2017/10/23-15:36:13.468638 7f361cba5700 [default] [JOB 2320] Level-0 flush table #2885: started
2017/10/23-15:36:13.470340 7f361cba5700 EVENT_LOG_v1 {"time_micros": 1508744173470308, "cf_name": "default", "job": 2320, "event": "table_file_creation", "file_number": 2885, "file_size": 12190, "table_properties": {"data_size": 10756, "index_size": 28, "filter_size": 453, "raw_key_size": 8966, "raw_average_key_size": 27, "raw_value_size": 4676, "raw_average_value_size": 14, "num_data_blocks": 1, "num_entries": 321, "filter_policy_name": "rocksdb.BuiltinBloomFilter", "kDeletedKeys": "114", "kMergeOperands": "0"}}
2017/10/23-15:36:13.470369 7f361cba5700 [default] [JOB 2320] Level-0 flush table #2885: 12190 bytes OK
2017/10/23-15:36:13.470806 7f361cba5700 [WARN] More existing levels in DB than needed. max_bytes_for_level_multiplier may not be guaranteed.
2017/10/23-15:36:13.471326 7f361cba5700 (Original Log Time 2017/10/23-15:36:13.470774) [default] Level-0 commit table #2885 started
2017/10/23-15:36:13.471332 7f361cba5700 (Original Log Time 2017/10/23-15:36:13.471269) [default] Level-0 commit table #2885: memtable #1 done
2017/10/23-15:36:13.471337 7f361cba5700 (Original Log Time 2017/10/23-15:36:13.471289) EVENT_LOG_v1 {"time_micros": 1508744173471278, "job": 2320, "event": "flush_finished", "lsm_state": [2, 0, 0, 0, 0, 0, 3], "immutable_memtables": 0}
2017/10/23-15:36:13.471342 7f361cba5700 (Original Log Time 2017/10/23-15:36:13.471309) [default] Level summary: base level 6 max bytes base 536870913 files[2 0 0 0 0 0 3] max score 0.50
2017/10/23-15:36:13.471354 7f361cba5700 [JOB 2320] Try to delete WAL files size 55392, prev total WAL file size 55475, number of live WAL files 2.
2017/10/23-15:36:14.196659 7f3617cfd700 [default] New memtable created with log file: #2886. Immutable memtables: 0.
2017/10/23-15:36:14.196759 7f361c3a4700 [JOB 2321] Syncing log #2884
2017/10/23-15:36:14.197686 7f361c3a4700 (Original Log Time 2017/10/23-15:36:14.196739) Calling FlushMemTableToOutputFile with column family [default], flush slots available 2, compaction slots allowed 1, compaction slots scheduled 1
2017/10/23-15:36:14.197695 7f361c3a4700 [default] [JOB 2321] Flushing memtable with next log file: 2886
2017/10/23-15:36:14.197739 7f361c3a4700 EVENT_LOG_v1 {"time_micros": 1508744174197708, "job": 2321, "event": "flush_started", "num_memtables": 1, "num_entries": 329, "num_deletes": 6, "memory_usage": 185056}
2017/10/23-15:36:14.197745 7f361c3a4700 [default] [JOB 2321] Level-0 flush table #2887: started
2017/10/23-15:36:14.200456 7f361c3a4700 EVENT_LOG_v1 {"time_micros": 1508744174200420, "cf_name": "default", "job": 2321, "event": "table_file_creation", "file_number": 2887, "file_size": 164563, "table_properties": {"data_size": 163101, "index_size": 52, "filter_size": 453, "raw_key_size": 7469, "raw_average_key_size": 24, "raw_value_size": 158401, "raw_average_value_size": 522, "num_data_blocks": 2, "num_entries": 303, "filter_policy_name": "rocksdb.BuiltinBloomFilter", "kDeletedKeys": "6", "kMergeOperands": "0"}}
2017/10/23-15:36:14.200483 7f361c3a4700 [default] [JOB 2321] Level-0 flush table #2887: 164563 bytes OK
2017/10/23-15:36:14.200966 7f361c3a4700 [WARN] More existing levels in DB than needed. max_bytes_for_level_multiplier may not be guaranteed.
2017/10/23-15:36:14.201466 7f361c3a4700 (Original Log Time 2017/10/23-15:36:14.200941) [default] Level-0 commit table #2887 started
2017/10/23-15:36:14.201472 7f361c3a4700 (Original Log Time 2017/10/23-15:36:14.201412) [default] Level-0 commit table #2887: memtable #1 done
2017/10/23-15:36:14.201477 7f361c3a4700 (Original Log Time 2017/10/23-15:36:14.201430) EVENT_LOG_v1 {"time_micros": 1508744174201420, "job": 2321, "event": "flush_finished", "lsm_state": [3, 0, 0, 0, 0, 0, 3], "immutable_memtables": 0}
2017/10/23-15:36:14.201482 7f361c3a4700 (Original Log Time 2017/10/23-15:36:14.201449) [default] Level summary: base level 6 max bytes base 536870913 files[3 0 0 0 0 0 3] max score 0.75
2017/10/23-15:36:14.201494 7f361c3a4700 [JOB 2321] Try to delete WAL files size 172392, prev total WAL file size 172775, number of live WAL files 2.
2017/10/23-15:36:14.662352 7f3620bad700 [default] [JOB 2322] Compacting 3@0 + 3@6 files to L6, score 0.00
2017/10/23-15:36:14.662374 7f3620bad700 [default] Compaction start summary: Base version 1557 Base level 0, inputs: [2887(160KB) 2885(11KB) 2883(40KB)], [2879(65MB) 2880(66MB) 2881(13MB)]
2017/10/23-15:36:14.662402 7f3620bad700 EVENT_LOG_v1 {"time_micros": 1508744174662384, "job": 2322, "event": "compaction_started", "files_L0": [2887, 2885, 2883], "files_L6": [2879, 2880, 2881], "score": 0, "input_data_size": 151980500}
2017/10/23-15:36:14.663789 7f36061ff700 [default] New memtable created with log file: #2888. Immutable memtables: 0.
2017/10/23-15:36:14.663877 7f361cba5700 [JOB 2323] Syncing log #2886
2017/10/23-15:36:14.664829 7f361cba5700 (Original Log Time 2017/10/23-15:36:14.663866) Calling FlushMemTableToOutputFile with column family [default], flush slots available 2, compaction slots allowed 1, compaction slots scheduled 0
2017/10/23-15:36:14.664840 7f361cba5700 [default] [JOB 2323] Flushing memtable with next log file: 2888
2017/10/23-15:36:14.664863 7f361cba5700 EVENT_LOG_v1 {"time_micros": 1508744174664852, "job": 2323, "event": "flush_started", "num_memtables": 1, "num_entries": 247, "num_deletes": 8, "memory_usage": 23784}
2017/10/23-15:36:14.664869 7f361cba5700 [default] [JOB 2323] Level-0 flush table #2890: started
2017/10/23-15:36:14.666314 7f361cba5700 EVENT_LOG_v1 {"time_micros": 1508744174666284, "cf_name": "default", "job": 2323, "event": "table_file_creation", "file_number": 2890, "file_size": 10744, "table_properties": {"data_size": 9438, "index_size": 28, "filter_size": 325, "raw_key_size": 9488, "raw_average_key_size": 41, "raw_value_size": 3210, "raw_average_value_size": 13, "num_data_blocks": 1, "num_entries": 231, "filter_policy_name": "rocksdb.BuiltinBloomFilter", "kDeletedKeys": "8", "kMergeOperands": "0"}}
2017/10/23-15:36:14.666343 7f361cba5700 [default] [JOB 2323] Level-0 flush table #2890: 10744 bytes OK
2017/10/23-15:36:14.666857 7f361cba5700 [WARN] More existing levels in DB than needed. max_bytes_for_level_multiplier may not be guaranteed.
2017/10/23-15:36:14.667410 7f361cba5700 (Original Log Time 2017/10/23-15:36:14.666829) [default] Level-0 commit table #2890 started
2017/10/23-15:36:14.667416 7f361cba5700 (Original Log Time 2017/10/23-15:36:14.667360) [default] Level-0 commit table #2890: memtable #1 done
2017/10/23-15:36:14.667420 7f361cba5700 (Original Log Time 2017/10/23-15:36:14.667378) EVENT_LOG_v1 {"time_micros": 1508744174667369, "job": 2323, "event": "flush_finished", "lsm_state": [4, 0, 0, 0, 0, 0, 3], "immutable_memtables": 0}
2017/10/23-15:36:14.667425 7f361cba5700 (Original Log Time 2017/10/23-15:36:14.667395) [default] Level summary: base level 6 max bytes base 536870913 files[4 0 0 0 0 0 3] max score 0.25
2017/10/23-15:36:14.667436 7f361cba5700 [JOB 2323] Try to delete WAL files size 18114, prev total WAL file size 18114, number of live WAL files 2.
2017/10/23-15:36:14.995104 7f3620bad700 [default] [JOB 2322] Generated table #2889: 122187 keys, 68716441 bytes
2017/10/23-15:36:14.995160 7f3620bad700 EVENT_LOG_v1 {"time_micros": 1508744174995130, "cf_name": "default", "job": 2322, "event": "table_file_creation", "file_number": 2889, "file_size": 68716441, "table_properties": {"data_size": 68704518, "index_size": 11013, "filter_size": 0, "raw_key_size": 2825564, "raw_average_key_size": 23, "raw_value_size": 66963178, "raw_average_value_size": 548, "num_data_blocks": 323, "num_entries": 122187, "filter_policy_name": "rocksdb.BuiltinBloomFilter", "kDeletedKeys": "0", "kMergeOperands": "0"}}
2017/10/23-15:36:15.325155 7f3620bad700 [default] [JOB 2322] Generated table #2891: 1494 keys, 69330876 bytes
2017/10/23-15:36:15.325195 7f3620bad700 EVENT_LOG_v1 {"time_micros": 1508744175325175, "cf_name": "default", "job": 2322, "event": "table_file_creation", "file_number": 2891, "file_size": 69330876, "table_properties": {"data_size": 69327458, "index_size": 2511, "filter_size": 0, "raw_key_size": 29718, "raw_average_key_size": 19, "raw_value_size": 69303045, "raw_average_value_size": 46387, "num_data_blocks": 75, "num_entries": 1494, "filter_policy_name": "rocksdb.BuiltinBloomFilter", "kDeletedKeys": "0", "kMergeOperands": "0"}}
2017/10/23-15:36:15.482887 7f3620bad700 [default] [JOB 2322] Generated table #2892: 202917 keys, 13924422 bytes
2017/10/23-15:36:15.482943 7f3620bad700 EVENT_LOG_v1 {"time_micros": 1508744175482923, "cf_name": "default", "job": 2322, "event": "table_file_creation", "file_number": 2892, "file_size": 13924422, "table_properties": {"data_size": 13896363, "index_size": 27148, "filter_size": 0, "raw_key_size": 4464732, "raw_average_key_size": 22, "raw_value_size": 10650156, "raw_average_value_size": 52, "num_data_blocks": 836, "num_entries": 202917, "filter_policy_name": "rocksdb.BuiltinBloomFilter", "kDeletedKeys": "0", "kMergeOperands": "0"}}
2017/10/23-15:36:15.483553 7f3620bad700 [default] [JOB 2322] Compacted 3@0 + 3@6 files to L6 => 151971739 bytes
2017/10/23-15:36:15.483600 7f3620bad700 [WARN] More existing levels in DB than needed. max_bytes_for_level_multiplier may not be guaranteed.
2017/10/23-15:36:15.484218 7f3620bad700 (Original Log Time 2017/10/23-15:36:15.484040) [default] compacted to: base level 6 max bytes base 536870913 files[1 0 0 0 0 0 3] max score 0.25, MB/sec: 185.1 rd, 185.1 wr, level 6, files in(3, 3) out(3) MB in(0.2, 144.7) out(144.9), read-write-amplify(1392.9) write-amplify(696.5) OK, records in: 326726, records dropped: 128
2017/10/23-15:36:15.484226 7f3620bad700 (Original Log Time 2017/10/23-15:36:15.484074) EVENT_LOG_v1 {"time_micros": 1508744175484058, "job": 2322, "event": "compaction_finished", "compaction_time_micros": 821107, "output_level": 6, "num_output_files": 3, "total_output_size": 151971739, "num_input_records": 326726, "num_output_records": 326598, "num_subcompactions": 1, "num_single_delete_mismatches": 0, "num_single_delete_fallthrough": 0, "lsm_state": [1, 0, 0, 0, 0, 0, 3]}
2017/10/23-15:36:15.484372 7f3620bad700 EVENT_LOG_v1 {"time_micros": 1508744175484366, "job": 2322, "event": "table_file_deletion", "file_number": 2887}
2017/10/23-15:36:15.484422 7f3620bad700 EVENT_LOG_v1 {"time_micros": 1508744175484419, "job": 2322, "event": "table_file_deletion", "file_number": 2885}
2017/10/23-15:36:15.484476 7f3620bad700 EVENT_LOG_v1 {"time_micros": 1508744175484473, "job": 2322, "event": "table_file_deletion", "file_number": 2883}
2017/10/23-15:36:15.488831 7f3620bad700 EVENT_LOG_v1 {"time_micros": 1508744175488827, "job": 2322, "event": "table_file_deletion", "file_number": 2881}
2017/10/23-15:36:15.510351 7f3620bad700 EVENT_LOG_v1 {"time_micros": 1508744175510347, "job": 2322, "event": "table_file_deletion", "file_number": 2880}
2017/10/23-15:36:15.529816 7f3620bad700 EVENT_LOG_v1 {"time_micros": 1508744175529812, "job": 2322, "event": "table_file_deletion", "file_number": 2879}
```

is the `JOB 2322` has any problem ?

**Comment by mm304321141** [comment]
version 5.3.3
@siying @IslamAbdelRahman @rockeet @lightmark
