### ISSUE TITLE
import rocksdb error:libgflags.so.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by xzcccc** [facebook/rocksdb#3968]
As I install rocksdb in my OS , however, when I use python to import rocksdb , an error happend.

```
[xzc@xzc gflags]$ python        
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 18:10:19) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import rocksdb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xzc/anaconda3/lib/python3.6/site-packages/rocksdb/__init__.py", line 1, in <module>
    from ._rocksdb import *
ImportError: libgflags.so.2: cannot open shared object file: No such file or directory
>>> 
```

And i find the file 'libgflags.so' in my file system, it inputs as follow:
```
[xzc@xzc gflags]$ sudo find / -name libgflags.so
/home/xzc/anaconda3/pkgs/gflags-2.2.1-hf484d3e_0/lib/libgflags.so
/home/xzc/anaconda3/lib/libgflags.so
/home/xzc/gflags/.libs/libgflags.so
/usr/local/lib/libgflags.so
```

There is no libgflags.so.2 found in my os.... I don't know what's wrong with it.
Should i cp the  libgflags.so into  libgflags.so.2?

OS :centos 7
python:3.6

Thanks

**Comment by zwang752** [comment]
Did you solve this problem?

**Comment by adamretter** [comment]
Rather than copy, you could attempt a symlink

**Comment by advance512** [comment]
If you're installing caffe via conda and running into this, try:
```
conda install python=2.7 caffe-gpu protobuf gflags
```
