### ISSUE TITLE
Iterator (readahead > 0) destruction pollutes the block cache

### ISSUE THREAD

**Issue by tulshiba** [facebook/rocksdb#4044]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev

Iterator with readahead > 0 drops all the partitioned bloom filter entries when destructed. This can cause subsequent get/read ops to reload the bloom filter entries adding to disk reads and latency. I see a comment in the code (partitioned bloom filter destructor) attesting to this behavior. This looks like a bug to me (RocksDB 5.9.2). We thought of using the workaround of setting the readahead to 0. But we can't use that for all of our use-cases (RocksDB on HDDs etc.).

Can someone confirm if my analysis is valid.?

```
#0  rocksdb::(anonymous namespace)::DeleteCachedFilterEntry (key=..., value=0x555555e18540) at ../../../rocksdb/table/block_based_table_reader.cc:2444
#1  0x00007ffff5e7c1ce in rocksdb::LRUHandle::Free (this=0x555555de4380) at ../../../rocksdb/cache/lru_cache.h:108
#2  0x00007ffff5e7b526 in rocksdb::LRUCacheShard::Erase (this=0x5555561ca440, key=..., hash=2435986937) at ../../../rocksdb/cache/lru_cache.cc:441
#3  0x00007ffff5e7ee44 in rocksdb::ShardedCache::Erase (this=0x555555e3ea10, key=...) at ../../../rocksdb/cache/sharded_cache.cc:73
#4  0x00007ffff6136d9a in rocksdb::PartitionedFilterBlockReader::~PartitionedFilterBlockReader (this=0x5555561e4b80) at ../../../rocksdb/table/partitioned_filter_block.cc:126
#5  0x00007ffff6136ec9 in rocksdb::PartitionedFilterBlockReader::~PartitionedFilterBlockReader (this=0x5555561e4b80) at ../../../rocksdb/table/partitioned_filter_block.cc:103
#6  0x00007ffff610815f in std::default_delete<rocksdb::FilterBlockReader>::operator() (this=0x555556228f20, __ptr=0x5555561e4b80)
    at /opt/cross/el7.3-x86_64/gcc-4.9.4/lib/gcc/x86_64-redhat-linux/4.9.4/../../../../x86_64-redhat-linux/include/c++/4.9.4/bits/unique_ptr.h:76
#7  0x00007ffff6107db3 in std::unique_ptr<rocksdb::FilterBlockReader, std::default_delete<rocksdb::FilterBlockReader> >::~unique_ptr (this=0x555556228f20)
    at /opt/cross/el7.3-x86_64/gcc-4.9.4/lib/gcc/x86_64-redhat-linux/4.9.4/../../../../x86_64-redhat-linux/include/c++/4.9.4/bits/unique_ptr.h:236
#8  0x00007ffff61056bb in rocksdb::BlockBasedTable::Rep::~Rep (this=0x555556228e00) at ../../../rocksdb/table/block_based_table_reader.h:400
#9  0x00007ffff60f5adf in rocksdb::BlockBasedTable::~BlockBasedTable (this=0x555555db9b10) at ../../../rocksdb/table/block_based_table_reader.cc:63
#10 0x00007ffff60f5b39 in rocksdb::BlockBasedTable::~BlockBasedTable (this=0x555555db9b10) at ../../../rocksdb/table/block_based_table_reader.cc:61
#11 0x00007ffff6012577 in rocksdb::(anonymous namespace)::DeleteTableReader (arg1=0x555555db9b10, arg2=0x0) at ../../../rocksdb/db/table_cache.cc:46
#12 0x00007ffff5e8a16f in rocksdb::Cleanable::DoCleanup (this=0x55555e541898) at ../../../rocksdb/include/rocksdb/cleanable.h:69
#13 0x00007ffff6127575 in rocksdb::Cleanable::~Cleanable (this=0x55555e541898) at ../../../rocksdb/table/iterator.cc:22
#14 0x00007ffff5fcc809 in rocksdb::InternalIterator::~InternalIterator (this=0x55555e541890) at ../../../rocksdb/table/internal_iterator.h:21
#15 0x00007ffff614d9f4 in rocksdb::(anonymous namespace)::TwoLevelIterator::~TwoLevelIterator (this=0x55555e541890) at ../../../rocksdb/table/two_level_iterator.cc:40
#16 0x00007ffff612ca66 in rocksdb::IteratorWrapper::DeleteIter (this=0x55555e5416f0, is_arena_mode=true) at ../../../rocksdb/table/iterator_wrapper.h:50
#17 0x00007ffff6129798 in rocksdb::MergingIterator::~MergingIterator (this=0x55555e541690) at ../../../rocksdb/table/merging_iterator.cc:76
#18 0x00007ffff5facb14 in rocksdb::DBIter::~DBIter (this=0x55555e541440) at ../../../rocksdb/db/db_iter.cc:154
#19 0x00007ffff5fab49e in rocksdb::ArenaWrappedDBIter::~ArenaWrappedDBIter (this=0x55555e541400) at ../../../rocksdb/db/db_iter.cc:1306
#20 0x00007ffff5fab4f9 in rocksdb::ArenaWrappedDBIter::~ArenaWrappedDBIter (this=0x55555e541400) at ../../../rocksdb/db/db_iter.cc:1306
```

If readahead > 0, RocksDB internally generates new table readers and so registers a cleanup function that drops these newly created table readers. So, when the iterator is destructed these table table readers and the corrosponding bloom filters (from the block cache) are dropped.

```
...
if (s.ok()) {
    if (options.table_filter &&
        !options.table_filter(*table_reader->GetTableProperties())) {
      result = NewEmptyInternalIterator(arena);
    } else {
      result = table_reader->NewIterator(options, arena, skip_filters);
    }
    if (create_new_table_reader) {
      assert(handle == nullptr);
      result->RegisterCleanup(&DeleteTableReader, table_reader, nullptr);
    } else if (handle != nullptr) {
      result->RegisterCleanup(&UnrefEntry, cache_, handle);
      handle = nullptr;  // prevent from releasing below
    }

    if (for_compaction) {
      table_reader->SetupForCompaction();
    }
    if (table_reader_ptr != nullptr) {
      *table_reader_ptr = table_reader;
    }
  }
...
```

```
...
PartitionedFilterBlockReader::~PartitionedFilterBlockReader() {
  // TODO(myabandeh): if instead of filter object we store only the blocks in
  // block cache, then we don't have to manually earse them from block cache
  // here.
  auto block_cache = table_->rep_->table_options.block_cache.get();
  if (UNLIKELY(block_cache == nullptr)) {
    return;
  }
  char cache_key[BlockBasedTable::kMaxCacheKeyPrefixSize + kMaxVarint64Length];
  BlockIter biter;
  BlockHandle handle;
  idx_on_fltr_blk_->NewIterator(&comparator_, &biter, true);
  biter.SeekToFirst();
  for (; biter.Valid(); biter.Next()) {
    auto input = biter.value();
    auto s = handle.DecodeFrom(&input);
    assert(s.ok());
    if (!s.ok()) {
      continue;
    }
    auto key = BlockBasedTable::GetCacheKey(table_->rep_->cache_key_prefix,
                                            table_->rep_->cache_key_prefix_size,
                                            handle, cache_key);
    block_cache->Erase(key);
  }
}
...
```

**Comment by tulshiba** [comment]
@maysamyabandeh - Any inputs on this? Thanks.

**Comment by tulshiba** [comment]
Any inputs on this?

**Comment by siying** [comment]
CC @sagar0

**Comment by maysamyabandeh** [comment]
The solution is not to create a new TableReader when readahead > 0. This will be addressed in https://github.com/facebook/rocksdb/pull/4052

**Comment by sagar0** [comment]
With #5246 new TableReaders are not created anymore on readahead > 0.
