### ISSUE TITLE
Bus error in BuildTable during initialization

### ISSUE THREAD

**Issue by ravikant86** [facebook/rocksdb#414]
See the below stack in core file.
Program terminated with signal 7, Bus error.
#0  0x00007fc9ecbb7d94 in pair<rocksdb::Histograms, char const (&) [37], void> (__x=<optimized out>, __y=..., this=0x7fc997ffe0f0) at /usr/local/include/c++/4.8.0/bits/stl_pair.h:145
#1  __static_initialization_and_destruction_0 (__priority=65535, __initialize_p=1) at ./include/rocksdb/statistics.h:219
#2  0x00007fc9ecbba8b5 in rocksdb::BuildTable (dbname=..., env=0x7fc9ecf40d20 <rocksdb::Env::Default()::default_env>, options=..., soptions=..., table_cache=0x7fc9804d2820, iter=0x7fc9448c2bf0, meta=0x7fc997ffe6c0, internal_comparator=..., newest_snapshot=0, 
    earliest_seqno_in_memtable=87602, compression=rocksdb::kZlibCompression) at db/builder.cc:72
#3  0x00007fc9ecb52066 in rocksdb::DBImpl::NewIterator (this=0x7fc9448c2bf0, options=..., column_family=<optimized out>) at db/db_impl.cc:3526
#4  0x00007fc9ecb535db in construct<rocksdb::log::Writer*, rocksdb::log::Writer* const&> (__p=0x7fc948c17b28, this=0x51) at /usr/local/include/c++/4.8.0/ext/new_allocator.h:120
#5  _S_construct<rocksdb::log::Writer*, rocksdb::log::Writer* const&> (__p=0x7fc948c17b28, __a=...) at /usr/local/include/c++/4.8.0/bits/alloc_traits.h:254
#6  construct<rocksdb::log::Writer*, rocksdb::log::Writer* const&> (__p=0x7fc948c17b28, __a=...) at /usr/local/include/c++/4.8.0/bits/alloc_traits.h:393
#7  push_back (__x=@0x7fc997ffe8a0: 0x3, this=0x51) at /usr/local/include/c++/4.8.0/bits/stl_vector.h:905
#8  push_back (item=<unknown type in /usr/local/lib/libhedvig.so, CU 0x213d7df, DIE 0x21db1e9>, this=0x19843) at ./util/autovector.h:230
#9  rocksdb::DBImpl::MakeRoomForWrite (this=0x7fc95a997980, cfd=0x7fc997ffeac0, force=false, superversions_to_free=0x7fc9ecbb3ce9, logs_to_free=0x7fc997ffe9d0) at db/db_impl.cc:4054
#10 0x00007fc9ecb53bff in operator-<rocksdb::DBImpl::LogFileNumberSize, rocksdb::DBImpl::LogFileNumberSize&, rocksdb::DBImpl::LogFileNumberSize*> (__y=..., __x=...) at /usr/local/include/c++/4.8.0/bits/stl_deque.h:337
#11 size (this=0x198) at /usr/local/include/c++/4.8.0/bits/stl_deque.h:1143
#12 rocksdb::DBImpl::FlushMemTableToOutputFile (this=0x0, cfd=0x7fc997ffe5e8, madeProgress=0x7fc943888a40, deletion_state=..., log_buffer=<optimized out>) at db/db_impl.cc:1551
#13 0x00007fc9ecb5d956 in rocksdb::DBImpl::DeleteObsoleteFiles (this=<optimized out>) at db/db_impl.cc:768
#14 0x00007fc9ecbabc7a in Fadvise (advice=4, len=26755841, offset=104515, fd=<optimized out>) at util/env_posix.cc:83
#15 rocksdb::(anonymous namespace)::PosixSequentialFile::InvalidateCache (this=0x7, offset=104515, length=26755841) at util/env_posix.cc:213
#16 0x000000300a4079d1 in start_thread () from /lib64/libpthread.so.0
#17 0x000000300a0e8b6d in clone () from /lib64/libc.so.6

**Comment by igorcanadi** [comment]
Closing due to inactivity. Feel free to reopen if you are still seeing this.
