### ISSUE TITLE
Install fails: Failed building wheel for python-rocksdb

### ISSUE THREAD

**Issue by prographo** [facebook/rocksdb#4186]
This is on Ubuntu 16.04 

### Expected behavior

make all
pip install python-rocksdb

(success)

### Actual behavior

(pyrocks_test) ubuntu@ip-172-31-21-95:~/ETH/rocksdb$ pip install python-rocksdb
Collecting python-rocksdb
  Using cached https://files.pythonhosted.org/packages/66/ec/5668df5564ef3bc6aa985ac5609ac716d4808b935f69e0e4720460a58b0e/python-rocksdb-0.6.9.tar.gz
Requirement already satisfied: setuptools>=25 in ./pyrocks_test/lib/python2.7/site-packages (from python-rocksdb) (40.0.0)
Building wheels for collected packages: python-rocksdb
  Running setup.py bdist_wheel for python-rocksdb ... error
  Complete output from command /home/ubuntu/ETH/rocksdb/pyrocks_test/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-efnoHF/python-rocksdb/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-9vpryj --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/rocksdb
  copying rocksdb/interfaces.py -> build/lib.linux-x86_64-2.7/rocksdb
  copying rocksdb/__init__.py -> build/lib.linux-x86_64-2.7/rocksdb
  copying rocksdb/errors.py -> build/lib.linux-x86_64-2.7/rocksdb
  copying rocksdb/merge_operators.py -> build/lib.linux-x86_64-2.7/rocksdb
  creating build/lib.linux-x86_64-2.7/rocksdb/tests
  copying rocksdb/tests/test_db.py -> build/lib.linux-x86_64-2.7/rocksdb/tests
  copying rocksdb/tests/__init__.py -> build/lib.linux-x86_64-2.7/rocksdb/tests
  copying rocksdb/tests/test_options.py -> build/lib.linux-x86_64-2.7/rocksdb/tests
  copying rocksdb/tests/test_memtable.py -> build/lib.linux-x86_64-2.7/rocksdb/tests
  running egg_info
  writing requirements to python_rocksdb.egg-info/requires.txt
  writing python_rocksdb.egg-info/PKG-INFO
  writing top-level names to python_rocksdb.egg-info/top_level.txt
  writing dependency_links to python_rocksdb.egg-info/dependency_links.txt
  reading manifest file 'python_rocksdb.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'python_rocksdb.egg-info/SOURCES.txt'
  copying rocksdb/_rocksdb.cpp -> build/lib.linux-x86_64-2.7/rocksdb
  copying rocksdb/_rocksdb.pyx -> build/lib.linux-x86_64-2.7/rocksdb
  copying rocksdb/backup.pxd -> build/lib.linux-x86_64-2.7/rocksdb
  copying rocksdb/cache.pxd -> build/lib.linux-x86_64-2.7/rocksdb
  copying rocksdb/comparator.pxd -> build/lib.linux-x86_64-2.7/rocksdb
  copying rocksdb/db.pxd -> build/lib.linux-x86_64-2.7/rocksdb
  copying rocksdb/env.pxd -> build/lib.linux-x86_64-2.7/rocksdb
  copying rocksdb/filter_policy.pxd -> build/lib.linux-x86_64-2.7/rocksdb
  copying rocksdb/iterator.pxd -> build/lib.linux-x86_64-2.7/rocksdb
  copying rocksdb/logger.pxd -> build/lib.linux-x86_64-2.7/rocksdb
  copying rocksdb/memtablerep.pxd -> build/lib.linux-x86_64-2.7/rocksdb
  copying rocksdb/merge_operator.pxd -> build/lib.linux-x86_64-2.7/rocksdb
  copying rocksdb/options.pxd -> build/lib.linux-x86_64-2.7/rocksdb
  copying rocksdb/slice_.pxd -> build/lib.linux-x86_64-2.7/rocksdb
  copying rocksdb/slice_transform.pxd -> build/lib.linux-x86_64-2.7/rocksdb
  copying rocksdb/snapshot.pxd -> build/lib.linux-x86_64-2.7/rocksdb
  copying rocksdb/status.pxd -> build/lib.linux-x86_64-2.7/rocksdb
  copying rocksdb/std_memory.pxd -> build/lib.linux-x86_64-2.7/rocksdb
  copying rocksdb/table_factory.pxd -> build/lib.linux-x86_64-2.7/rocksdb
  copying rocksdb/universal_compaction.pxd -> build/lib.linux-x86_64-2.7/rocksdb
  creating build/lib.linux-x86_64-2.7/rocksdb/cpp
  copying rocksdb/cpp/comparator_wrapper.hpp -> build/lib.linux-x86_64-2.7/rocksdb/cpp
  copying rocksdb/cpp/filter_policy_wrapper.hpp -> build/lib.linux-x86_64-2.7/rocksdb/cpp
  copying rocksdb/cpp/memtable_factories.hpp -> build/lib.linux-x86_64-2.7/rocksdb/cpp
  copying rocksdb/cpp/merge_operator_wrapper.hpp -> build/lib.linux-x86_64-2.7/rocksdb/cpp
  copying rocksdb/cpp/slice_transform_wrapper.hpp -> build/lib.linux-x86_64-2.7/rocksdb/cpp
  copying rocksdb/cpp/utils.hpp -> build/lib.linux-x86_64-2.7/rocksdb/cpp
  copying rocksdb/cpp/write_batch_iter_helper.hpp -> build/lib.linux-x86_64-2.7/rocksdb/cpp
  running build_ext
  skipping 'rocksdb/_rocksdb.cpp' Cython extension (up-to-date)
  building 'rocksdb._rocksdb' extension
  creating build/temp.linux-x86_64-2.7
  creating build/temp.linux-x86_64-2.7/rocksdb
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c rocksdb/_rocksdb.cpp -o build/temp.linux-x86_64-2.7/rocksdb/_rocksdb.o -std=c++11 -O3 -Wall -Wextra -Wconversion -fno-strict-aliasing -fno-rtti
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  rocksdb/_rocksdb.cpp:549:27: fatal error: rocksdb/slice.h: No such file or directory
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for python-rocksdb
  Running setup.py clean for python-rocksdb
Failed to build python-rocksdb
Installing collected packages: python-rocksdb
  Running setup.py install for python-rocksdb ... error
    Complete output from command /home/ubuntu/ETH/rocksdb/pyrocks_test/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-efnoHF/python-rocksdb/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-NHS8d4/install-record.txt --single-version-externally-managed --compile --install-headers /home/ubuntu/ETH/rocksdb/pyrocks_test/include/site/python2.7/python-rocksdb:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/rocksdb
    copying rocksdb/interfaces.py -> build/lib.linux-x86_64-2.7/rocksdb
    copying rocksdb/__init__.py -> build/lib.linux-x86_64-2.7/rocksdb
    copying rocksdb/errors.py -> build/lib.linux-x86_64-2.7/rocksdb
    copying rocksdb/merge_operators.py -> build/lib.linux-x86_64-2.7/rocksdb
    creating build/lib.linux-x86_64-2.7/rocksdb/tests
    copying rocksdb/tests/test_db.py -> build/lib.linux-x86_64-2.7/rocksdb/tests
    copying rocksdb/tests/__init__.py -> build/lib.linux-x86_64-2.7/rocksdb/tests
    copying rocksdb/tests/test_options.py -> build/lib.linux-x86_64-2.7/rocksdb/tests
    copying rocksdb/tests/test_memtable.py -> build/lib.linux-x86_64-2.7/rocksdb/tests
    running egg_info
    writing requirements to python_rocksdb.egg-info/requires.txt
    writing python_rocksdb.egg-info/PKG-INFO
    writing top-level names to python_rocksdb.egg-info/top_level.txt
    writing dependency_links to python_rocksdb.egg-info/dependency_links.txt
    reading manifest file 'python_rocksdb.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'python_rocksdb.egg-info/SOURCES.txt'
    copying rocksdb/_rocksdb.cpp -> build/lib.linux-x86_64-2.7/rocksdb
    copying rocksdb/_rocksdb.pyx -> build/lib.linux-x86_64-2.7/rocksdb
    copying rocksdb/backup.pxd -> build/lib.linux-x86_64-2.7/rocksdb
    copying rocksdb/cache.pxd -> build/lib.linux-x86_64-2.7/rocksdb
    copying rocksdb/comparator.pxd -> build/lib.linux-x86_64-2.7/rocksdb
    copying rocksdb/db.pxd -> build/lib.linux-x86_64-2.7/rocksdb
    copying rocksdb/env.pxd -> build/lib.linux-x86_64-2.7/rocksdb
    copying rocksdb/filter_policy.pxd -> build/lib.linux-x86_64-2.7/rocksdb
    copying rocksdb/iterator.pxd -> build/lib.linux-x86_64-2.7/rocksdb
    copying rocksdb/logger.pxd -> build/lib.linux-x86_64-2.7/rocksdb
    copying rocksdb/memtablerep.pxd -> build/lib.linux-x86_64-2.7/rocksdb
    copying rocksdb/merge_operator.pxd -> build/lib.linux-x86_64-2.7/rocksdb
    copying rocksdb/options.pxd -> build/lib.linux-x86_64-2.7/rocksdb
    copying rocksdb/slice_.pxd -> build/lib.linux-x86_64-2.7/rocksdb
    copying rocksdb/slice_transform.pxd -> build/lib.linux-x86_64-2.7/rocksdb
    copying rocksdb/snapshot.pxd -> build/lib.linux-x86_64-2.7/rocksdb
    copying rocksdb/status.pxd -> build/lib.linux-x86_64-2.7/rocksdb
    copying rocksdb/std_memory.pxd -> build/lib.linux-x86_64-2.7/rocksdb
    copying rocksdb/table_factory.pxd -> build/lib.linux-x86_64-2.7/rocksdb
    copying rocksdb/universal_compaction.pxd -> build/lib.linux-x86_64-2.7/rocksdb
    creating build/lib.linux-x86_64-2.7/rocksdb/cpp
    copying rocksdb/cpp/comparator_wrapper.hpp -> build/lib.linux-x86_64-2.7/rocksdb/cpp
    copying rocksdb/cpp/filter_policy_wrapper.hpp -> build/lib.linux-x86_64-2.7/rocksdb/cpp
    copying rocksdb/cpp/memtable_factories.hpp -> build/lib.linux-x86_64-2.7/rocksdb/cpp
    copying rocksdb/cpp/merge_operator_wrapper.hpp -> build/lib.linux-x86_64-2.7/rocksdb/cpp
    copying rocksdb/cpp/slice_transform_wrapper.hpp -> build/lib.linux-x86_64-2.7/rocksdb/cpp
    copying rocksdb/cpp/utils.hpp -> build/lib.linux-x86_64-2.7/rocksdb/cpp
    copying rocksdb/cpp/write_batch_iter_helper.hpp -> build/lib.linux-x86_64-2.7/rocksdb/cpp
    running build_ext
    skipping 'rocksdb/_rocksdb.cpp' Cython extension (up-to-date)
    building 'rocksdb._rocksdb' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/rocksdb
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c rocksdb/_rocksdb.cpp -o build/temp.linux-x86_64-2.7/rocksdb/_rocksdb.o -std=c++11 -O3 -Wall -Wextra -Wconversion -fno-strict-aliasing -fno-rtti
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    rocksdb/_rocksdb.cpp:549:27: fatal error: rocksdb/slice.h: No such file or directory
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/ubuntu/ETH/rocksdb/pyrocks_test/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-efnoHF/python-rocksdb/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-NHS8d4/install-record.txt --single-version-externally-managed --compile --install-headers /home/ubuntu/ETH/rocksdb/pyrocks_test/include/site/python2.7/python-rocksdb" failed with error code 1 in /tmp/pip-install-efnoHF/python-rocksdb/

**Comment by Macgill-john** [comment]
```
Defaulting to user installation because normal site-packages is not writeable
Collecting python-rocksdb
  Using cached python-rocksdb-0.7.0.tar.gz (219 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: setuptools>=25 in ./.local/lib/python3.10/site-packages (from python-rocksdb) (59.2.0)
Building wheels for collected packages: python-rocksdb
  Building wheel for python-rocksdb (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [7784 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.10
      creating build/lib.linux-x86_64-3.10/rocksdb
      copying rocksdb/merge_operators.py -> build/lib.linux-x86_64-3.10/rocksdb
      copying rocksdb/interfaces.py -> build/lib.linux-x86_64-3.10/rocksdb
      copying rocksdb/__init__.py -> build/lib.linux-x86_64-3.10/rocksdb
      copying rocksdb/errors.py -> build/lib.linux-x86_64-3.10/rocksdb
      creating build/lib.linux-x86_64-3.10/rocksdb/tests
      copying rocksdb/tests/test_options.py -> build/lib.linux-x86_64-3.10/rocksdb/tests
      copying rocksdb/tests/test_memtable.py -> build/lib.linux-x86_64-3.10/rocksdb/tests
      copying rocksdb/tests/test_db.py -> build/lib.linux-x86_64-3.10/rocksdb/tests
      copying rocksdb/tests/__init__.py -> build/lib.linux-x86_64-3.10/rocksdb/tests
      running egg_info
      writing python_rocksdb.egg-info/PKG-INFO
      writing dependency_links to python_rocksdb.egg-info/dependency_links.txt
      writing requirements to python_rocksdb.egg-info/requires.txt
      writing top-level names to python_rocksdb.egg-info/top_level.txt
      reading manifest file 'python_rocksdb.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      writing manifest file 'python_rocksdb.egg-info/SOURCES.txt'
      copying rocksdb/_rocksdb.cpp -> build/lib.linux-x86_64-3.10/rocksdb
      copying rocksdb/_rocksdb.pyx -> build/lib.linux-x86_64-3.10/rocksdb
      copying rocksdb/backup.pxd -> build/lib.linux-x86_64-3.10/rocksdb
      copying rocksdb/cache.pxd -> build/lib.linux-x86_64-3.10/rocksdb
      copying rocksdb/comparator.pxd -> build/lib.linux-x86_64-3.10/rocksdb
      copying rocksdb/db.pxd -> build/lib.linux-x86_64-3.10/rocksdb
      copying rocksdb/env.pxd -> build/lib.linux-x86_64-3.10/rocksdb
      copying rocksdb/filter_policy.pxd -> build/lib.linux-x86_64-3.10/rocksdb
      copying rocksdb/iterator.pxd -> build/lib.linux-x86_64-3.10/rocksdb
      copying rocksdb/logger.pxd -> build/lib.linux-x86_64-3.10/rocksdb
      copying rocksdb/memtablerep.pxd -> build/lib.linux-x86_64-3.10/rocksdb
      copying rocksdb/merge_operator.pxd -> build/lib.linux-x86_64-3.10/rocksdb
      copying rocksdb/options.pxd -> build/lib.linux-x86_64-3.10/rocksdb
      copying rocksdb/slice_.pxd -> build/lib.linux-x86_64-3.10/rocksdb
      copying rocksdb/slice_transform.pxd -> build/lib.linux-x86_64-3.10/rocksdb
      copying rocksdb/snapshot.pxd -> build/lib.linux-x86_64-3.10/rocksdb
      copying rocksdb/status.pxd -> build/lib.linux-x86_64-3.10/rocksdb
      copying rocksdb/std_memory.pxd -> build/lib.linux-x86_64-3.10/rocksdb
      copying rocksdb/table_factory.pxd -> build/lib.linux-x86_64-3.10/rocksdb
      copying rocksdb/universal_compaction.pxd -> build/lib.linux-x86_64-3.10/rocksdb
      creating build/lib.linux-x86_64-3.10/rocksdb/cpp
      copying rocksdb/cpp/comparator_wrapper.hpp -> build/lib.linux-x86_64-3.10/rocksdb/cpp
      copying rocksdb/cpp/filter_policy_wrapper.hpp -> build/lib.linux-x86_64-3.10/rocksdb/cpp
      copying rocksdb/cpp/memtable_factories.hpp -> build/lib.linux-x86_64-3.10/rocksdb/cpp
      copying rocksdb/cpp/merge_operator_wrapper.hpp -> build/lib.linux-x86_64-3.10/rocksdb/cpp
      copying rocksdb/cpp/slice_transform_wrapper.hpp -> build/lib.linux-x86_64-3.10/rocksdb/cpp
      copying rocksdb/cpp/utils.hpp -> build/lib.linux-x86_64-3.10/rocksdb/cpp
      copying rocksdb/cpp/write_batch_iter_helper.hpp -> build/lib.linux-x86_64-3.10/rocksdb/cpp
      running build_ext
      Compiling rocksdb/_rocksdb.pyx because it changed.
      [1/1] Cythonizing rocksdb/_rocksdb.pyx
      /home/john/.local/lib/python3.10/site-packages/Cython/Compiler/Main.py:346: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /tmp/pip-install-8mjqyv8_/python-rocksdb_ac1441e837644bcc9040526999e72983/rocksdb/_rocksdb.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      from cpython.bytes cimport PyBytes_Size
      from cpython.bytes cimport PyBytes_FromString
      from cpython.bytes cimport PyBytes_FromStringAndSize
      from cpython.unicode cimport PyUnicode_Decode
      
      from std_memory cimport shared_ptr
      ^
      ------------------------------------------------------------
      
      rocksdb/_rocksdb.pyx:15:0: 'std_memory.pxd' not found
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      from cpython.bytes cimport PyBytes_Size
      from cpython.bytes cimport PyBytes_FromString
      from cpython.bytes cimport PyBytes_FromStringAndSize
      from cpython.unicode cimport PyUnicode_Decode
      
      from std_memory cimport shared_ptr
      ^
      ------------------------------------------------------------
    .
    .
    .
    .
    .
    
    rocksdb/_rocksdb.pyx:2413:44: Converting to Python object not allowed without gil
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-8mjqyv8_/python-rocksdb_ac1441e837644bcc9040526999e72983/setup.py", line 21, in <module>
          setup(
        File "/home/john/.local/lib/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3.10/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/usr/lib/python3.10/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/home/john/.local/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 325, in run
          self.run_command("build")
        File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/lib/python3.10/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/home/john/.local/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 79, in run
          _build_ext.run(self)
        File "/usr/lib/python3.10/distutils/command/build_ext.py", line 340, in run
          self.build_extensions()
        File "/usr/lib/python3.10/distutils/command/build_ext.py", line 449, in build_extensions
          self._build_extensions_serial()
        File "/usr/lib/python3.10/distutils/command/build_ext.py", line 474, in _build_extensions_serial
          self.build_extension(ext)
        File "/home/john/.local/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
          _build_ext.build_extension(self, ext)
        File "/home/john/.local/lib/python3.10/site-packages/Cython/Distutils/build_ext.py", line 122, in build_extension
          new_ext = cythonize(
        File "/home/john/.local/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1117, in cythonize
          cythonize_one(*args)
        File "/home/john/.local/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1284, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: rocksdb/_rocksdb.pyx
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for python-rocksdb
  Running setup.py clean for python-rocksdb
Failed to build python-rocksdb
ERROR: Could not build wheels for python-rocksdb, which is required to install pyproject.toml-based projects

```
I am trying to install rocksdb using `pip install python-rocksdb` the latest one(0.7.0). I am getting the above error. Anyone know how to solve this ?

os- Ubuntu 22.04
python-3.10
pip - 24.0

**Comment by adamretter** [comment]
I haven't been involved in the Python API, but at a guess could it be a Python 2 vs 3 compatibility issue?
