### ISSUE TITLE
Advisor is unable to parse Percentiles

### ISSUE THREAD

**Issue by jsdt** [facebook/rocksdb#4269]
### Expected behavior
Advisor should be able to parse a log file.
### Actual behavior
Parsing fails with the following stack trace:
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jeffdt/gh/rocksdb/tools/advisor/advisor/rule_parser_example.py", line 89, in <module>
    main(args)
  File "/home/jeffdt/gh/rocksdb/tools/advisor/advisor/rule_parser_example.py", line 42, in main
    data_sources, db_options.get_column_families()
  File "/home/jeffdt/gh/rocksdb/tools/advisor/advisor/rule_parser.py", line 497, in get_triggered_rules
    self.trigger_conditions(data_sources)
  File "/home/jeffdt/gh/rocksdb/tools/advisor/advisor/rule_parser.py", line 514, in trigger_conditions
    source.check_and_trigger_conditions(cond_subset)
  File "/home/jeffdt/gh/rocksdb/tools/advisor/advisor/db_timeseries_parser.py", line 122, in check_and_trigger_conditions
    self.fetch_timeseries(reqd_keys)
  File "/home/jeffdt/gh/rocksdb/tools/advisor/advisor/db_stats_fetcher.py", line 112, in fetch_timeseries
    self.add_to_timeseries(new_log, reqd_stats)
  File "/home/jeffdt/gh/rocksdb/tools/advisor/advisor/db_stats_fetcher.py", line 87, in add_to_timeseries
    stats_on_line = self.parse_log_line_for_stats(line)
  File "/home/jeffdt/gh/rocksdb/tools/advisor/advisor/db_stats_fetcher.py", line 39, in parse_log_line_for_stats
    stat_dict[stat_name] = float(metric)
ValueError: could not convert string to float: 'Percentiles'
```
The log line it is failing to parse is:
```
rocksdb.db.get.micros statistics Percentiles :=> 50 : 0.000000 95 : 0.000000 99 : 0.000000 100 : 0.000000
```
### Steps to reproduce the behavior
Using rocks version 5.14.2 and the advisor from 4ea56b1bd00b5f8751e5e9733d01ceb33ebd09e3:
```
python3 -m advisor.rule_parser_example --rules_spec=advisor/rules.ini --rocksdb_options=$HOME/testing/rocks/2/OPTIONS-1195193 --log_files_path_prefix=$HOME/testing/rocks/2/LOG --stats_dump_period_sec=60
```
I attached the a zip with the log file and options file.
[input.zip](https://github.com/facebook/rocksdb/files/2284031/input.zip)

**Comment by anand1976** [comment]
I'm not very familiar with the advisor. Cc @maysamyabandeh

**Comment by jsdt** [comment]
It looks like advisor depends on a formatting change that isn't in the latest release. I wrote a quick fix for it: https://github.com/facebook/rocksdb/compare/master...jsdt:jsdt/advisor

**Comment by maysamyabandeh** [comment]
Thanks @jsdt for the report. Yeah the formatting is changed in https://github.com/facebook/rocksdb/commit/508a09fd62bf058a2b6bd9ea9bcd8e66e5b240cc
The patch of yours seems to properly handle the difference in formatting. I let the issue to be open for a while so others also could find your patch if faced the same issue.

**Comment by jsdt** [comment]
Would you like a PR with this fix (and tests)?

**Comment by maysamyabandeh** [comment]
The advisor should be consistent with master status and it is today. At this stage we better avoid making it complicated to be compatible with previous releases too.
