### ISSUE TITLE
can't load IA 32-bit .so on a ARM-bit platform

### ISSUE THREAD

**Issue by jing5877** [facebook/rocksdb#4276]
### Expected behavior
rocksdb init ok.

### Actual behavior
Some mistake appeared when init rocksdb.

### Steps to reproduce the behavior
Init rocksdb on  raspberrypi 3.
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: /tmp/librocksdbjni6098687721602980727.so: /tmp/librocksdbjni6098687721602980727.so: cannot open shared object file: No such file or directory (Possible cause: can't load IA 32-bit .so on a ARM-bit platform)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:78)
	at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:56)
	at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:64)
	at org.rocksdb.RocksDB.<clinit>(RocksDB.java:35)
	at org.rocksdb.Options.<clinit>(Options.java:25)
	at com.feeyo.newdb.pd.PdStore.<init>(PdStore.java:47)
	at com.feeyo.newdb.pd.PdStore.<clinit>(PdStore.java:22)
	at com.feeyo.raft.test.PdStateMachine.<init>(PdStateMachine.java:18)
	at com.feeyo.raft.test.RaftTest.main(RaftTest.java:51)
```

**Comment by adamretter** [comment]
So the answer is in the error message.

At the moment we don't provide support and builds for the ARM processors. That is not to say that we couldn't, but we don't currently. Feel free to send a PR to enable it...
