### ISSUE TITLE
Asan: container-overflow in HistogramBucketMapper constructor

### ISSUE THREAD

**Issue by pgoodman** [facebook/rocksdb#4319]
So this is probably a false positive from Asan, but it was easy enough to fix with a minor refactor.

### Expected behavior
No Asan report.

### Actual behavior
The following:
```=================================================================
==18637==ERROR: AddressSanitizer: container-overflow on address 0x602000000a38 at pc 0x00010ced748d bp 0x7ffee71c2a50 sp 0x7ffee71c2a48
READ of size 8 at 0x602000000a38 thread T0

    #0 0x10ced748c in rocksdb::HistogramBucketMapper::HistogramBucketMapper() histogram.cc:31
    #1 0x10ced85e4 in rocksdb::HistogramBucketMapper::HistogramBucketMapper() histogram.cc:26
    #2 0x10cf0a853 in __cxx_global_var_init.183 histogram.cc:65
    #3 0x10cf0a89e in _GLOBAL__sub_I_histogram.cc histogram.cc
    #4 0x11de24ac5 in ImageLoaderMachO::doModInitFunctions(ImageLoader::LinkContext const&) (dyld:x86_64+0x16ac5)
    #5 0x11de24cf5 in ImageLoaderMachO::doInitialization(ImageLoader::LinkContext const&) (dyld:x86_64+0x16cf5)
    #6 0x11de20217 in ImageLoader::recursiveInitialization(ImageLoader::LinkContext const&, unsigned int, char const*, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) (dyld:x86_64+0x12217)
    #7 0x11de1f34d in ImageLoader::processInitializers(ImageLoader::LinkContext const&, unsigned int, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) (dyld:x86_64+0x1134d)
    #8 0x11de1f3e1 in ImageLoader::runInitializers(ImageLoader::LinkContext const&, ImageLoader::InitializerTimingList&) (dyld:x86_64+0x113e1)
    #9 0x11de10566 in dyld::initializeMainExecutable() (dyld:x86_64+0x2566)
    #10 0x11de15238 in dyld::_main(macho_header const*, unsigned long, int, char const**, char const**, char const**, unsigned long*) (dyld:x86_64+0x7238)
    #11 0x11de0f3d3 in dyldbootstrap::start(macho_header const*, int, char const**, long, macho_header const*, unsigned long*) (dyld:x86_64+0x13d3)
    #12 0x11de0f1d1 in _dyld_start (dyld:x86_64+0x11d1)

0x602000000a38 is located 8 bytes inside of 16-byte region [0x602000000a30,0x602000000a40)
allocated by thread T0 here:
    #0 0x1156d0b32 in wrap__Znwm (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x62b32)
    #1 0x10c277179 in std::__1::vector<unsigned long long, std::__1::allocator<unsigned long long> >::allocate(unsigned long) new:226
    #2 0x10cee1027 in std::__1::enable_if<(__is_forward_iterator<unsigned long long const*>::value) && (is_constructible<unsigned long long, std::__1::iterator_traits<unsigned long long const*>::reference>::value), void>::type std::__1::vector<unsigned long long, std::__1::allocator<unsigned long long> >::assign<unsigned long long const*>(unsigned long long const*, unsigned long long const*) vector:1403
    #3 0x10ced6b61 in rocksdb::HistogramBucketMapper::HistogramBucketMapper() vector:562
    #4 0x10ced85e4 in rocksdb::HistogramBucketMapper::HistogramBucketMapper() histogram.cc:26
    #5 0x10cf0a853 in __cxx_global_var_init.183 histogram.cc:65
    #6 0x10cf0a89e in _GLOBAL__sub_I_histogram.cc histogram.cc
    #7 0x11de24ac5 in ImageLoaderMachO::doModInitFunctions(ImageLoader::LinkContext const&) (dyld:x86_64+0x16ac5)
    #8 0x11de24cf5 in ImageLoaderMachO::doInitialization(ImageLoader::LinkContext const&) (dyld:x86_64+0x16cf5)
    #9 0x11de20217 in ImageLoader::recursiveInitialization(ImageLoader::LinkContext const&, unsigned int, char const*, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) (dyld:x86_64+0x12217)
    #10 0x11de1f34d in ImageLoader::processInitializers(ImageLoader::LinkContext const&, unsigned int, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) (dyld:x86_64+0x1134d)
    #11 0x11de1f3e1 in ImageLoader::runInitializers(ImageLoader::LinkContext const&, ImageLoader::InitializerTimingList&) (dyld:x86_64+0x113e1)
    #12 0x11de10566 in dyld::initializeMainExecutable() (dyld:x86_64+0x2566)
    #13 0x11de15238 in dyld::_main(macho_header const*, unsigned long, int, char const**, char const**, char const**, unsigned long*) (dyld:x86_64+0x7238)
    #14 0x11de0f3d3 in dyldbootstrap::start(macho_header const*, int, char const**, long, macho_header const*, unsigned long*) (dyld:x86_64+0x13d3)
    #15 0x11de0f1d1 in _dyld_start (dyld:x86_64+0x11d1)

HINT: if you don't care about these errors you may set ASAN_OPTIONS=detect_container_overflow=0.
If you suspect a false positive see also: https://github.com/google/sanitizers/wiki/AddressSanitizerContainerOverflow.
SUMMARY: AddressSanitizer: container-overflow histogram.cc:31 in rocksdb::HistogramBucketMapper::HistogramBucketMapper()
Shadow bytes around the buggy address:
  0x1c04000000f0: fa fa 00 00 fa fa 00 00 fa fa 00 00 fa fa 00 00
  0x1c0400000100: fa fa 00 00 fa fa 00 00 fa fa 00 00 fa fa 00 00
  0x1c0400000110: fa fa 00 00 fa fa fd fd fa fa fd fd fa fa fd fd
  0x1c0400000120: fa fa fd fd fa fa fd fd fa fa fd fd fa fa fd fd
  0x1c0400000130: fa fa fd fd fa fa fd fd fa fa fd fd fa fa fd fd
=>0x1c0400000140: fa fa fd fd fa fa fc[fc]fa fa fa fa fa fa fa fa
  0x1c0400000150: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c0400000160: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c0400000170: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c0400000180: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c0400000190: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==18637==ABORTING
```
### How I fixed it

Old code:

```c++
  bucketValues_ = {1, 2};
```

New code:
```c++
  bucketValues_.resize(2);
  bucketValues_[0] = 1;
  bucketValues_[1] = 2;
```

**Comment by ajkr** [comment]
Hm interesting, we also build with ASAN but haven't seen this issue. Is there any chance the false positive described here (https://github.com/google/sanitizers/wiki/AddressSanitizerContainerOverflow) applies to you?

**Comment by pgoodman** [comment]
Indeed, definitely covered by that false positive.

**Comment by ajkr** [comment]
Great, thanks for getting back to us.
