### ISSUE TITLE
SST file lock

### ISSUE THREAD

**Issue by kamdibus** [facebook/rocksdb#4421]
### Expected behaviour
SST file can be deleted after RocksDb instance is closed on Windows.
### Actual behaviour
SST file remains locked after closing RocksDb instance on Windows. This problem happens after dropColumnFamily operation.
The file can be deleted after the jvm is shutdown.
### Environment
Windows 7
RocksDb 5.13.1, 5.14.2
### Steps to reproduce the behavior
```
RocksDb db = openRocksDb(...) // create RocksDb instance

ColumnFamilyHandle cfHandle = db.createColumnFamily(new ColumnFamilyDescriptor("testcf".getBytes(), cfOptions()));

write(db, cfHandle); // write some data to db

db.close();

db = openRocksDb(...); // reopen RocksDb to trigger creation of SST file

ColumnFamilyHandle dropCf = ...; // get testCf handle

db.dropColumnFamily(dropCf); // drop testcf after reopen
dropCf.close();
db.close();

FileUtils.forceDelete(rocksDbDir.toFile()); // throws java.io.Exception: Unable to delete file: ***.sst on Windows.
```

**Comment by anniefu** [comment]
I've seen the same issue on Windows using the C# - https://github.com/warrenfalk/rocksdb-sharp API

**Environment**
Windows 10 Pro, version 1803
RocksDb 5.14.2

**Repro**
```
        public void Test()
        {
            string temp = Path.GetTempPath();
            var testdb = Path.Combine(temp, "functional_test");
            string path = Environment.ExpandEnvironmentVariables(testdb);

            var columName = "column";
            var columnFamilies = new ColumnFamilies();
            columnFamilies.Add(columName, new ColumnFamilyOptions());

            var dbOptions = new DbOptions()
                .SetCreateIfMissing(true)
                .SetCreateMissingColumnFamilies(true);

            using (var db = RocksDb.Open(dbOptions, path, columnFamilies))
            {
                var cfh = db.GetColumnFamily(columName);
                db.Put("hello", "world", cfh);
            }

            using (var db = RocksDb.Open(dbOptions, path, columnFamilies))
            {
                db.DropColumnFamily(columName);
            }

            Directory.Delete(path, recursive: true);
        }
```

**Result**
```
[10/26/2018 5:35:22 PM Informational] [xUnit.net 00:00:00.9710181]       System.IO.IOException : The directory is not empty
[10/26/2018 5:35:22 PM Informational] [xUnit.net 00:00:00.9718720]       Stack Trace:
[10/26/2018 5:35:22 PM Informational] [xUnit.net 00:00:00.9727290]            at System.IO.Win32FileSystem.RemoveDirectoryHelper(String fullPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
[10/26/2018 5:35:22 PM Informational] [xUnit.net 00:00:00.9728359]            at System.IO.Win32FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
[10/26/2018 5:35:22 PM Informational] [xUnit.net 00:00:00.9728698]            at System.IO.Directory.Delete(String path, Boolean recursive)
[10/26/2018 5:35:22 PM Informational] [xUnit.net 00:00:00.9728995]         D:\RocksDbSharp\tests\RocksDbSharpTest\FunctionalTests.cs(40,0): at RocksDbSharpTest.FunctionalTests.Test()
```

**Comment by ajkr** [comment]
Let me close this since I think it's the same issue as #4409, for which I'm finding an owner.

**Comment by adamretter** [comment]
I agree it is likely the same issue as #4409
