### ISSUE TITLE
library loading error with rocksdb5.14.2

### ISSUE THREAD

**Issue by lemonguge** [facebook/rocksdb#4468]
`RocksDB.loadLibrary()` throw exception
```
Caused by: java.lang.UnsatisfiedLinkError: /home/admin/iotx-lora-server/.default/temp/librocksdbjni6992931247226937799.so: /home/admin/iotx-lora-server/.default/temp/librocksdbjni6992931247226937799.so: ELF file OS ABI invalid
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1971)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1854)
	at java.lang.Runtime.load0(Runtime.java:821)
	at java.lang.System.load(System.java:1107)
	at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:78)
	at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:56)
	at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:64)
	at org.rocksdb.RocksDB.<clinit>(RocksDB.java:35)
```
### Expected behavior
I can start normally on my MAC computer.
### Actual behavior
But it can't be started on my Linux server(Red Hat Enterprise Linux Server release 5.7).

**Comment by adamretter** [comment]
We build the releases on CentOS 6. We used to build on CentOS 5, but it became to difficult to support due to its age. You will need to build your own release for CentOS 5.

**Comment by lemonguge** [comment]
how to build and replace it

**Comment by adamretter** [comment]
@lemonguge - follow INSTALL.md to make sure you have all the pre-requisites on your CentOS 5 machine and then run `make rocksdbjavastatic`

**Comment by bu1bu2** [comment]
$cat /etc/issue
Enterprise Linux Server release 5.7 (CatFeces)  
-----------


          <dependency>
                <groupId>org.rocksdb</groupId>
                <artifactId>rocksdbjni</artifactId>
                <version>5.5.1</version>
            </dependency>
        </dependencies>

this version is available
