### ISSUE TITLE
UnsatisfiedLinkError for Rocksdb  java

### ISSUE THREAD

**Issue by liukun4515** [facebook/rocksdb#5064]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
Use java API like the example:
[example](https://github.com/facebook/rocksdb/wiki/RocksJava-Basics#opening-a-database)

My code
```
import org.rocksdb.Options;
import org.rocksdb.RocksDB;
import org.rocksdb.RocksDBException;

public class OpenDB {

  
  public static void main(String[] args) {
    // a static method that loads the RocksDB C++ library.
    RocksDB.loadLibrary();
    // the Options class contains a set of configurable DB options
    // that determines the behaviour of the database.
    try (final Options options = new Options().setCreateIfMissing(true)) {

      // a factory method that returns a RocksDB instance
      try (final RocksDB db = RocksDB.open(options, "path/to/db")) {

        // do something
      }
    } catch (RocksDBException e) {
      // do some error handling
    }
  }
}
```
### Actual behavior
 Some error when  i run the code

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: /private/var/folders/k0/c6q5hth54xl5yq670kccwvxh0000gn/T/librocksdbjni4601466708866429973.jnilib: dlopen(/private/var/folders/k0/c6q5hth54xl5yq670kccwvxh0000gn/T/librocksdbjni4601466708866429973.jnilib, 1): Symbol not found: __ZdlPvSt11align_val_t
  Referenced from: /private/var/folders/k0/c6q5hth54xl5yq670kccwvxh0000gn/T/librocksdbjni4601466708866429973.jnilib
  Expected in: /usr/lib/libc++.1.dylib
 in /private/var/folders/k0/c6q5hth54xl5yq670kccwvxh0000gn/T/librocksdbjni4601466708866429973.jnilib
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:78)
	at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:56)
	at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:64)
	at org.rocksdb.RocksDB.<clinit>(RocksDB.java:35)
	at edu.tsinghua.k1.rocksdb.example.OpenDB.main(OpenDB.java:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

### Steps to reproduce the behavior

My os is macos 10.10.5
JDK is 8

**Comment by totalslacker** [comment]
Same here with mac os 10.12.6 and idk 1.8.0_101.

**Comment by adamretter** [comment]
I am afraid that your libc library, which is shipped with your version of MacOS is too old.

You need to either:

1. build your own binaries from source (which will then use your version of libc).
2. if you wish to use the shipped binaries, update to a newer version of Mac OS. I am not sure of the minimal version exactly, but the binaries were built using 10.14.3 (Mojave)
