### ISSUE TITLE
org.rocksdb.RocksDBException: unknown WriteBatch tag 

### ISSUE THREAD

**Issue by liukun4515** [facebook/rocksdb#5068]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev

I use the rocksdbjava by：

```
<dependency>
      <groupId>org.rocksdb</groupId>
      <artifactId>rocksdbjni</artifactId>
      <version>5.17.2</version>
    </dependency>
```
Call the `write(new WriteOptions(), WriteBatch);` concurrently in multithreads.

### Expected behavior

Non-error in writing data

### Actual behavior

Java exception stack trace.

I wrapped the RocksDB in my project.
````
edu.tsinghua.k1.api.TimeSeriesDBException: org.rocksdb.RocksDBException: unknown WriteBatch tag
	at edu.tsinghua.k1.rocksdb.RocksDBTimeSeriesDB.write(RocksDBTimeSeriesDB.java:44) ~[timeseries-leveldb-2.0-SNAPSHOT.jar:na]
	at cn.edu.tsinghua.iotdb.benchmark.db.leveldb.TsLevelDB.insertOneBatch(TsLevelDB.java:114) ~[iotdb-benchmark-0.0.1.jar:na]
	at cn.edu.tsinghua.iotdb.benchmark.db.ClientThread.run(ClientThread.java:132) [iotdb-benchmark-0.0.1.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_171]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]
Caused by: org.rocksdb.RocksDBException: unknown WriteBatch tag
	at org.rocksdb.RocksDB.write0(Native Method) ~[rocksdbjni-5.17.2.jar:na]
	at org.rocksdb.RocksDB.write(RocksDB.java:602) ~[rocksdbjni-5.17.2.jar:na]
	at edu.tsinghua.k1.rocksdb.RocksDBTimeSeriesDB.write(RocksDBTimeSeriesDB.java:41) ~[timeseries-leveldb-2.0-SNAPSHOT.jar:na]
	... 7 common frames omitted
````

### Steps to reproduce the behavior

My os is Ubuntu 16.04.4 LTS

Java version ：
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)

**Comment by adamretter** [comment]
I just want to be certain of something. Are you sharing `WriteBatch` between threads? If so that won't work without you adding appropriate synchronisation, as `WriteBatch` is not thread-safe.

**Comment by liukun4515** [comment]
> If so that won't work without you adding appropriate synchronisation

I don't share `WriteBatch` between threads, but diff threads use the same `RocksDB` instance.

I forget to release the c++ object by [memory management](https://github.com/facebook/rocksdb/wiki/RocksJava-Basics#memory-management).
After I released the c++ object, there is no error.

But I'm confused about the exception `unknown WriteBatch tag`

**Comment by liukun4515** [comment]
Before i know the `memory management`, there is no error using one thread writing data.
@adamretter

**Comment by adamretter** [comment]
@liukun4515 Okay so it sounds like your problem is solved. The error `unknown WriteBatch tag` is coming internally from the RocksDB C++ code.
