### ISSUE TITLE
java.lang.UnsatisfiedLinkError: C:\Users\admin\AppData\Local\Temp\librocksdbjni5734698881557363843.dll

### ISSUE THREAD

**Issue by BEWINDOWEB** [facebook/rocksdb#5177]
### Expected behavior and Actual behavior
* windows 10 / x64
* jdk8
* rocksdb 5.17.2
caused by :
```
private final DBOptions DB_OPTIONS = new DBOptions();
```
and throws exception imformation:
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\admin\AppData\Local\Temp\librocksdbjni5734698881557363843.dll: refused to access。
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:78)
	at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:56)
	at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:64)
	at org.rocksdb.RocksDB.<clinit>(RocksDB.java:35)
	at org.rocksdb.DBOptions.<clinit>(DBOptions.java:21)
	at org.jmqtt.store.rocksdb.db.RDB.<init>(RDB.java:19)
	at org.jmqtt.store.rocksdb.RDBMqttStore.<init>(RDBMqttStore.java:15)
	at org.jmqtt.broker.BrokerController.<init>(BrokerController.java:102)
	at org.jmqtt.broker.BrokerStartup.start(BrokerStartup.java:63)
	at org.jmqtt.broker.BrokerStartup.main(BrokerStartup.java:25)
```
there is no librocksdbjnixxx.dll in temp dir, but it does exist in jar:
![image](https://user-images.githubusercontent.com/6178098/55937330-49beae00-5c6b-11e9-9624-321b6254e827.png)

### i've tried but doesn't work:
* uninstall vs runtime 2017, reinstall vs rumtime 2015 as rocksdb wiki tolds.

### Steps to reproduce the behavior
run open source project https://github.com/Cicizz/jmqtt

**Comment by adamretter** [comment]
If you follow the code in `NativeLibraryLoader#loadLibraryFromJarToTemp(String)`, you should see that the Jar file is unpacked to the temp directory when it is first run.

**Comment by BEWINDOWEB** [comment]
> If you follow the code in `NativeLibraryLoader#loadLibraryFromJarToTemp(String)`, you should see that the native dll file is unpacked to the temp directory when it is first run.

yes, i debug it and find the file, but after execute:
```
System.load(this.loadLibraryFromJarToTemp(var1).getAbsolutePath());
```
files gone and threw 'java.lang.UnsatisfiedLinkError' exception, System.load is a java standard function, i don't know why it cannot load.

**Comment by adamretter** [comment]
I think it is more likely that you are missing some libraries that are required by the DLL, as opposed to the DLL being deleted. What happens if you try building from source locally?

**Comment by BEWINDOWEB** [comment]
> I think it is more likely that you are missing some libraries that are required by the DLL, as opposed to the DLL being deleted. What happens if you try building from source locally?

no, i think not. The classloader will load:
* java1.8\jre\bin\instrument.dll
* java1.8\jre\bin\net.dll
* java1.8\jre\bin\nio.dll
one by one, and it works fine,then it load:
* ........\Local\Temp\librocksdbjni4239644554011197516.dll
the program stopped and said UnsatisfiedLinkError: librocksdbjni.dll refused to access.
And i check the permission of that file, it's OK. 
So i don't know what to do , i have no idea to debug, could you give some advice please, thanks.

**Comment by adamretter** [comment]
I would start by placing a breakpoint on the line:
```
System.load(this.loadLibraryFromJarToTemp(var1).getAbsolutePath());
```
When it hits the breakpoint, check your filesystem to make sure the temp DLL file actually exists ;-)

**Comment by BEWINDOWEB** [comment]
> I would start by placing a breakpoint on the line:
> 
> ```
> System.load(this.loadLibraryFromJarToTemp(var1).getAbsolutePath());
> ```
> When it hits the breakpoint, check your filesystem to make sure the temp DLL file actually exists ;-)

i've tried it yesterday, and the file is exist, but after throwing exception, it will be deleted.

and i found somebody encountered the same problem at 2017-11-03 19:41, https://www.cnblogs.com/wuxun1997/p/7780188.html, he hasn't fixed it yet.

Classloader.java, line 1941:
```
lib.load(name, isBuiltin);
```
cause the exception.

**Comment by adamretter** [comment]
> i've tried it yesterday, and the file is exist, but after throwing exception, it will be deleted.

Right! Because the exception happens before it is deleted I suspect you are missing some required libraries.

Next step... can you try building RocksDB from source? The details of how to do that are on the GitHub Wiki.
