### ISSUE TITLE
RocksDBException: Too many open files in system

### ISSUE THREAD

**Issue by javeme** [facebook/rocksdb#5488]
### Expected behavior
Close file descriptor after dropping ColumnFamily.

### Actual behavior
When we frequently create and drop ColumnFamily([test scenario](https://github.com/hugegraph/hugegraph/blob/master/hugegraph-test/src/main/java/com/baidu/hugegraph/tinkerpop/StructureStandardTest.java)), the number of open file descriptors continues to grow until an error occurs:
```
Caused by: org.rocksdb.RocksDBException: While open directory: rocksdb-data/schema: Too many open files in system
	at org.rocksdb.RocksDB.createColumnFamily(Native Method)
	at org.rocksdb.RocksDB.createColumnFamily(RocksDB.java:1706)
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStdSessions.createTable(RocksDBStdSessions.java:164)
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore.createTable(RocksDBStore.java:340)
```
Looking at the number of files opened by the process, it is really very large. It seems that the file descriptor did not been closed after dropping ColumnFamily.
```
$ lsof -p 95791 |grep rocksdb-data | wc -l
8014
```
OS: Mac 10.11.6

### Steps to reproduce the behavior
This problem can be easily reproduced (rocksjni):
```java
        ColumnFamilyDescriptor cfd = new ColumnFamilyDescriptor(encode("test"));
        for (int i = 0; i < 100000; i++) {
            ColumnFamilyHandle cfHandle = this.rocksdb.createColumnFamily(cfd);
            this.rocksdb.dropColumnFamily(cfHandle);
            cfHandle.close();
        }
```
Affected versions include:  **5.14.2**, **5.17.2**, **5.18.3** (We have already tested).

But an old version **5.8.6** we used before did not have this problem.

**Comment by miasantreble** [comment]
Hi, thanks for reporting. 
Are you able to reproduce this issue in c++?
I wrote a test but doesn't seem to repro
```
TEST_F(DBTest, TooManyOpenFiles) {
  ColumnFamilyOptions cf_options;
  WriteOptions write_options;
  Options options;
  ASSERT_OK(TryReopen(options));
  std::vector<std::string> cf_names;
  std::vector<ColumnFamilyHandle*> cf_handles;
  std::vector<ColumnFamilyDescriptor> cf_descriptors;
  cf_descriptors.emplace_back("cf1", ColumnFamilyOptions());
  cf_names.push_back("cf1");
  for (int i = 0; i < 100000; i++) {
    ASSERT_OK(db_->CreateColumnFamilies(cf_descriptors, &cf_handles));
    ASSERT_OK(db_->DropColumnFamilies(cf_handles));
    for (auto* handle : cf_handles) {
      delete handle;
    }
  }
  Close();
}
```
Also it would be helpful if you can paste the content from lsof, so that we can identify the issue. 
This is from my test:
```
db_test    315290         xiez  cwd       DIR               0,28       1422            253798583 /data/users/xiez/rocksdb
db_test    315290         xiez  rtd       DIR               0,28        294                  256 /
db_test    315290         xiez  txt       REG               0,28  157513488            350464163 /data/users/xiez/rocksdb/db_test
db_test    315290         xiez  mem       REG               0,27                       350464163 /data/users/xiez/rocksdb/db_test (path dev=0,28)
db_test    315290         xiez  mem       REG               0,27                       239367209 /usr/local/fbcode/gcc-5-glibc-2.23/lib/libc-2.23.so (path dev=0,28)
db_test    315290         xiez  mem       REG               0,27                       239367237 /usr/local/fbcode/gcc-5-glibc-2.23/lib/libgcc_s.so.1 (path dev=0,28)
db_test    315290         xiez  mem       REG               0,27                       239367274 /usr/local/fbcode/gcc-5-glibc-2.23/lib/libm-2.23.so (path dev=0,28)
db_test    315290         xiez  mem       REG               0,27                       239367327 /usr/local/fbcode/gcc-5-glibc-2.23/lib/librt-2.23.so (path dev=0,28)
db_test    315290         xiez  mem       REG               0,27                       239367314 /usr/local/fbcode/gcc-5-glibc-2.23/lib/libpthread-2.23.so (path dev=0,28)
db_test    315290         xiez  mem       REG               0,27                       239367337 /usr/local/fbcode/gcc-5-glibc-2.23/lib/libstdc++.so.6.0.21 (path dev=0,28)
db_test    315290         xiez  mem       REG               0,27                       239367230 /usr/local/fbcode/gcc-5-glibc-2.23/lib/libdl-2.23.so (path dev=0,28)
db_test    315290         xiez  mem       REG               0,27                       239367196 /usr/local/fbcode/gcc-5-glibc-2.23/lib/ld-2.23.so (path dev=0,28)
db_test    315290         xiez    0u      CHR              136,3        0t0                    6 /dev/pts/3
db_test    315290         xiez    1u      CHR              136,3        0t0                    6 /dev/pts/3
db_test    315290         xiez    2u      CHR              136,3        0t0                    6 /dev/pts/3
db_test    315290         xiez    3w      REG               0,28  127786170            350464178 /tmp/rocksdbtest-138022/db_test_8405410294672666538/LOG
db_test    315290         xiez    4r      DIR               0,28        198            350464170 /tmp/rocksdbtest-138022/db_test_8405410294672666538
db_test    315290         xiez    5u      REG               0,28          0            350464172 /tmp/rocksdbtest-138022/db_test_8405410294672666538/LOCK
db_test    315290         xiez    6r      DIR               0,28        198            350464170 /tmp/rocksdbtest-138022/db_test_8405410294672666538
db_test    315290         xiez    7w      REG               0,28    1146908            350464179 /tmp/rocksdbtest-138022/db_test_8405410294672666538/MANIFEST-000005
db_test    315290         xiez    8w      REG               0,28          0            350464181 /tmp/rocksdbtest-138022/db_test_8405410294672666538/000006.log
```

**Comment by javeme** [comment]
@miasantreble Thanks for your reply, Is the version you tried in [5.14.2, 5.17.2, 5.18.3]?
Seems the version of the dependent library is too low on my mac, the c++ rocksdb can't be compiled.
If you really can't reproduce it in c++, we may try with a virtual machine. Or maybe it’s just a issue in jni?

The content from lsof:
```sh
$ lsof -p 22055 | grep rocksdb-data | wc -l
     475
$  lsof -p 22055 | grep rocksdb-data
java    22055 username  257w     REG                1,4   3354918 43820696 /Users/username/hugegraph/hugegraph-example/rocksdb-data/schema/LOG
java    22055 username  259r     DIR                1,4       476 43820599 /Users/username/hugegraph/hugegraph-example/rocksdb-data/schema
java    22055 username  260u     REG                1,4         0 43820601 /Users/username/hugegraph/hugegraph-example/rocksdb-data/schema/LOCK
java    22055 username  261r     DIR                1,4       476 43820599 /Users/username/hugegraph/hugegraph-example/rocksdb-data/schema
java    22055 username  262w     REG                1,4     33891 43820697 /Users/username/hugegraph/hugegraph-example/rocksdb-data/schema/MANIFEST-000011
java    22055 username  263w     REG                1,4         0 43820699 /Users/username/hugegraph/hugegraph-example/rocksdb-data/schema/000012.log
java    22055 username  264w     REG                1,4     15550 43820705 /Users/username/hugegraph/hugegraph-example/rocksdb-data/system/LOG
java    22055 username  265r     DIR                1,4       442 43820668 /Users/username/hugegraph/hugegraph-example/rocksdb-data/system
java    22055 username  266u     REG                1,4         0 43820670 /Users/username/hugegraph/hugegraph-example/rocksdb-data/system/LOCK
java    22055 username  267r     DIR                1,4       442 43820668 /Users/username/hugegraph/hugegraph-example/rocksdb-data/system
java    22055 username  268w     REG                1,4        59 43820706 /Users/username/hugegraph/hugegraph-example/rocksdb-data/system/MANIFEST-000011
java    22055 username  269w     REG                1,4         0 43820708 /Users/username/hugegraph/hugegraph-example/rocksdb-data/system/000012.log
java    22055 username  270w     REG                1,4     15546 43820714 /Users/username/hugegraph/hugegraph-example/rocksdb-data/graph/LOG
java    22055 username  271r     DIR                1,4       442 43820680 /Users/username/hugegraph/hugegraph-example/rocksdb-data/graph
java    22055 username  272u     REG                1,4         0 43820682 /Users/username/hugegraph/hugegraph-example/rocksdb-data/graph/LOCK
java    22055 username  273r     DIR                1,4       442 43820680 /Users/username/hugegraph/hugegraph-example/rocksdb-data/graph
java    22055 username  274w     REG                1,4        59 43820715 /Users/username/hugegraph/hugegraph-example/rocksdb-data/graph/MANIFEST-000011
java    22055 username  275w     REG                1,4         0 43820717 /Users/username/hugegraph/hugegraph-example/rocksdb-data/graph/000012.log
java    22055 username  276r     DIR                1,4       476 43820599 /Users/username/hugegraph/hugegraph-example/rocksdb-data/schema
java    22055 username  277r     DIR                1,4       476 43820599 /Users/username/hugegraph/hugegraph-example/rocksdb-data/schema
java    22055 username  278r     DIR                1,4       476 43820599 /Users/username/hugegraph/hugegraph-example/rocksdb-data/schema
java    22055 username  279r     DIR                1,4       476 43820599 /Users/username/hugegraph/hugegraph-example/rocksdb-data/schema
java    22055 username  280r     DIR                1,4       476 43820599 /Users/username/hugegraph/hugegraph-example/rocksdb-data/schema
java    22055 username  281r     DIR                1,4       476 43820599 /Users/username/hugegraph/hugegraph-example/rocksdb-data/schema
java    22055 username  282r     DIR                1,4       476 43820599 /Users/username/hugegraph/hugegraph-example/rocksdb-data/schema
java    22055 username  283r     DIR                1,4       476 43820599 /Users/username/hugegraph/hugegraph-example/rocksdb-data/schema
java    22055 username  284r     DIR                1,4       476 43820599 /Users/username/hugegraph/hugegraph-example/rocksdb-data/schema
java    22055 username  285r     DIR                1,4       476 43820599 /Users/username/hugegraph/hugegraph-example/rocksdb-data/schema
java    22055 username  286r     DIR                1,4       476 43820599 /Users/username/hugegraph/hugegraph-example/rocksdb-data/schema
java    22055 username  287r     DIR                1,4       476 43820599 /Users/username/hugegraph/hugegraph-example/rocksdb-data/schema
java    22055 username  288r     DIR                1,4       476 43820599 /Users/username/hugegraph/hugegraph-example/rocksdb-data/schema
java    22055 username  289r     DIR                1,4       476 43820599 /Users/username/hugegraph/hugegraph-example/rocksdb-data/schema
java    22055 username  290r     DIR                1,4       476 43820599 /Users/username/hugegraph/hugegraph-example/rocksdb-data/schema
java    22055 username  291r     DIR                1,4       476 43820599 /Users/username/hugegraph/hugegraph-example/rocksdb-data/schema
... # The rest are the same
```

**Comment by javeme** [comment]
I tried a minimal complete program that can be reproduced every time on version rocksdbjni 5.14.2.
```java
    public static void main(String args[]) throws RocksDBException {
        String path = "rocksdb-data";

        DBOptions options = new DBOptions();
        options.setWalDir(path);
        options.setCreateIfMissing(true);

        //RocksDB rocksdb = RocksDB.open(options, path); // won't reproduce

        List<ColumnFamilyDescriptor> cfds = new ArrayList<>();
        cfds.add(new ColumnFamilyDescriptor(encode("default")));
        List<ColumnFamilyHandle> cfhs = new ArrayList<>();
        RocksDB rocksdb = RocksDB.open(options, path, cfds, cfhs);

        ColumnFamilyDescriptor cfd = new ColumnFamilyDescriptor(encode("test"));
        for (int i = 0; i < 100000; i++) {
            ColumnFamilyHandle cfHandle = rocksdb.createColumnFamily(cfd);
            rocksdb.dropColumnFamily(cfHandle);
            cfHandle.close();
        }
    }
```

**Comment by adamretter** [comment]
Apart from loading the native library, the Java API does not do any file IO itself, so I doubt this is a file IO problem in the Java API.

**Comment by javeme** [comment]
Found the cause: it seems that the [native handle](https://github.com/facebook/rocksdb/blob/v5.14.2/java/src/main/java/org/rocksdb/RocksDB.java#L1727) of ColumnFamilyHandle is leaked, then it has no effect to release native handle when calling [ColumnFamilyHandle.close()](https://github.com/facebook/rocksdb/blob/v5.14.2/java/src/main/java/org/rocksdb/ColumnFamilyHandle.java#L104)

**Comment by javeme** [comment]
This issue seems to be resolved: https://github.com/facebook/rocksdb/pull/4770/commits/e552a5dc3142ee38d31365ed3d4e82b20c955d30#diff-1d8e426769eb85777e184c4d254d3306L2361

**Comment by ChengGit** [comment]
hi @javeme @adamretter , may I know how did you solve this issue? I bumped into the same issue, and we are currently on 5.18.3, as we use kafka 2.4.0 library. Would exclude module `rocksdb.jni-5.18.3` from kafka dependency and provide an alternative `rocksdb.jni-6.7.2` work? could you shed some lights on?

**Comment by adamretter** [comment]
> rocksdb.jni-5.18.3 from kafka dependency and provide an alternative rocksdb.jni-6.7.2

@ChengGit I can't say. It depends on if Kafka is compatible or not. Best to chase with the Kafka project.
