### ISSUE TITLE
proper way to clean up iterator

### ISSUE THREAD

**Issue by mango009** [facebook/rocksdb#5500]
I almost always get a core dump upon program existing. It is a simple program that uses Iterator in a std::unique_ptr.  The last statement of the program is to close the database by issuing a Close() call . Is there a specific way to ensure database clean up?

```
#0  0x00007ffff658a428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff658c02a in __GI_abort () at abort.c:89
#2  0x00000000009fe96f in rocksdb::port::PthreadCall (label=0xd7b4ad "lock", result=22)
    at third_party/rocksdb/port/port_posix.cc:48
#3  0x00000000009fea9c in rocksdb::port::Mutex::Lock (this=0x7ffff47a84d8)
    at third_party/rocksdb/port/port_posix.cc:76
#4  0x0000000000969b9a in rocksdb::InstrumentedMutex::LockInternal (this=0x7ffff47a84d8)
    at third_party/rocksdb/monitoring/instrumented_mutex.cc:34
#5  0x0000000000969b50 in rocksdb::InstrumentedMutex::Lock (this=0x7ffff47a84d8)
    at third_party/rocksdb/monitoring/instrumented_mutex.cc:27
#6  0x00000000007e17b5 in rocksdb::(anonymous namespace)::CleanupIteratorState (
    arg1=0x7fffe41c1100) at third_party/rocksdb/db/db_impl.cc:1264
#7  0x00000000008859dd in rocksdb::Cleanable::DoCleanup (this=0x7fffe419d568)
    at third_party/rocksdb/include/rocksdb/cleanable.h:68
#8  0x0000000000a519e4 in rocksdb::Cleanable::~Cleanable (this=0x7fffe419d568, 
    __in_chrg=<optimized out>) at third_party/rocksdb/table/iterator.cc:22
#9  0x00000000008aab2c in rocksdb::InternalIteratorBase<rocksdb::Slice>::~InternalIteratorBase
    (this=0x7fffe419d560, __in_chrg=<optimized out>)
    at third_party/rocksdb/table/internal_iterator.h:23
#10 0x0000000000a65a8c in rocksdb::MergingIterator::~MergingIterator (this=0x7fffe419d560, 
    __in_chrg=<optimized out>) at third_party/rocksdb/table/merging_iterator.cc:86
#11 0x0000000000887975 in rocksdb::DBIter::~DBIter (this=0x7fffe419d040, 
    __in_chrg=<optimized out>) at third_party/rocksdb/db/db_iter.cc:167
#12 0x000000000088516e in rocksdb::ArenaWrappedDBIter::~ArenaWrappedDBIter (
    this=0x7fffe419d000, __in_chrg=<optimized out>) at third_party/rocksdb/db/db_iter.cc:1482
#13 0x00000000008851cc in rocksdb::ArenaWrappedDBIter::~ArenaWrappedDBIter (
    this=0x7fffe419d000, __in_chrg=<optimized out>) at third_party/rocksdb/db/db_iter.cc:1482
#14 0x000000000042c24a in std::default_delete<rocksdb::Iterator>::operator() (
    this=0x7fffffffd5f0, __ptr=0x7fffe419d000) at /usr/include/c++/5/bits/unique_ptr.h:76
#15 0x0000000000428385 in std::unique_ptr<rocksdb::Iterator, std::default_delete<rocksdb::Iterator> >::~unique_ptr (this=0x7fffffffd5f0, __in_chrg=<optimized out>)
    at /usr/include/c++/5/bits/unique_ptr.h:236
```

**Comment by miasantreble** [comment]
is it possible to paste your simple program? My guess is that you are doing double deletion but need to see your code to be sure

**Comment by ramvadiv** [comment]
Closing this old issue (which was pending more info from the Issue reporter). @mango009 - pls open a new issue, if you still have this problem and provide more details/sample code stub.
