### ISSUE TITLE
[JNI jar] UnsatisfiedLinkError using compiled jar

### ISSUE THREAD

**Issue by richardyc** [facebook/rocksdb#5597]
I try to use my Mac OS X 10.14.5 with openjdk version "1.8.0_212" to compile a crossbuild jar using `make jclean clean rocksdbjavastaticrelease`. I used the resulting `rocksdbjni-6.2.0.jar` and tests passed on my Mac using the jar.

However, when running in Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-1040-aws x86_64) using the same `rocksdbjni-6.2.0.jar`, I encountered 
```
org.rocksdb.SstFileReader.newSstFileReader(J)J
java.lang.UnsatisfiedLinkError: 
	at org.rocksdb.SstFileReader.newSstFileReader(Native Method)
	at org.rocksdb.SstFileReader.<init>(SstFileReader.java:14)
```

However, when I `jar xvf rocksdbjni-6.2.0.jar | grep librocksdbjni`, I saw
```
 inflated: librocksdbjni-linux32.so
 inflated: librocksdbjni-linux64.so
 inflated: librocksdbjni-osx.jnilib
```
So clearly the native library should be there in the jar, but seems like the native library cannot be found.

**Comment by richardyc** [comment]
The issue was internal version conflict, I also imported rocksdbjni jar that does not have this change, and for some reason the jar is looking for the native library that does not yet have this change. Removing the duplicated import solved the issue.
