### ISSUE TITLE
Segmentation Fault opening DB using All Static Linkage

### ISSUE THREAD

**Issue by biocodz** [facebook/rocksdb#5899]
I consistently encounter SIGSEGV when my binaries are All Static i.e. include All dependent libraries statically linked.

(!) Occasionally ( 1 in 20 or so ) it runs OK.

{!} The SIGSEGV happens on SECOND opening of the DB (i.e. it is opened once OK, then closed : [~KeyValueDatabase() { delete kvdb; }](https://github.com/biocore/sortmerna/blob/master/include/kvdb.hpp#L25), and crashes when opening the second time)

(!) It DOESN'T happen when RocksDB is linked Statically, and Runtime is SO.

RocksDB versions tested: master HEAD, 5.18.3, 6.2.4 (so this bug is NOT version dependent)
RocksDB build type: Release
OS: Ubuntu 16.04 Guest VM on VBox Windows Host
Compiler: GNU 7.4.0
Compression library: ZLib

Here is a partial execution trace when running in GDB:

NOTE: ellipsis (`...`)  is used in place of removed parts (non-important here)

```
# Executable and OS statistics
# Ubuntu 16.04
uname -a
  Linux ubuntu16 4.4.0-165-generic #193-Ubuntu SMP Tue Sep 17 17:42:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

# rocksdb 5.18.3
ls -l rocksdb/dist/lib/
   drwxrwxr-x 3 biocodz biocodz     4096 Oct  9 18:15 cmake
   -rw-r--r-- 1 biocodz biocodz 15688732 Oct  9 18:15 librocksdb.a
   lrwxrwxrwx 1 biocodz biocodz       15 Oct  9 18:15 librocksdb.so -> librocksdb.so.5
   lrwxrwxrwx 1 biocodz biocodz       20 Oct  9 18:15 librocksdb.so.5 -> librocksdb.so.5.18.3
   -rw-r--r-- 1 biocodz biocodz  7220808 Oct  9 18:03 librocksdb.so.5.18.3

# Executable using RocksDB (sortmerna) statically linked
which sortmerna | xargs ldd
    not a dynamic executable

 which sortmerna | xargs file
   /home/biocodz/sortmerna/dist_t1_smr3-0-4_rocks5-18-3/bin/sortmerna: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32,  BuildID[sha1]=8d11f85ecb313abf1b4b9760e6fe766f66cb33f5, not stripped

# Debug starts
gdb --args sortmerna ...(some flags)... -d $HOME/sortmerna/run/kvdb
GNU gdb (Ubuntu 8.2-0ubuntu1~16.04.1) 8.2
...
[ThreadPool:36] initialized Pool with: [10] threads
...
OPEN  (opening the rocksdb DB - first time)
...
OPENED   (DB is opened - OK)
...
[Refstats:32] Index Statistics calculation Start ... Done. Time elapsed: 0.96 sec
[align:414] Loading index 0 part 1/1 ... done [1.24] sec
[align:425] Loading references  ... done [0.75] sec
...
[ThreadPool:36] initialized Pool with: [3] threads
OPEN (opening the DB second time)
Thread 31 "rocksdb:high3" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff9bfff700 (LWP 6462)]
0x0000000000000000 in ?? ()
(gdb) where
#0  0x0000000000000000 in ?? ()
#1  0x00000000007f9da1 in std::thread::detach() ()
#2  0x0000000000729dc9 in rocksdb::ThreadPoolImpl::Impl::BGThread(unsigned long) ()
#3  0x0000000000729edf in rocksdb::ThreadPoolImpl::Impl::BGThreadWrapper(void*) ()
#4  0x00000000007f9aef in execute_native_thread_routine ()
#5  0x0000000000795835 in start_thread (arg=0x7fff9bfff700) at pthread_create.c:333
#6  0x00000000008df279 in clone ()
```
The error happens on this line [rocksdb::Status s = rocksdb::DB::Open(options, kvdbPath, &kvdb);](https://github.com/biocore/sortmerna/blob/master/include/kvdb.hpp#L22): 

I can provide more information including complete traces for building the libraries, executable, and from runs.

Any ideas are highly appreciated.

**Comment by biocodz** [comment]
Closing, as this appears to be a problem with the Ubuntu 16.04 runtime libraries. Exact same binaries built on Centos7 work fine on both Ubuntu and Centos.
