### ISSUE TITLE
MultiGet() crashes when running with BlockBasedTableOptions::no_block_cache=true

### ISSUE THREAD

**Issue by spetrunia** [facebook/rocksdb#5975]
Transaction::MultiGet call crashes with assertion if one runs with Block Cache
disabled:

```C++
  ColumnFamilyOptions cf_opt;
  BlockBasedTableOptions blk_opt;
  blk_opt.block_cache = nullptr;
  blk_opt.no_block_cache = true;
  cf_opt.table_factory.reset(NewBlockBasedTableFactory(blk_opt));

  ...
  Transaction* txn = db->BeginTransaction(WriteOptions(), TransactionOptions());
  txn->MultiGet(ReadOptions(), handles[0], keys.size(), keys.data(),
                values.data(), statuses.data());
```

crashes with 
```
transaction_test: table/block_based/block_based_table_reader.cc:2057: 
TBlockIter* rocksdb::BlockBasedTable::NewDataBlockIterator(const rocksdb::ReadOptions&,
 rocksdb::CachableEntry<rocksdb::Block>&, TBlockIter*, rocksdb::Status) const [with TBlockIter = 
rocksdb::DataBlockIter]: Assertion `block.GetValue() != nullptr' failed.
```

```
Thread 1 "transaction_tes" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) wher
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff5db8801 in __GI_abort () at abort.c:79
#2  0x00007ffff5da839a in __assert_fail_base (fmt=0x7ffff5f2f7d8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=assertion@entry=0x555555b4e12a "block.GetValue() != nullptr", 
    file=file@entry=0x555555b4d540 "table/block_based/block_based_table_reader.cc", line=line@entry=2057, 
    function=function@entry=0x555555b4eda0 <rocksdb::DataBlockIter* rocksdb::BlockBasedTable::NewDataBlockIterator<rocksdb::DataBlockIter>(rocksdb::ReadOptions const&, rocksdb::CachableEntry<rocksdb::Block>&, rocksdb::DataBlockIter*, rocksdb::Status) const::__PRETTY_FUNCTION__> "TBlockIter* rocksdb::BlockBasedTable::NewDataBlockIterator(const rocksdb::ReadOptions&, rocksdb::CachableEntry<rocksdb::Block>&, TBlockIter*, rocksdb::Status) const [with TBlockIter = rocksdb::DataBlo"...) at assert.c:92
#3  0x00007ffff5da8412 in __GI___assert_fail (assertion=assertion@entry=0x555555b4e12a "block.GetValue() != nullptr", 
    file=file@entry=0x555555b4d540 "table/block_based/block_based_table_reader.cc", line=line@entry=2057, 
    function=function@entry=0x555555b4eda0 <rocksdb::DataBlockIter* rocksdb::BlockBasedTable::NewDataBlockIterator<rocksdb::DataBlockIter>(rocksdb::ReadOptions const&, rocksdb::CachableEntry<rocksdb::Block>&, rocksdb::DataBlockIter*, rocksdb::Status) const::__PRETTY_FUNCTION__> "TBlockIter* rocksdb::BlockBasedTable::NewDataBlockIterator(const rocksdb::ReadOptions&, rocksdb::CachableEntry<rocksdb::Block>&, TBlockIter*, rocksdb::Status) const [with TBlockIter = rocksdb::DataBlo"...) at assert.c:101
#4  0x000055555592767c in rocksdb::BlockBasedTable::NewDataBlockIterator<rocksdb::DataBlockIter> (this=this@entry=0x7ffff1c49d40, ro=..., 
    block=..., input_iter=input_iter@entry=0x7fffffff6800, s=...) at table/block_based/block_based_table_reader.cc:2057
#5  0x00005555559239ee in rocksdb::BlockBasedTable::MultiGet (this=0x7ffff1c49d40, read_options=..., mget_range=<optimized out>, 
    prefix_extractor=<optimized out>, skip_filters=false) at table/block_based/block_based_table_reader.cc:3549
#6  0x000055555580e1e5 in rocksdb::TableCache::MultiGet (this=this@entry=0x7ffff555f8d0, options=..., internal_comparator=..., file_meta=..., 
    mget_range=mget_range@entry=0x7fffffff9a20, prefix_extractor=0x0, file_read_hist=0x7ffff5573000, skip_filters=false, level=0)
    at db/table_cache.cc:507
#7  0x00005555558366a3 in rocksdb::Version::MultiGet (this=<optimized out>, read_options=..., range=range@entry=0x7fffffffb270, 
    callback=callback@entry=0x0, is_blob=is_blob@entry=0x0) at db/version_set.cc:1947
#8  0x000055555572e71c in rocksdb::DBImpl::MultiGetImpl (this=this@entry=0x7ffff5532000, read_options=..., 
    column_family=column_family@entry=0x7ffff1c49320, key_context=..., sorted_input=sorted_input@entry=false, callback=callback@entry=0x0, 
    is_blob_index=0x0) at db/db_impl/db_impl.cc:1986
#9  0x0000555555a71b12 in rocksdb::WriteBatchWithIndex::MultiGetFromBatchAndDB (this=0x7ffff5492c98, db=<optimized out>, read_options=..., 
    column_family=0x7ffff1c49320, num_keys=7, keys=<optimized out>, values=0x7ffff554c300, statuses=0x7ffff547f9b0, sorted_input=false, 
    callback=0x0) at utilities/write_batch_with_index/write_batch_with_index.cc:998
#10 0x0000555555a725e6 in rocksdb::WriteBatchWithIndex::MultiGetFromBatchAndDB (this=<optimized out>, db=<optimized out>, read_options=..., 
    column_family=<optimized out>, num_keys=<optimized out>, keys=<optimized out>, values=0x7ffff554c300, statuses=0x7ffff547f9b0, 
    sorted_input=false) at utilities/write_batch_with_index/write_batch_with_index.cc:940
#11 0x0000555555a3a5e3 in rocksdb::TransactionBaseImpl::MultiGet (this=<optimized out>, read_options=..., column_family=<optimized out>, 
    num_keys=<optimized out>, keys=<optimized out>, values=<optimized out>, statuses=0x7ffff547f9b0, sorted_input=false)
    at utilities/transactions/transaction_base.cc:327
#12 0x00005555555ea05c in rocksdb::TransactionTest_MultiGetNoBlockCacheTest_Test::TestBody (this=0x7ffff551c600)
    at utilities/transactions/transaction_test.cc:4472
```

A complete testcase is here:
[psergey-no-block-cache-crash.diff.txt](https://github.com/facebook/rocksdb/files/3778001/psergey-no-block-cache-crash.diff.txt)

**Comment by spetrunia** [comment]
A smaller testcase, without garbage comments: [psergey-no-block-cache-crash-v2.diff.txt](https://github.com/facebook/rocksdb/files/3778018/psergey-no-block-cache-crash-v2.diff.txt)

**Comment by ltamasi** [comment]
Yes, it seems like the MultiGet code path relies on a block cache being present. Cc @anand1976

**Comment by anand1976** [comment]
I overlooked this case - thanks for catching it. Let me create a PR for the fix. Its simple to fix as there's no real reason MultiGet needs to rely on a block cache.

**Comment by siying** [comment]
It also reminds us that crash test doesn't cover the scenario that no block cache is used.
