### ISSUE TITLE
Getting UnsatisfiedLinkError

### ISSUE THREAD

**Issue by realSmushyTaco** [facebook/rocksdb#7222]
### Expected behavior
No error.
### Actual behavior
Crash:
```
[01:31:32 ERROR]: Error occurred while enabling Ride v1.0.0 (Is it up to date?)
java.lang.UnsatisfiedLinkError: 'long com.smushytaco.ride.shaded.org.rocksdb.Options.newOptions()'
        at com.smushytaco.ride.shaded.org.rocksdb.Options.newOptions(Native Method) ~[?:?]
        at com.smushytaco.ride.shaded.org.rocksdb.Options.<init>(Options.java:53) ~[?:?]
        at com.smushytaco.plugin.database.PersistentHashMap.<init>(PersistentHashMap.kt:17) ~[?:?]
        at com.smushytaco.plugin.RidePlugin.onEnable(RidePlugin.kt:16) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.1.jar:git-Paper-131]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.1.jar:git-Paper-131]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.1.jar:git-Paper-131]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:500) ~[patched_1.16.1.jar:git-Paper-131]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:414) ~[patched_1.16.1.jar:git-Paper-131]
        at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:471) ~[patched_1.16.1.jar:git-Paper-131]
        at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.1.jar:git-Paper-131]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:941) ~[patched_1.16.1.jar:git-Paper-131]        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-131]
        at java.lang.Thread.run(Thread.java:832) [?:?]
```
### Steps to reproduce the behavior
```kotlin
class PersistentHashMap(databaseName: String, databasePath: String) : KeyValueRepository<UUID, ArrayList<UUID>> {
    private val databaseDirectory = File(databasePath, databaseName)
    private lateinit var database: RocksDB
    init {
        RocksDB.loadLibrary()
        val options = Options()
        options.setCreateIfMissing(true)
        try {
            Files.createDirectories(Paths.get(databaseDirectory.parentFile.path))
            Files.createDirectories(Paths.get(databaseDirectory.absoluteFile.path))
            database = RocksDB.open(options, databaseDirectory.absolutePath)
        } catch (iOException: IOException) {
            println("Cause: ${iOException.cause}")
            println("Message: ${iOException.message}")
            iOException.printStackTrace()
        } catch (rocksDBException: RocksDBException) {
            println("Cause: ${rocksDBException.cause}")
            println("Message: ${rocksDBException.message}")
            rocksDBException.printStackTrace()
        }
    }
    override operator fun set(key: UUID, value: ArrayList<UUID>) {
        try {
            database.put(key.toByteArray(), value.toByteArray())
        } catch (rocksDBException: RocksDBException) {
            println("Cause: ${rocksDBException.cause}")
            println("Message: ${rocksDBException.message}")
            rocksDBException.printStackTrace()
        }
    }

    override operator fun get(key: UUID): ArrayList<UUID> {
        var uuidArrayList = arrayListOf<UUID>()
        try {
            val bytes = database.get(key.toByteArray())
            if (bytes != null) uuidArrayList = bytes.toUUIDArrayList()
        } catch (rocksDBException: RocksDBException) {
            println("Cause: ${rocksDBException.cause}")
            println("Message: ${rocksDBException.message}")
            rocksDBException.printStackTrace()
        }
        return uuidArrayList
    }

    override fun remove(key: UUID) {
        try {
            database.delete(key.toByteArray())
        } catch (rocksDBException: RocksDBException) {
            println("Cause: ${rocksDBException.cause}")
            println("Message: ${rocksDBException.message}")
            rocksDBException.printStackTrace()
        }
    }
}
```
Create an instance of this class and run the code and you'll get a crash. If it helps I'm using the latest Windows 10 version (64 bit) and I'm using rocksdb verion 6.11.4

**Comment by realSmushyTaco** [comment]
The crash refers to line 17 so it seems like just having the options variable there caused the crash for some reason.

**Comment by adamretter** [comment]
@realSmushyTaco The error:

```
java.lang.UnsatisfiedLinkError: 'long com.smushytaco.ride.shaded.org.rocksdb.Options.newOptions()'
```

Seems to indicate a problem in your code when calling `Options.newOptions()`. Have you loaded the native library first?

**Comment by realSmushyTaco** [comment]
> @realSmushyTaco The error:
> 
> 
> 
> ```
> 
> java.lang.UnsatisfiedLinkError: 'long com.smushytaco.ride.shaded.org.rocksdb.Options.newOptions()'
> 
> ```
> 
> 
> 
> Seems to indicate a problem in your code when calling `Options.newOptions()`. Have you loaded the native library first?

@adamretter yes I have, check the code under steps to reproduce, the first thing I do is call `RocksDB.loadLibrary()`

**Comment by adamretter** [comment]
@realSmushyTaco Which version of RocksDB?

Just loading the options is a very simple thing - and we have many test cases for this. Can you please boil down your example to a minimum reproducible test case and make sure to express it in Java please.

**Comment by realSmushyTaco** [comment]
> @realSmushyTaco Which version of RocksDB?
> 
> 
> 
> Just loading the options is a very simple thing - and we have many test cases for this. Can you please boil down your example to a minimum reproducible test case and make sure to express it in Java please.

@adamretter as state on the bottom of the initial post I'm using 6.11.4 on the latest version of windows (64 bit). Regarding rewriting that in Java I just followed along with this tutorial: https://dev.to/thegroo/simple-rocksdb-with-java-crash-course-20o7 in Kotlin (But without all the extra annotation stuff they used), if you can't read Kotlin just read the code there, it's an accurate representation of the code I posted here.

**Comment by adamretter** [comment]
>  if you can't read Kotlin just read the code there, it's an accurate representation of the code I posted here.

That may be the case.

However, there is more code there than you need to reproduce the error. To help us to help you, please follow our instructions of creating a minimal reproducible test-case in Java. I suspect that when you distill this down to the bare-minimum we can quickly identify the problem.

**Comment by realSmushyTaco** [comment]
```java
public class PersistentHashMapJava {
    void PersistentHashMap() {
        RocksDB.loadLibrary();
        Options options = new Options();
        options.setCreateIfMissing(true);
    }
}
```
That's the Java equivalent of the code that ran from the start up to the crash.

**Comment by JanTuck** [comment]
Relocation issue.

**Comment by Proximyst** [comment]
To explain more on Jan's comment:

The issue is that OP is relocating the library and its usages. This means the functions in the native code is not the same as expected (i.e. it is not `org.rocksdb`). If OP tries this without relocation, it should work just fine.

**Comment by realSmushyTaco** [comment]
```kotlin
import com.github.jengelman.gradle.plugins.shadow.tasks.ConfigureShadowRelocation
import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar
plugins {
    java
    val kotlinVersion: String by System.getProperties()
    kotlin("jvm").version(kotlinVersion)
    id("com.github.johnrengelman.shadow").version("6.0.0")
}
group = "com.smushytaco"
version = "1.0.0"
repositories {
    mavenCentral()
    maven("https://papermc.io/repo/repository/maven-public/")
}
dependencies {
    val kotlinVersion: String by System.getProperties()
    implementation(kotlin("stdlib", kotlinVersion))
    implementation("org.rocksdb", "rocksdbjni", "6.11.4")
    //https://papermc.io/javadocs/paper/1.16/overview-summary.html
    compileOnly("com.destroystokyo.paper", "paper-api", "1.16.1-R0.1-SNAPSHOT")
}
val autoRelocate by tasks.register<ConfigureShadowRelocation>("configureShadowRelocation", ConfigureShadowRelocation::class) {
    target = tasks.getByName("shadowJar") as ShadowJar?
    val packageName = "${project.group}.${project.name.toLowerCase()}"
    prefix = "$packageName.shaded"
}
tasks {
    shadowJar {
        archiveClassifier.set("")
        project.configurations.implementation.get().isCanBeResolved = true
        configurations = listOf(project.configurations.implementation.get())
        dependsOn(autoRelocate)
        minimize()
    }
    build {
        dependsOn(shadowJar)
    }
}
```
Since you guys do support Java I assume somebody's had an issue with this before, any help with figuring out what exactly needs to be done to my build.gradle.kts fix my issue would mean a lot. If you don't know how to fix it I don't blame you gradle is confusing lol

**Comment by adamretter** [comment]
@realSmushyTaco It's not simple at all.

The C++ code for the JNI layer is written in such a way that certain function names (including namespaces) are expected. You would be best not to relocate the package names for RocksDB when you create your Uber jar.
