### ISSUE TITLE
Database corrupted itself after a restart

### ISSUE THREAD

**Issue by Cavallium** [facebook/rocksdb#7326]
After closing a rocksdb database as usual, the database can't be opened anymore.
The database is almost a year old and it never had such problems.
The only special operation that I did recently was adding a new column family to the database, but it still worked afterwards.

### Expected behavior
Being able to open the database.

### Actual behavior
The database can't be opened anymore.
```stacktrace
org.rocksdb.RocksDBException: Can't access /261271.sst: IO error: No such file or directorywhile stat a file for size: /srv/data/database_main_hot/261271.sst: No such file or directo
ry                                                  
Can't access /261249.sst: IO error: No such file or directorywhile stat a file for size: /srv/data/database_main_hot/261249.sst: No such file or directory
Can't access /261204.sst: IO error: No such file or directorywhile stat a file for size: /srv/data/database_main_hot/261204.sst: No such file or directory
Can't access /261205.sst: IO error: No such file or directorywhile stat a file for size: /srv/data/database_main_hot/261205.sst: No such file or directory
Can't access /259716.sst: IO error: No such file or directorywhile stat a file for size: /srv/data/database_main_hot/259716.sst: No such file or directory
Can't access /259717.sst: IO error: No such file or directorywhile stat a file for size: /srv/data/database_main_hot/259717.sst: No such file or directory
Can't access /259718.sst: IO error: No such file or directorywhile stat a file for size: /srv/data/database_main_hot/259718.sst: No such file or directory
Can't access /259720.sst: IO error: No such file or directorywhile stat a file for size: /srv/data/database_main_hot/259720.sst: No such file or directory
Can't access /259721.sst: IO error: No such file or directorywhile stat a file for size: /srv/data/database_main_hot/259721.sst: No such file or directory
Can't access /259723.sst: IO error: No such file or directorywhile stat a file for size: /srv/data/database_main_hot/259723.sst: No such file or directory
Can't access /259724.sst: IO error: No such file or directorywhile stat a file for size: /srv/data/database_main_hot/259724.sst: No such file or directory
Can't access /259726.sst: IO error: No such file or directorywhile stat a file for size: /srv/data/database_main_hot/259726.sst: No such file or directory
Can't access /259727.sst: IO error: No such file or directorywhile stat a file for size: /srv/data/database_main_hot/259727.sst: No such file or directory
Can't access /259728.sst: IO error: No such file or directorywhile stat a file for size: /srv/data/database_main_hot/259728.sst: No such file or directory

        at org.rocksdb.RocksDB.open(Native Method)
        at org.rocksdb.RocksDB.open(RocksDB.java:290)
        ... 6 more 
```

### Steps to reproduce the behavior
rocksdbjni version 6.11.4

Options:
``` ini
# This is a RocksDB option file.
#
# For detailed file format spec, please refer to the example file
# in examples/rocksdb_option_file_example.ini
#

[Version]
  rocksdb_version=6.7.3
  options_file_version=1.1

[DBOptions]
  write_dbid_to_manifest=false
  avoid_unnecessary_blocking_io=false
  two_write_queues=false
  allow_ingest_behind=false
  writable_file_max_buffer_size=1048576
  avoid_flush_during_shutdown=false
  avoid_flush_during_recovery=false
  info_log_level=INFO_LEVEL
  access_hint_on_compaction_start=NORMAL
  allow_concurrent_memtable_write=true
  enable_pipelined_write=false
  stats_dump_period_sec=600
  stats_persist_period_sec=600
  strict_bytes_per_sync=false
  WAL_ttl_seconds=30
  WAL_size_limit_MB=1024
  max_subcompactions=1
  dump_malloc_stats=false
  db_log_dir=
  wal_recovery_mode=kPointInTimeRecovery
  log_file_time_to_roll=0
  enable_write_thread_adaptive_yield=true
  recycle_log_file_num=0
  table_cache_numshardbits=6
  atomic_flush=false
  preserve_deletes=false
  stats_history_buffer_size=1048576
  max_open_files=-1
  max_file_opening_threads=16
  delete_obsolete_files_period_micros=20000000
  max_background_flushes=-1
  write_thread_slow_yield_usec=3
  base_background_compactions=-1
  manual_wal_flush=false
  wal_dir=/srv/data/database_main
  max_background_compactions=-1
  bytes_per_sync=10485760
  max_background_jobs=4
  use_fsync=false
  unordered_write=false
  fail_if_options_file_error=false
  random_access_max_buffer_size=1048576
  compaction_readahead_size=0
  wal_bytes_per_sync=10485760
  new_table_reader_for_compaction_inputs=false
  skip_stats_update_on_db_open=false
  persist_stats_to_disk=false
  skip_log_error_on_recovery=false
  log_readahead_size=0
  is_fd_close_on_exec=true
  use_adaptive_mutex=false
  error_if_exists=false
  write_thread_max_yield_usec=100
  enable_thread_tracking=false
  db_write_buffer_size=0
  create_missing_column_families=false
  paranoid_checks=true
  create_if_missing=true
  max_manifest_file_size=1073741824
  allow_2pc=false
  max_total_wal_size=8589934592
  use_direct_io_for_flush_and_compaction=false
  manifest_preallocation_size=4194304
  use_direct_reads=false
  delayed_write_rate=16777216
  allow_fallocate=true
  max_write_batch_group_size_bytes=1048576
  keep_log_file_num=10
  allow_mmap_reads=false
  max_log_file_size=0
  allow_mmap_writes=false
  advise_random_on_open=true

[CFOptions "default"]
  sample_for_compression=0
  compaction_pri=kMinOverlappingRatio
  merge_operator=nullptr
  compaction_filter_factory=nullptr
  memtable_factory=SkipListFactory
  memtable_insert_with_hint_prefix_extractor=nullptr
  comparator=leveldb.BytewiseComparator
  target_file_size_base=67108864
  max_sequential_skip_in_iterations=8
  compaction_style=kCompactionStyleLevel
  max_bytes_for_level_base=268435456
  bloom_locality=0
  write_buffer_size=67108864
  compression_per_level=
  memtable_huge_page_size=0
  max_successive_merges=0
  arena_block_size=8388608
  memtable_whole_key_filtering=false
  target_file_size_multiplier=1
  max_bytes_for_level_multiplier_additional=1:1:1:1:1:1:1
  num_levels=7
  min_write_buffer_number_to_merge=1
  max_write_buffer_number_to_maintain=0
  max_write_buffer_number=2
  compression=kSnappyCompression
  level0_stop_writes_trigger=36
  level0_slowdown_writes_trigger=20
  compaction_filter=nullptr
  level0_file_num_compaction_trigger=4
  max_compaction_bytes=1677721600
  compaction_options_universal={stop_style=kCompactionStopStyleTotalSize;compression_size_percent=-1;allow_trivial_move=false;max_merge_width=4294967295;max_size_amplification_percent=200;min_merge_width=2;size_ratio=1;}
  memtable_prefix_bloom_size_ratio=0,000000
  max_write_buffer_size_to_maintain=0
  hard_pending_compaction_bytes_limit=274877906944
  ttl=2592000
  table_factory=BlockBasedTable
  soft_pending_compaction_bytes_limit=68719476736
  prefix_extractor=nullptr
  bottommost_compression=kDisableCompressionOption
  force_consistency_checks=false
  paranoid_file_checks=false
  compaction_options_fifo={allow_compaction=false;max_table_files_size=1073741824;}
  max_bytes_for_level_multiplier=10,000000
  optimize_filters_for_hits=false
  level_compaction_dynamic_level_bytes=false
  inplace_update_num_locks=10000
  inplace_update_support=false
  periodic_compaction_seconds=0
  disable_auto_compactions=false
  report_bg_io_stats=false
  
[TableOptions/BlockBasedTable "default"]
  pin_top_level_index_and_filter=true
  enable_index_compression=true
  read_amp_bytes_per_bit=8589934592
  format_version=2
  block_align=false
  metadata_block_size=4096
  block_size_deviation=10
  partition_filters=false
  block_size=4096
  index_block_restart_interval=1
  no_block_cache=false
  checksum=kCRC32c
  whole_key_filtering=true
  index_shortening=kShortenSeparators
  data_block_index_type=kDataBlockBinarySearch
  index_type=kBinarySearch
  verify_compression=false
  filter_policy=nullptr
  data_block_hash_table_util_ratio=0,750000
  pin_l0_filter_and_index_blocks_in_cache=false
  block_restart_interval=16
  cache_index_and_filter_blocks_with_high_priority=true
  cache_index_and_filter_blocks=false
  hash_index_allow_collision=true
  flush_block_policy_factory=FlushBlockBySizePolicyFactory
  

[CFOptions "hash_map_members_deep"]
  sample_for_compression=0
  compaction_pri=kMinOverlappingRatio
  merge_operator=nullptr
  compaction_filter_factory=nullptr
  memtable_factory=SkipListFactory
  memtable_insert_with_hint_prefix_extractor=nullptr
  comparator=leveldb.BytewiseComparator
  target_file_size_base=67108864
  max_sequential_skip_in_iterations=8
  compaction_style=kCompactionStyleLevel
  max_bytes_for_level_base=268435456
  bloom_locality=0
  write_buffer_size=67108864
  compression_per_level=
  memtable_huge_page_size=0
  max_successive_merges=0
  arena_block_size=8388608
  memtable_whole_key_filtering=false
  target_file_size_multiplier=1
  max_bytes_for_level_multiplier_additional=1:1:1:1:1:1:1
  num_levels=7
  min_write_buffer_number_to_merge=1
  max_write_buffer_number_to_maintain=0
  max_write_buffer_number=2
  compression=kSnappyCompression
  level0_stop_writes_trigger=36
  level0_slowdown_writes_trigger=20
  compaction_filter=nullptr
  level0_file_num_compaction_trigger=4
  max_compaction_bytes=1677721600
  compaction_options_universal={stop_style=kCompactionStopStyleTotalSize;compression_size_percent=-1;allow_trivial_move=false;max_merge_width=4294967295;max_size_amplification_percent=200;min_merge_width=2;size_ratio=1;}
  memtable_prefix_bloom_size_ratio=0,000000
  max_write_buffer_size_to_maintain=0
  hard_pending_compaction_bytes_limit=274877906944
  ttl=2592000
  table_factory=BlockBasedTable
  soft_pending_compaction_bytes_limit=68719476736
  prefix_extractor=nullptr
  bottommost_compression=kDisableCompressionOption
  force_consistency_checks=false
  paranoid_file_checks=false
  compaction_options_fifo={allow_compaction=false;max_table_files_size=1073741824;}
  max_bytes_for_level_multiplier=10,000000
  optimize_filters_for_hits=false
  level_compaction_dynamic_level_bytes=false
  inplace_update_num_locks=10000
  inplace_update_support=false
  periodic_compaction_seconds=0
  disable_auto_compactions=false
  report_bg_io_stats=false
  
[TableOptions/BlockBasedTable "hash_map_members_deep"]
  pin_top_level_index_and_filter=true
  enable_index_compression=true
  read_amp_bytes_per_bit=8589934592
  format_version=2
  block_align=false
  metadata_block_size=4096
  block_size_deviation=10
  partition_filters=false
  block_size=4096
  index_block_restart_interval=1
  no_block_cache=false
  checksum=kCRC32c
  whole_key_filtering=true
  index_shortening=kShortenSeparators
  data_block_index_type=kDataBlockBinarySearch
  index_type=kBinarySearch
  verify_compression=false
  filter_policy=nullptr
  data_block_hash_table_util_ratio=0,750000
  pin_l0_filter_and_index_blocks_in_cache=false
  block_restart_interval=16
  cache_index_and_filter_blocks_with_high_priority=true
  cache_index_and_filter_blocks=false
  hash_index_allow_collision=true
  flush_block_policy_factory=FlushBlockBySizePolicyFactory
  

[CFOptions "hash_set_solid_free_uids_set"]
  sample_for_compression=0
  compaction_pri=kMinOverlappingRatio
  merge_operator=nullptr
  compaction_filter_factory=nullptr
  memtable_factory=SkipListFactory
  memtable_insert_with_hint_prefix_extractor=nullptr
  comparator=leveldb.BytewiseComparator
  target_file_size_base=67108864
  max_sequential_skip_in_iterations=8
  compaction_style=kCompactionStyleLevel
  max_bytes_for_level_base=268435456
  bloom_locality=0
  write_buffer_size=67108864
  compression_per_level=
  memtable_huge_page_size=0
  max_successive_merges=0
  arena_block_size=8388608
  memtable_whole_key_filtering=false
  target_file_size_multiplier=1
  max_bytes_for_level_multiplier_additional=1:1:1:1:1:1:1
  num_levels=7
  min_write_buffer_number_to_merge=1
  max_write_buffer_number_to_maintain=0
  max_write_buffer_number=2
  compression=kSnappyCompression
  level0_stop_writes_trigger=36
  level0_slowdown_writes_trigger=20
  compaction_filter=nullptr
  level0_file_num_compaction_trigger=4
  max_compaction_bytes=1677721600
  compaction_options_universal={stop_style=kCompactionStopStyleTotalSize;compression_size_percent=-1;allow_trivial_move=false;max_merge_width=4294967295;max_size_amplification_percent=200;min_merge_width=2;size_ratio=1;}
  memtable_prefix_bloom_size_ratio=0,000000
  max_write_buffer_size_to_maintain=0
  hard_pending_compaction_bytes_limit=274877906944
  ttl=2592000
  table_factory=BlockBasedTable
  soft_pending_compaction_bytes_limit=68719476736
  prefix_extractor=nullptr
  bottommost_compression=kDisableCompressionOption
  force_consistency_checks=false
  paranoid_file_checks=false
  compaction_options_fifo={allow_compaction=false;max_table_files_size=1073741824;}
  max_bytes_for_level_multiplier=10,000000
  optimize_filters_for_hits=false
  level_compaction_dynamic_level_bytes=false
  inplace_update_num_locks=10000
  inplace_update_support=false
  periodic_compaction_seconds=0
  disable_auto_compactions=false
  report_bg_io_stats=false
  
[TableOptions/BlockBasedTable "hash_set_solid_free_uids_set"]
  pin_top_level_index_and_filter=true
  enable_index_compression=true
  read_amp_bytes_per_bit=8589934592
  format_version=2
  block_align=false
  metadata_block_size=4096
  block_size_deviation=10
  partition_filters=false
  block_size=4096
  index_block_restart_interval=1
  no_block_cache=false
  checksum=kCRC32c
  whole_key_filtering=true
  index_shortening=kShortenSeparators
  data_block_index_type=kDataBlockBinarySearch
  index_type=kBinarySearch
  verify_compression=false
  filter_policy=nullptr
  data_block_hash_table_util_ratio=0,750000
  pin_l0_filter_and_index_blocks_in_cache=false
  block_restart_interval=16
  cache_index_and_filter_blocks_with_high_priority=true
  cache_index_and_filter_blocks=false
  hash_index_allow_collision=true
  flush_block_policy_factory=FlushBlockBySizePolicyFactory
  
```

**Comment by cheng-chang** [comment]
Can you access files under /srv/data/database_main_hot/? Is it a permission issue?

**Comment by Cavallium** [comment]
Yes, I can access them, there are all the .sst files with the right permission, but the ones that are listed in the error are missing.

**Comment by zhaojintaozhao** [comment]
> Yes, I can access them, there are all the .sst files with the right permission, but the ones that are listed in the error are missing.
I also had the same problem. When database restart, it lost sst files. How did you solve it？

**Comment by ajkr** [comment]
@zhaojintaozhao Can you provide more details? Is there an error message or a LOG file we can see? How did you notice SST files were lost?

**Comment by riversand963** [comment]
PIng @zhaojintaozhao ?

**Comment by riversand963** [comment]
closing due to lack of details and inactivity.

**Comment by btiwana12** [comment]
We are facing a similar issue as well.. Exact same log message.

**Comment by aceqbaceq** [comment]
+1
