### ISSUE TITLE
v6.4.6 segfault error  in lru_cache when DeleteEntry

### ISSUE THREAD

**Issue by lnparker** [facebook/rocksdb#7391]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Actual behavior
segfault  : general protection ip:ac9501 sp:7fae9a5fa4e0 error:0

gcc:4.8.2
rocksdb:v6.4.6

```
(gdb) bt
#0  0x0000000000ac9501 in __exchange_and_add (__val=-1, __mem=0x12c913b946e704f8) at /usr/include/c++/4.8.2/ext/atomicity.h:49
#1  __exchange_and_add_dispatch (__val=-1, __mem=0x12c913b946e704f8) at /usr/include/c++/4.8.2/ext/atomicity.h:82
#2  _M_dispose (__a=..., this=0x12c913b946e704e8) at /usr/include/c++/4.8.2/bits/basic_string.h:246
#3  ~basic_string (this=0x7fad73415845, __in_chrg=<optimized out>) at /usr/include/c++/4.8.2/bits/basic_string.h:539
#4  rocksdb::(anonymous namespace)::DeleteEntry<std::basic_string<char> > (value=0x7fad73415845)
    at /export/jiangshouchao/jd/jimdb/jimkv/.external/rocksdb/db/table_cache.cc:40
#5  0x0000000000a147bf in Free (this=0x7fadf35b8000) at /export/jiangshouchao/jd/jimdb/jimkv/.external/rocksdb/cache/lru_cache.h:127
#6  rocksdb::LRUCacheShard::Insert (this=<optimized out>, key=..., hash=<optimized out>, value=0x7fadcb4cdf70, charge=<optimized out>,
    deleter=0xac94c0 <rocksdb::(anonymous namespace)::DeleteEntry<std::basic_string<char> >(rocksdb::Slice const&, void*)>, handle=0x0,
    priority=rocksdb::Cache::LOW) at /export/jiangshouchao/jd/jimdb/jimkv/.external/rocksdb/cache/lru_cache.cc:394
#7  0x0000000000a15428 in rocksdb::ShardedCache::Insert (this=0x7faeaf231a18, key=..., value=0x7fadcb4cdf70, charge=90,
    deleter=0xac94c0 <rocksdb::(anonymous namespace)::DeleteEntry<std::basic_string<char> >(rocksdb::Slice const&, void*)>, handle=0x0,
    priority=rocksdb::Cache::LOW) at /export/jiangshouchao/jd/jimdb/jimkv/.external/rocksdb/cache/sharded_cache.cc:51
#8  0x0000000000aca8c2 in rocksdb::TableCache::Get (this=0x7fae81e0e680, options=..., internal_comparator=..., file_meta=..., k=...,
    get_context=get_context@entry=0x7fae9a5fa9e0, prefix_extractor=0x0, file_read_hist=0x7fae81fce758, skip_filters=false, level=4)
    at /export/jiangshouchao/jd/jimdb/jimkv/.external/rocksdb/db/table_cache.cc:383
#9  0x0000000000ae465b in rocksdb::Version::Get (this=0x7fae660d7800, read_options=..., k=..., value=value@entry=0x7fae9a5fae50,
    status=status@entry=0x7fae9a5faf00, merge_context=merge_context@entry=0x7fae9a5fabe0,
    max_covering_tombstone_seq=max_covering_tombstone_seq@entry=0x7fae9a5fabc8, value_found=value_found@entry=0x0,
    key_exists=key_exists@entry=0x0, seq=seq@entry=0x0, callback=callback@entry=0x0, is_blob=is_blob@entry=0x0)
    at /export/jiangshouchao/jd/jimdb/jimkv/.external/rocksdb/db/version_set.cc:1702
#10 0x0000000000a19de0 in rocksdb::DBImpl::GetImpl (this=0x7fae81e33000, read_options=..., column_family=<optimized out>, key=...,
    pinnable_val=0x7fae9a5fae50, value_found=value_found@entry=0x0, callback=callback@entry=0x0, is_blob_index=is_blob_index@entry=0x0)
    at /export/jiangshouchao/jd/jimdb/jimkv/.external/rocksdb/db/db_impl/db_impl.cc:1552
#11 0x0000000000a1a37b in rocksdb::DBImpl::Get (this=<optimized out>, read_options=..., column_family=<optimized out>, key=...,
    value=<optimized out>) at /export/jiangshouchao/jd/jimdb/jimkv/.external/rocksdb/db/db_impl/db_impl.cc:1444
#12 0x0000000000a316a5 in rocksdb::DB::Get (this=0x7fae81e33000, options=..., column_family=0x7fae643c4b80, key=..., value=0x7fae9a5fafc0)
    at /export/jiangshouchao/jd/jimdb/jimkv/.external/rocksdb/include/rocksdb/db.h:392
```

### Steps to reproduce the behavior
sorry,  the crash is not  reproducible  since it happens after several days of processing of a rather large dataset.

**Comment by lnparker** [comment]
hello, anybody helps me , thank u !

**Comment by jay-zhuang** [comment]
Thanks @lnparker for reporting the issue. How often does it happen? It would be great if you could provide more information to help us reproduce the issue.

**Comment by lnparker** [comment]
sorry, the crash is not reproducible since it happens after several days of processing of a rather large dataset.
gcc:4.8.2
rocksdb:v6.4.6
segfault : general protection ip:ac9501 sp:7fae9a5fa4e0 error:0

is it possible that the reason is because gcc version ? @jay-zhuang

**Comment by ramvadiv** [comment]
@lnparker - any more info on this issue? 

For example: 
- Is it reproducible with later releases of RocksDB? 
- Any new data on reproducibility of this issue?
