### ISSUE TITLE
rocksdbjava error: Exception in thread "main" java.lang.UnsatisfiedLinkError: /tmp/librocksdbjni4785964616785894573.so:

### ISSUE THREAD

**Issue by GOGOYAO** [facebook/rocksdb#7620]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

I want to use HdfsEnv in rocksdbjava, which is not supported on Maven central repo. So I compile it following the wiki.
Then I add the dependency like this:
```
<dependency>
            <groupId>org.rocksdb</groupId>
            <artifactId>rocksdbjni</artifactId>
            <version>6.14.0</version>
            <scope>system</scope>
            <systemPath>xxxx/rocksdbjni-6.14.0-linux64.jar</systemPath>
</dependency>
```
And I use rocksdbjava like this:
```
    public void testSstFileWriter(String path) throws IOException {
        RocksDB.loadLibrary();
        DBOptions dbOps = new DBOptions();
        HdfsEnv env = new HdfsEnv("");
        dbOps.setEnv(env);
        SstFileWriter sstWriter = new SstFileWriter(new EnvOptions(dbOps), new Options());
        try {
            sstWriter.open(path);
            String key = "1";
            String value = "1";
            sstWriter.put(key.getBytes(), value.getBytes());
            sstWriter.finish();
        } catch (Exception e) {
            LOG.error(e.toString());
        }
    }
```

I can compile my code, but I can not run it.

### Expected behavior
succeeded to run my code.
### Actual behavior

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: /tmp/librocksdbjni4785964616785894573.so: libjemalloc.so.1: no such file or directory
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1938)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1821)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:79)
	at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:57)
	at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:69)
	at org.rocksdb.RocksDB.<clinit>(RocksDB.java:38)
	at org.rocksdb.DBOptions.<clinit>(DBOptions.java:22)
	at com.kuaishou.data.udf.ad.TestMain.testSstFileWriter(TestMain.java:52)
	at com.kuaishou.data.udf.ad.TestMain.main(TestMain.java:96)
```

**Comment by adamretter** [comment]
@GOGOYAO It looks like you have built a version of RocksJava which is dynamically linked against jemalloc, but the system you are running it on does not have the same jemalloc library installed.

**Comment by GOGOYAO** [comment]
@adamretter I have compile rocksdbjava with `ROCKSDB_DISABLE_JEMALLOC=true make -j8 rocksdbjava` but I get the same error. Any more ideas?

**Comment by adamretter** [comment]
@GOGOYAO If you have compiled it with `ROCKSDB_DISABLE_JEMALLOC=true make -j8 rocksdbjava` I cannot see how you could have any errors about jemalloc!?!
