### ISSUE TITLE
Java MultiGet NPE with key list 70_000 , but ok with 60_000

### ISSUE THREAD

**Issue by hsnamed** [facebook/rocksdb#8039]
rocksdbjni-6-5-12

What the reason for this behavior
All options by default

```
private byte[] generateString(int size) {
        var ba = new byte[size];
        new Random().nextBytes(ba);
        return ba;
 }
var lst = IntStream.range(0, 70_000).mapToObj(i -> generateString(4)).collect(Collectors.toList());
var res= db.multiGetAsList(lst);

```
Got exception

```
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
	at java.base/java.util.Arrays$ArrayList.<init>(Arrays.java:4323)
	at java.base/java.util.Arrays.asList(Arrays.java:4310)
	at org.rocksdb.RocksDB.multiGetAsList(RocksDB.java:2424)

```
But multigeting list with 60_000 keys is ok.

**Comment by adamretter** [comment]
@hsnamed Thanks for the report, I can reproduce this via the test:
```
/**
   * Test for https://github.com/facebook/rocksdb/issues/8039
   */
  @Test
  public void multiGetAsListLarge() throws RocksDBException {
    final List<byte[]> keys = new ArrayList();
    for (int i = 0; i < 70000; i++) {
      final byte[] key = new byte[4];
      rand.nextBytes(key);
      keys.add(key);
    }

    try (final Options opt = new Options()
                 .setCreateIfMissing(true);
         final RocksDB db = RocksDB.open(opt,
                 dbFolder.getRoot().getAbsolutePath())
    ) {
      final List<byte[]> values = db.multiGetAsList(keys);
      assertThat(values.size()).isEqualTo(keys.size());
    }
  }
```
