### ISSUE TITLE
Write failed: Compaction error: Corruption: Compaction sees out-of-order keys.

### ISSUE THREAD

**Issue by rohitjoshi** [facebook/rocksdb#8248]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
When writing to rocksdb, it should be successful.
### Actual behavior
Write fails with `Compaction error: Corruption: Compaction sees out-of-order keys.` error.
```
2021/04/29-22:52:31.965199 7f40affff700 [db/compaction/compaction_job.cc:1532] [default] [JOB 3] Generated table #87431: 258662 keys, 33734873 bytes
2021/04/29-22:52:31.965241 7f40affff700 EVENT_LOG_v1 {"time_micros": 1619751151965218, "cf_name": "default", "job": 3, "event": "table_file_creation", "file_number": 87431, "file_size": 33734873, "file_checksum": "", "file_checksum_func_name": "Unknown", "table_properties": {"data_size": 33555953, "index_size": 236917, "index_partitions": 0, "top_level_index_size": 0, "index_key_is_user_key": 1, "index_value_is_delta_encoded": 1, "filter_size": 0, "raw_key_size": 7245071, "raw_average_key_size": 28, "raw_value_size": 44208872, "raw_average_value_size": 170, "num_data_blocks": 12919, "num_entries": 258662, "num_deletions": 0, "num_merge_operands": 0, "num_range_deletions": 0, "format_version": 0, "fixed_key_len": 0, "filter_policy": "rocksdb.BuiltinBloomFilter", "column_family_name": "default", "column_family_id": 0, "comparator": "leveldb.BytewiseComparator", "merge_operator": "nullptr", "prefix_extractor_name": "nullptr", "property_collectors": "[]", "compression": "LZ4", "compression_options": "window_bits=-14; level=32767; strategy=0; max_dict_bytes=0; zstd_max_train_bytes=0; enabled=0; ", "creation_time": 1606887214, "oldest_key_time": 0, "file_creation_time": 1619751151, "db_id": "3821e0bf-d95b-411c-8365-1815fac2071c", "db_session_id": "HN1YDZGUMKTDDM61KJGU"}}

2021/04/29-22:52:32.104065 7f40affff700 [WARN] [db/db_impl/db_impl_compaction_flush.cc:3101] Compaction error: Corruption: Compaction sees out-of-order keys.
2021/04/29-22:52:32.104102 7f40affff700 (Original Log Time 2021/04/29-22:52:32.104024) [db/compaction/compaction_job.cc:830] [default] compacted to: base level 3 level multiplier 10.00 max bytes base 536870912 files[0 0 0 0 0 39 2872] max score 0.08, MB/sec: 277.1 rd, 52.3 wr, level 6, files in(1, 66) out(12) MB in(16.2, 2063.5) out(392.4), read-write-amplify(153.0) write-amplify(24.3) Corruption: Compaction sees out-of-order keys., records in: 16713222, records dropped: 13558666 output_compression: LZ4

2021/04/29-22:52:32.104107 7f40affff700 (Original Log Time 2021/04/29-22:52:32.104058) EVENT_LOG_v1 {"time_micros": 1619751152104038, "job": 3, "event": "compaction_finished", "compaction_time_micros": 7870339, "compaction_time_cpu_micros": 6192462, "output_level": 6, "num_output_files": 12, "total_output_size": 411505707, "num_input_records": 16713222, "num_output_records": 3154556, "num_subcompactions": 1, "output_compression": "LZ4", "num_single_delete_mismatches": 0, "num_single_delete_fallthrough": 0, "lsm_state": [0, 0, 0, 0, 0, 39, 2872]}
2021/04/29-22:52:32.104110 7f40affff700 [ERROR] [db/db_impl/db_impl_compaction_flush.cc:2621] Waiting after background compaction error: Corruption: Compaction sees out-of-order keys., Accumulated background error counts: 1
2021/04/29-22:52:33.106335 7f40affff700 EVENT_LOG_v1 {"time_micros": 1619751153106329, "job": 3, "event": "table_file_deletion", "file_number": 87432}
2021/04/29-22:52:33.106492 7f40affff700 EVENT_LOG_v1 {"time_micros": 1619751153106489, "job": 3, "event": "table_file_deletion", "file_number": 87431}
2021/04/29-22:52:33.106633 7f40affff700 EVENT_LOG_v1 {"time_micros": 1619751153106630, "job": 3, "event": "table_file_deletion", "file_number": 87430}
2021/04/29-22:52:33.106775 7f40affff700 EVENT_LOG_v1 {"time_micros": 1619751153106772, "job": 3, "event": "table_file_deletion", "file_number": 87429}
2021/04/29-22:52:33.106911 7f40affff700 EVENT_LOG_v1 {"time_micros": 1619751153106909, "job": 3, "event": "table_file_deletion", "file_number": 87428}
2021/04/29-22:52:33.107075 7f40affff700 EVENT_LOG_v1 {"time_micros": 1619751153107073, "job": 3, "event": "table_file_deletion", "file_number": 87427}
2021/04/29-22:52:33.107209 7f40affff700 EVENT_LOG_v1 {"time_micros": 1619751153107206, "job": 3, "event": "table_file_deletion", "file_number": 87426}
2021/04/29-22:52:33.107344 7f40affff700 EVENT_LOG_v1 {"time_micros": 1619751153107341, "job": 3, "event": "table_file_deletion", "file_number": 87425}
2021/04/29-22:52:33.107486 7f40affff700 EVENT_LOG_v1 {"time_micros": 1619751153107483, "job": 3, "event": "table_file_deletion", "file_number": 87424}
2021/04/29-22:52:33.107616 7f40affff700 EVENT_LOG_v1 {"time_micros": 1619751153107613, "job": 3, "event": "table_file_deletion", "file_number": 87423}
2021/04/29-22:52:33.107725 7f40affff700 EVENT_LOG_v1 {"time_micros": 1619751153107723, "job": 3, "event": "table_file_deletion", "file_number": 87422}
2021/04/29-22:52:33.110867 7f40affff700 EVENT_LOG_v1 {"time_micros": 1619751153110863, "job": 3, "event": "table_file_deletion", "file_number": 87421}
2021/04/29-22:52:33.113788 7f40affff700 EVENT_LOG_v1 {"time_micros": 1619751153113783, "job": 3, "event": "table_file_deletion", "file_number": 87420}
2021/04/29-22:52:35.046548 7f405dffb700 [db/db_impl/db_impl_compaction_flush.cc:1510] [default] Manual flush start.
2021/04/29-22:52:35.046678 7f405dffb700 [db/db_impl/db_impl_write.cc:1765] [default] New memtable created with log file: #87417. Immutable memtables: 0.
2021/04/29-22:52:35.046694 7f405dffb700 [db/db_impl/db_impl_compaction_flush.cc:1521] [default] Manual flush finished, status: Corruption: Compaction sees out-of-order keys.
```

**Comment by ajkr** [comment]
The data from the bad compaction should not have been persisted. Does the problem happen again after restarting?

**Comment by rohitjoshi** [comment]
yes, I just restarted and problem persists. Any suggestion to repair ? 

We have two nodes and both restores from backup at startup.  Only one node has this issue.

**Comment by ajkr** [comment]
Were the input files created by a pre-6.14 RocksDB version, or without `check_flush_compaction_key_order`, or with a different comparator? Are you able to scan them with `sst_dump` and verify the ordering?

Assuming it is the case that the input files are incorrectly ordered, we don't really have repair tooling. I have thought before about extending #6955 to sort keys in an incorrectly ordered file, but found the demand for lossy repair tooling to be low. Do you have backups or replicas?

**Comment by rohitjoshi** [comment]
yes, backup was created using rocksdb version 6.11.4 ([rust-rocksdb-0.15](https://github.com/rust-rocksdb/rust-rocksdb/commit/b91299ca2e2278cd5ed0db35f5687fb5e37118cd)) and recently we upgraded the application to use 6.17.3 [(rust-rocksdb-0.16](https://github.com/rust-rocksdb/rust-rocksdb/commit/5329272444193c68394fa02428158ebccee09e45))

No change in check_flush_compaction_key_order or comparactor. 

I have not tried running sst_dump.

This corruption is in QA and we do have multiple backups in cross-region so we are good. No concern about the data loss. Thank you.  

I tried to run repair() but it purged most of the data so that did not help.

**Comment by ajkr** [comment]
> This corruption is in QA and we do have multiple backups in cross-region so we are good. No concern about the data loss. Thank you.

Thanks, let us know if anything else is needed.

**Comment by EAHITechnology** [comment]
@ajkr If I want to run `sst_dump`, how should I write the command in this scenario? I tried to use the check command but found nothing, and my data directory relocation can be opened directly with rocksdb.

version : rocksdb 6.4

**Comment by asad-awadia** [comment]
@ajkr i am seeing this on db flush/close [sometimes] -- I do have custom comparators implemented - version 7.4.4

Any idea what might be happening? I am a bit stuck trying to debug what exactly is this caused by or how to fix this

**Comment by ajkr** [comment]
Is the DB recoverable after this happens?

Does your comparator have any risk of violating total ordering? If so, you can load keys from a WAL leading up to such a crash using `ldb wal_dump` and try to validate your comparator on them

**Comment by asad-awadia** [comment]
@ajkr 
> Is the DB recoverable after this happens?
I will check

>Does your comparator have any risk of violating total ordering

What does this mean? like give wrong ordering answers?

>using ldb dump_wal and try to validate your comparator on them

How do i get this ldb binary? I have a `ldb.cc` in the tools folder -- but how do i build this as a runnable?

**Comment by asad-awadia** [comment]
No it is not recoverable - the .open method throws the same exception
```
org.rocksdb.RocksDBException: Compaction sees out-of-order keys.
	at org.rocksdb.OptimisticTransactionDB.open(Native Method)
	at org.rocksdb.OptimisticTransactionDB.open(OptimisticTransactionDB.java:80)
```
<img width="306" alt="Screenshot 2024-01-19 at 7 11 34 PM" src="https://github.com/facebook/rocksdb/assets/6923282/991e3b96-d7d0-4a95-997c-dd9e87677794">

**Comment by asad-awadia** [comment]
`make static_lib` doesn't compile ?

```
ar: creating archive librocksdb.a
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: librocksdb.a(db_impl_debug.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: librocksdb.a(env_default.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: librocksdb.a(env_win.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: librocksdb.a(io_win.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: librocksdb.a(port_win.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: librocksdb.a(win_logger.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: librocksdb.a(win_thread.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: librocksdb.a(async_file_reader.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: librocksdb.a(crc32c_arm64.o) has no symbols
```

**Comment by asad-awadia** [comment]
trying `make clean; make static_lib; make shared_lib; DEBUG_LEVEL=0 make tools`

**Comment by asad-awadia** [comment]
ok i think i got the ldb tool compiled

trying out dumps

**Comment by asad-awadia** [comment]
@ajkr there are a lot of PUTs in the wal - more so than I think I wrote

How do i know which column family was being compacted that caused this issue? i have default + 5 column families [with different comparators]

How do i know which sort is failing?

**Comment by asad-awadia** [comment]
tons of - not sure what to do with these
```
4016,19,5841,1902968,PUT(0) : 0x646F672E6A736F6E233130 PUT(7) : 0x00000014506172697331300005 PUT(7) : 0x0000000D323032342D30312D32325431343A31333A31342E3837353038352D30353A30305B416D65726963612F546F726F6E746F5D31300031 PUT(6) : 0x00000015000000000000000031300008 PUT(7) : 0x00000007313937302D30342D30363130000A PUT(7) : 0x000000196531300001 PUT(7) : 0x0000001A616E6431300003 PUT(7) : 0x0000001A61766F696431300005 PUT(7) : 0x0000001A686967687761797331300008 PUT(7) : 0x0000001A696631300002 PUT(7) : 0x0000001A697331300002 PUT(7) : 0x0000001A6F6E31300002 PUT(7) : 0x0000001A706572736F6E31300006 PUT(7) : 0x0000001A726F61647331300005 PUT(7) : 0x0000001A74686531300003 PUT(7) : 0x0000001A7468656D2E31300005 PUT(7) : 0x0000001A7468697331300004 PUT(7) : 0x0000001066616C736531300005 PUT(3) : 0x000000110000001A31300004
4035,19,5844,1908816,PUT(0) : 0x646F672E6A736F6E233131 PUT(7) : 0x00000014506172697331310005 PUT(7) : 0x0000000D323032342D30312D32325431343A31333A31352E3232343631312D30353A30305B416D65726963612F546F726F6E746F5D31310031 PUT(6) : 0x00000015000000000000000031310008 PUT(7) : 0x00000007313937352D30352D31363131000A PUT(7) : 0x000000196431310001 PUT(7) : 0x0000001A616E6431310003 PUT(7) : 0x0000001A61766F696431310005 PUT(7) : 0x0000001A686967687761797331310008 PUT(7) : 0x0000001A696631310002 PUT(7) : 0x0000001A697331310002 PUT(7) : 0x0000001A6F6E31310002 PUT(7) : 0x0000001A706572736F6E31310006 PUT(7) : 0x0000001A726F61647331310005 PUT(7) : 0x0000001A74686531310003 PUT(7) : 0x0000001A7468656D2E31310005 PUT(7) : 0x0000001A7468697331310004 PUT(7) : 0x0000001066616C736531310005 PUT(3) : 0x000000110000001B31310004
4054,19,5846,1914667,PUT(0) : 0x646F672E6A736F6E233132 PUT(7) : 0x00000014506172697331320005 PUT(7) : 0x0000000D323032342D30312D32325431343A31333A31352E3535373739372D30353A30305B416D65726963612F546F726F6E746F5D31320031 PUT(6) : 0x00000015000000000000000031320008 PUT(7) : 0x00000007313936322D30372D32353132000A PUT(7) : 0x000000196431320001 PUT(7) : 0x0000001A616E6431320003 PUT(7) : 0x0000001A61766F696431320005 PUT(7) : 0x0000001A686967687761797331320008 PUT(7) : 0x0000001A696631320002 PUT(7) : 0x0000001A697331320002 PUT(7) : 0x0000001A6F6E31320002 PUT(7) : 0x0000001A706572736F6E31320006 PUT(7) : 0x0000001A726F61647331320005 PUT(7) : 0x0000001A74686531320003 PUT(7) : 0x0000001A7468656D2E31320005 PUT(7) : 0x0000001A7468697331320004 PUT(7) : 0x0000001066616C736531320005 PUT(3) : 0x000000110000001C31320004
4073,19,5844,1920520,PUT(0) : 0x646F672E6A736F6E233133 PUT(7) : 0x00000014506172697331330005 PUT(7) : 0x0000000D323032342D30312D32325431343A31333A31352E3838383832342D30353A30305B416D65726963612F546F726F6E746F5D31330031 PUT(6) : 0x00000015000000000000000031330008 PUT(7) : 0x00000007313939362D30362D32333133000A PUT(7) : 0x000000196431330001 PUT(7) : 0x0000001A616E6431330003 PUT(7) : 0x0000001A61766F696431330005 PUT(7) : 0x0000001A686967687761797331330008 PUT(7) : 0x0000001A696631330002 PUT(7) : 0x0000001A697331330002 PUT(7) : 0x0000001A6F6E31330002 PUT(7) : 0x0000001A706572736F6E31330006 PUT(7) : 0x0000001A726F61647331330005 PUT(7) : 0x0000001A74686531330003 PUT(7) : 0x0000001A7468656D2E31330005 PUT(7) : 0x0000001A7468697331330004 PUT(7) : 0x0000001066616C736531330005 PUT(3) : 0x000000110000001D31330004
```

**Comment by asad-awadia** [comment]
@ajkr ok got a more simple reproducer -- it seems to be happening for doubles only [surprisingly Double works]

this is the wal dump
```
1,1,66,0,PUT(2) : 0x646F672E6A736F6E5F646F75626C654669656C64
2,2,1726,73,PUT(0) : 0x646F672E6A736F6E2331 PUT(6) : 0x0000000040091EB851EB851F310008
4,2,1726,1806,PUT(0) : 0x646F672E6A736F6E2332 PUT(6) : 0x0000000040091EB851EB851F320008
6,2,1724,3539,PUT(0) : 0x646F672E6A736F6E2333 PUT(6) : 0x0000000040091EB851EB851F330008
8,2,1726,5270,PUT(0) : 0x646F672E6A736F6E2334 PUT(6) : 0x0000000040091EB851EB851F340008
10,2,1726,7003,PUT(0) : 0x646F672E6A736F6E2335 PUT(6) : 0x0000000040091EB851EB851F350008
12,2,1724,8736,PUT(0) : 0x646F672E6A736F6E2336 PUT(6) : 0x0000000040091EB851EB851F360008
14,2,1724,10467,PUT(0) : 0x646F672E6A736F6E2337 PUT(6) : 0x0000000040091EB851EB851F370008
16,2,1724,12198,PUT(0) : 0x646F672E6A736F6E2338 PUT(6) : 0x0000000040091EB851EB851F380008
18,2,1724,13929,PUT(0) : 0x646F672E6A736F6E2339 PUT(6) : 0x0000000040091EB851EB851F390008
20,2,1729,15660,PUT(0) : 0x646F672E6A736F6E233130 PUT(6) : 0x0000000040091EB851EB851F31300008
22,2,1731,17396,PUT(0) : 0x646F672E6A736F6E233131 PUT(6) : 0x0000000040091EB851EB851F31310008
24,2,1732,19134,PUT(0) : 0x646F672E6A736F6E233132 PUT(6) : 0x0000000040091EB851EB851F31320008
26,2,1732,20873,PUT(0) : 0x646F672E6A736F6E233133 PUT(6) : 0x0000000040091EB851EB851F31330008
```

The first hex is the key - is the second hex the value? How do I interpret and use this?

**Comment by asad-awadia** [comment]
This is my comparator code for double
key format is `<int><double><bytes><short>`
```
  virtual int Compare(const Slice& a, const Slice& b) const override {
    int prefixOrder = comparePrefix(a, b);
    if ( prefixOrder != 0 ) {
      return prefixOrder;
    }

    Slice A(a);
    Slice B(b);
    double dblA = 0.0;
    bool AisNaN = (A.size() < 14);
    if( !AisNaN ) {
      A.remove_suffix(2);
      A.remove_prefix(4);
      dblA = ntohDouble(A.data());
      AisNaN = std::isnan(dblA);
    }

    bool BisNaN = (B.size() < 14);
    double dblB = 0.0;
    if( !BisNaN ) {
      A.remove_suffix(2);
      B.remove_prefix(4);
      dblB = ntohDouble(B.data());
      BisNaN = std::isnan(dblB);
    }

    if( !AisNaN && !BisNaN ) {

      // Three-way comparison.  Returns value:
      // if a < b: negative result
      // if a > b: positive result
      // else: zero result
      if( dblA < dblB ) return -1;
      if( dblA > dblB ) return +1;

      // dblA == dblB
      A.remove_prefix(8);
      B.remove_prefix(8);
      return A.compare(B);
    }

    // handle keys with invalid size
    if( AisNaN ) {
      if( BisNaN )
        return 0; // a == b: both a and b are invalid
      return -1; // a < b
    }
    return 1; // a > b
  }
```

**Comment by ajkr** [comment]
Thanks for the info.

> PUT(0) : 0x646F672E6A736F6E2331 PUT(6) : 0x0000000040091EB851EB851F310008
>
> The first hex is the key - is the second hex the value? How do I interpret and use this?

That is two keys. One is for the column family with ID 0 and the other is for the column family with ID 6. There's no values, unless you pass `--print_value`, which isn't needed since we're interested in the key ordering.

**Comment by ajkr** [comment]
> How do I interpret and use this?

If it were me I'd write a program that loads each CF's keys into memory. Then look for elements that the comparator orders oddly. Examples:

- `Compare(a, b) < 0 && Compare(b, a) < 0`
- `Compare(a, b) < 0 && Compare(b, c) < 0 && Compare(c, a) < 0`

from looking at the code though I suspect the second `A.remove_suffix(2);` is a copy-paste error and should be `B.remove_suffix(2);`

**Comment by asad-awadia** [comment]
omg :') that was it! Thank you so much!

**Comment by yizhengli** [comment]
@ajkr hello, is this issue fixed? If so, could you please share me the related code changes? Thanks.
