### ISSUE TITLE
rocksdbjni 4.1 not found libgflags.2.dylib on OS X 10.11

### ISSUE THREAD

**Issue by Barlog-M** [facebook/rocksdb#871]
`compile 'org.rocksdb:rocksdbjni:4.1'`
`java.lang.UnsatisfiedLinkError 1): Library not loaded: /usr/local/lib/libgflags.2.dylib`

`compile 'org.rocksdb:rocksdbjni:4.0'`
work fine

seems like a bug

**Comment by yhchiang** [comment]
Thanks for reporting this issue.   We will try to rebuild and republish the 4.1 package soon.

**Comment by zackb** [comment]
+1

**Comment by yhchiang** [comment]
Hello @Barlog-M and @zackb, I have republished the 4.1 package.  Let me know if the new package fix the existing issue or not.
https://oss.sonatype.org/#nexus-search;quick~rocksdb

**Comment by Barlog-M** [comment]
```
gradle run                 ~/projects/java/db/rocksdb/hello/
:compileJava
Download https://oss.sonatype.org/content/repositories/releases/org/rocksdb/rocksdbjni/4.1/rocksdbjni-4.1.pom
Download https://oss.sonatype.org/content/repositories/releases/org/rocksdb/rocksdbjni/4.1/rocksdbjni-4.1.jar
:processResources UP-TO-DATE
:classes
:run
Exception in thread "main" java.lang.UnsatisfiedLinkError: /private/var/folders/2g/b56wdft17h1fx35rl6bbcml80000gn/T/librocksdbjni1975054551977281102..jnilib: dlopen(/private/var/folders/2g/b56wdft17h1fx35rl6bbcml80000gn/T/librocksdbjni1975054551977281102..jnilib, 1): Library not loaded: /usr/local/lib/libgflags.2.dylib
  Referenced from: /private/var/folders/2g/b56wdft17h1fx35rl6bbcml80000gn/T/librocksdbjni1975054551977281102..jnilib
  Reason: image not found
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1938)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1821)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:105)
	at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:56)
	at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:47)
	at org.rocksdb.RocksDB.<clinit>(RocksDB.java:23)
	at li.barlog.App.main(App.java:13)
:run FAILED
```

**Comment by zackb** [comment]
I still see the same behavior on mac and linux
Exception in thread "main" java.lang.UnsatisfiedLinkError: /tmp/librocksdbjni221976702200869786..so: libgflags.so.2: cannot open shared object file: No such file or directory

**Comment by yhchiang** [comment]
Thanks for reporting.  I thought I have cherry-pick all the previous fix in 4.1 but seems not, let me double check if I miss something.

**Comment by yhchiang** [comment]
@zackb, @Barlog-M: Oops, the new package is called 4.1.0 instead of 4.1.  Do you mind trying 4.1.0 instead?  I downloaded the 4.1.0 package and the dependency of the binary looks fine to me:

    otool -L librocksdbjni-osx.jnilib
    librocksdbjni-osx.jnilib:
        ./java/target/librocksdbjni-osx.jnilib (compatibility version 0.0.0, current version 0.0.0)
        /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)

**Comment by Barlog-M** [comment]
4.1.0 works correctly. Thank you!

**Comment by zackb** [comment]
Works here too with 4.1.0. Thanks!

**Comment by yhchiang** [comment]
Awesome!

**Comment by darionyaphet** [comment]
Good Job :+1:
