### ISSUE TITLE
Documentation page "MultiGet Performance" wrong?

### ISSUE THREAD

**Issue by ByteHamster** [facebook/rocksdb#8920]
The [documentation page for "MultiGet Performance"](https://github.com/facebook/rocksdb/wiki/MultiGet-Performance) states that:

> MultiGet has the capability to issue IO requests for multiple data blocks in the same SST file in parallel, thus reducing latency. On Linux, PosixEnv has the capability to do parallel IO for MultiGet() using the IO Uring interface.

The `DBImpl::MultiGet` method iterates over the keys and issues a `Version::Get` call for each of the keys individually (even though there would also be a `Version::MultiGet` variant). This is where the knowledge of having multiple IO requests seems to get lost. The call finally results in multiple calls to `PosixRandomAccessFile::Read` and does not call `PosixRandomAccessFile::MultiRead`.

Does this mean that the documentation is wrong/misleading and that `MultiGet` actually does **not** issue parallel IO calls?

CC: @anand1976 who wrote that part of the documentation.

---

Steps to reproduce: Set breakpoints in `PosixRandomAccessFile::Read` and `PosixRandomAccessFile::MultiRead` and create a tiny database that fits into a single SST file, for example like the following. Observe that only `PosixRandomAccessFile::Read` gets called.

```cpp
rocksdb::Options options;
options.create_if_missing = true;
rocksdb::BlockBasedTableOptions table_options;
table_options.no_block_cache = true;
options.table_factory.reset(NewBlockBasedTableFactory(table_options));
options.use_direct_reads = true;

rocksdb::DB* db;
rocksdb::Status status = rocksdb::DB::Open(options, "testdb", &db);

db->Put(rocksdb::WriteOptions(), "key1", "value1");
db->Put(rocksdb::WriteOptions(), "key2", "value2");
db->Put(rocksdb::WriteOptions(), "key3", "value3");
db->Flush(rocksdb::FlushOptions());

std::vector<std::string> values(3);
std::vector<rocksdb::Slice> querySlices;
querySlices.emplace_back("key1");
querySlices.emplace_back("key2");
querySlices.emplace_back("key3");

db->MultiGet(rocksdb::ReadOptions(), querySlices, &values);

db->Close();
```

**Comment by ajkr** [comment]
Thanks for the code snippet. I tried migrating to the newer MultiGet() API and it seemed to work. See this comment on the API you were previously using: https://github.com/facebook/rocksdb/blob/f4a1d106681c7631db9d3932331e6433dd12b548/include/rocksdb/db.h#L505-L507. We should update the wiki to reflect that.

Code snippet using new API:

```
rocksdb::Options options;
options.create_if_missing = true;
rocksdb::BlockBasedTableOptions table_options;
table_options.no_block_cache = true;
options.table_factory.reset(NewBlockBasedTableFactory(table_options));
options.use_direct_reads = true;

rocksdb::DB* db;
rocksdb::Status status = rocksdb::DB::Open(options, "testdb", &db);

db->Put(rocksdb::WriteOptions(), "key1", "value1");
db->Put(rocksdb::WriteOptions(), "key2", "value2");
db->Put(rocksdb::WriteOptions(), "key3", "value3");
db->Flush(rocksdb::FlushOptions());

std::vector<rocksdb::PinnableSlice> values(3);
std::vector<rocksdb::Status> statuses(3);
std::vector<rocksdb::Slice> querySlices;
querySlices.emplace_back("key1");
querySlices.emplace_back("key2");
querySlices.emplace_back("key3");

db->MultiGet(rocksdb::ReadOptions(),
             db->DefaultColumnFamily(),
             3 /* num_keys */,
             querySlices.data(),
             values.data(),
             statuses.data());

db->Close();
```

Breakpoint hits here:

```
(gdb) bt
#0  rocksdb::RandomAccessFileReader::MultiRead (this=0x7ffff46160e0, opts=..., read_reqs=0x7fffffff3708, num_reqs=1, aligned_buf=0x7fffffff3498) at file/random_access_file_reader.cc:216
#1  0x0000000000605293 in rocksdb::BlockBasedTable::RetrieveMultipleBlocks (this=0x7ffff460b1a0, options=..., batch=0x7fffffff4410, handles=0x7fffffff49d0, statuses=0x7fffffff4c00, results=0x7fffffff4e30, scratch=0x0,
    uncompression_dict=...) at table/block_based/block_based_table_reader.cc:1737
#2  0x000000000060a2b2 in rocksdb::BlockBasedTable::MultiGet (this=0x7ffff460b1a0, read_options=..., mget_range=0x7fffffff7e90, prefix_extractor=0x0, skip_filters=false) at table/block_based/block_based_table_reader.cc:2681
#3  0x0000000000851f4c in rocksdb::TableCache::MultiGet (this=0x7ffff76bcf40, options=..., internal_comparator=..., file_meta=..., mget_range=0x7fffffff8100, prefix_extractor=0x0, file_read_hist=0x7ffff769ac00, skip_filters=false,
    level=0) at db/table_cache.cc:559
#4  0x00000000004b4f3c in rocksdb::Version::MultiGet (this=0x7ffff764fc00, read_options=..., range=0x7fffffffa350, callback=0x0) at db/version_set.cc:2100
#5  0x00000000007742b5 in rocksdb::DBImpl::MultiGetImpl (this=0x7ffff76cb000, read_options=..., start_key=0, num_keys=3, sorted_keys=0x7fffffffb5e0, super_version=0x7ffff460c000, snapshot=15, callback=0x0) at db/db_impl/db_impl.cc:2575
#6  0x0000000000773d33 in rocksdb::DBImpl::MultiGetWithCallback (this=0x7ffff76cb000, read_options=..., column_family=0x7ffff76ae7e0, callback=0x0, sorted_keys=0x7fffffffb5e0) at db/db_impl/db_impl.cc:2505
#7  0x0000000000773a65 in rocksdb::DBImpl::MultiGet (this=0x7ffff76cb000, read_options=..., column_family=0x7ffff76ae7e0, num_keys=3, keys=0x7ffff7689780, values=0x7ffff760a040, timestamps=0x0, statuses=0x7ffff7692d60,
    sorted_input=false) at db/db_impl/db_impl.cc:2448
#8  0x00000000007737bc in rocksdb::DBImpl::MultiGet (this=0x7ffff76cb000, read_options=..., column_family=0x7ffff76ae7e0, num_keys=3, keys=0x7ffff7689780, values=0x7ffff760a040, statuses=0x7ffff7692d60, sorted_input=false)
    at db/db_impl/db_impl.cc:2418
#9  0x000000000040be71 in main () at tmp.cc:26
```

**Comment by ByteHamster** [comment]
Oh, sorry. I somehow didn't notice that there are two independent implementations. I added a small note to the wiki page mentioning this. Thank you very much for your help!
