### ISSUE TITLE
Segmentation fault  in rocksdb::LRUCacheShard::Lookup

### ISSUE THREAD

**Issue by Manojgupta5** [facebook/rocksdb#9217]
**Getting a segmentation fault when trying to reopen the database/application. I am not using any compression and just using default settings.

Its a 2-column database, one to store the metadata and other one for storing the actual logs.
Is this a known issue and can anyone help please?**

Call stack:

```
Thread 64 "Linux" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff5e0a500 (LWP 30931)]
0x00007ffff7fda4c2 in ?? () from /lib64/ld-linux-x86-64.so.2
(gdb) bt
#0  0x00007ffff7fda4c2 in ?? () from /lib64/ld-linux-x86-64.so.2
#1  0x00007ffff7fdb1e9 in ?? () from /lib64/ld-linux-x86-64.so.2
#2  0x00007ffff7fe0187 in ?? () from /lib64/ld-linux-x86-64.so.2
#3  0x00007ffff7fe7c2e in ?? () from /lib64/ld-linux-x86-64.so.2
#4  0x00007ffff749c2c3 in rocksdb::LRUCacheShard::Lookup(rocksdb::Slice const&, unsigned int, rocksdb::Cache::CacheItemHelper const*, std::function<rocksdb::Status (void*, unsigned long, void**, unsigned long*)> const&, rocksdb::Cache::Priority, bool) ()
   from /home/iquser/rocksdb_libs/librocksdb.so.6.22
#5  0x00007ffff777fdab in rocksdb::BlockBasedTable::GetEntryFromCache(rocksdb::Cache*, rocksdb::Slice const&, rocksdb::BlockType, bool, rocksdb::GetContext*, rocksdb::Cache::CacheItemHelper const*, std::function<rocksdb::Status (void*, unsigned long, void**, unsigned long*)> const&, rocksdb::Cache::Priority) const () from /home/iquser/rocksdb_libs/librocksdb.so.6.22
#6  0x00007ffff779302e in rocksdb::Status rocksdb::BlockBasedTable::GetDataBlockFromCache<rocksdb::Block>(rocksdb::Slice const&, rocksdb::Slice const&, rocksdb::Cache*, rocksdb::Cache*, rocksdb::ReadOptions const&, rocksdb::CachableEntry<rocksdb::Block>*, rocksdb::UncompressionDict const&, rocksdb::BlockType, bool, rocksdb::GetContext*) const () from /home/iquser/rocksdb_libs/librocksdb.so.6.22:
#7  0x00007ffff7793c46 in rocksdb::Status rocksdb::BlockBasedTable::MaybeReadBlockAndLoadToCache<rocksdb::Block>(rocksdb::FilePrefetchBuffer*, rocksdb::ReadOptions const&, rocksdb::BlockHandle const&, rocksdb::UncompressionDict const&, bool, rocksdb::CachableEntry<rocksdb::Block>*, rocksdb::BlockType, rocksdb::GetContext*, rocksdb::BlockCacheLookupContext*, rocksdb::BlockContents*) const ()
   from /home/iquser/rocksdb_libs/librocksdb.so.6.22
#8  0x00007ffff77943f6 in rocksdb::Status rocksdb::BlockBasedTable::RetrieveBlock<rocksdb::Block>(rocksdb::FilePrefetchBuffer*, rocksdb::ReadOptions const&, rocksdb::BlockHandle const&, rocksdb::UncompressionDict const&, rocksdb::CachableEntry<rocksdb::Block>*, rocksdb::BlockType, rocksdb::GetContext*, rocksdb::BlockCacheLookupContext*, bool, bool, bool) const () from /home/iquser/rocksdb_libs/librocksdb.so.6.22
#9  0x00007ffff777900e in rocksdb::DataBlockIter* rocksdb::BlockBasedTable::NewDataBlockIterator<rocksdb::DataBlockIter>(rocksdb::ReadOptions const&, rocksdb::BlockHandle const&, rocksdb::DataBlockIter*, rocksdb::BlockType, rocksdb::GetContext*, rocksdb::BlockCacheLookupContext*, rocksdb::Status, rocksdb::FilePrefetchBuffer*, bool) const () from /home/iquser/rocksdb_libs/librocksdb.so.6.22
#10 0x00007ffff77847ef in rocksdb::BlockBasedTable::Get(rocksdb::ReadOptions const&, rocksdb::Slice const&, rocksdb::GetContext*, rocksdb::SliceTransform const*, bool) () from /home/iquser/rocksdb_libs/librocksdb.so.6.22
#11 0x00007ffff761cdac in rocksdb::TableCache::Get(rocksdb::ReadOptions const&, rocksdb::InternalKeyComparator const&, rocksdb::FileMetaData const&, rocksdb::Slice const&, rocksdb::GetContext*, rocksdb::SliceTransform const*, rocksdb::HistogramImpl*, bool, int, unsigned long) ()
   from /home/iquser/rocksdb_libs/librocksdb.so.6.22
#12 0x00007ffff765b11a in rocksdb::Version::Get(rocksdb::ReadOptions const&, rocksdb::LookupKey const&, rocksdb::PinnableSlice*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, rocksdb::Status*, rocksdb::MergeContext*, unsigned long*, bool*, bool*, unsigned long*, rocksdb::ReadCallback*, bool*, bool) () from /home/iquser/rocksdb_libs/librocksdb.so.6.22
#13 0x00007ffff7529428 in rocksdb::DBImpl::GetImpl(rocksdb::ReadOptions const&, rocksdb::Slice const&, rocksdb::DBImpl::GetImplOptions&) ()
   from /home/iquser/rocksdb_libs/librocksdb.so.6.22
#14 0x00007ffff7529919 in rocksdb::DBImpl::Get(rocksdb::ReadOptions const&, rocksdb::ColumnFamilyHandle*, rocksdb::Slice const&, rocksdb::PinnableSlice*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*) ()
--Type <RET> for more, q to quit, c to continue without paging--
   from /home/iquser/rocksdb_libs/librocksdb.so.6.22
#15 0x00007ffff7520a86 in rocksdb::DBImpl::Get(rocksdb::ReadOptions const&, rocksdb::ColumnFamilyHandle*, rocksdb::Slice const&, rocksdb::PinnableSlice*) () from /home/iquser/rocksdb_libs/librocksdb.so.6.22
#16 0x0000555555ba73f5 in RocksDBWrapper::logGet (this=0x55555662c530, aLogHandle=32769, aRecordNum=1, aRecordOffset=0, 
    aBufferPtr=0x7fff680e2f88, aBufferSize=4) at RocksDBWrapper.cpp:359
```

**Comment by Manojgupta5** [comment]
@pdillinger thanks for reply. The crash is consistent. However if I iterate all the keys before Get operation, the crash is gone.
Any idea what might be happening in the background?
Does rocksdb rebuilds the cache when reading all the keys?

**Comment by hx235** [comment]
> @pdillinger thanks for reply. The crash is consistent. However if I iterate all the keys before Get operation, the crash is gone. Any idea what might be happening in the background? Does Rocksdb rebuilds the cache when reading all the keys?

Hi @Manojgupta5 :) - would you mind sharing a repro code  (like a minimum unit-test that repros the segmentation fault and the one makes the crash gone) with your RocksDB version? Thanks!
