### ISSUE TITLE
rocksDB JNI can not run in macos when jdk version is 17

### ISSUE THREAD

**Issue by xj524598** [facebook/rocksdb#9550]
rocksDB JNI can not run in macos when jdk version is 17:

my macos version is: Big Sur 11.6

jdk version is: 17.0.1

rocksDB jni version is:
   <dependency>
            <groupId>org.rocksdb</groupId>
            <artifactId>rocksdbjni</artifactId>
            <version>6.27.3</version>
        </dependency>

### Actual behavior: no suitable image found. detail is downside

2022-02-11 14:04:47.787 ERROR 53939 logTag:  bizID:  errCode: traceID: --- [           main] c.d.s.gateway.common.tools.RocksDBTools  :init rocksDB errro: java.lang.UnsatisfiedLinkError: /private/var/folders/p8/9spv531s6t936yq1zthnp17hs176vc/T/librocksdbjni162285091552927165.jnilib: dlopen(/private/var/folders/p8/9spv531s6t936yq1zthnp17hs176vc/T/librocksdbjni162285091552927165.jnilib, 1): no suitable image found.  Did find:
	/private/var/folders/p8/9spv531s6t936yq1zthnp17hs176vc/T/librocksdbjni162285091552927165.jnilib: mach-o, but wrong architecture
	/private/var/folders/p8/9spv531s6t936yq1zthnp17hs176vc/T/librocksdbjni162285091552927165.jnilib: mach-o, but wrong architecture
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:384)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:228)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:170)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2389)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1953)
	at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:79)
	at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:57)
	at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:69)
	at org.rocksdb.RocksDB.<clinit>(RocksDB.java:38)

### Steps to reproduce the behavior
in macos ,using rocksdbjni on jdk 17, can reproduce this mistake

**Comment by xj524598** [comment]
there is some pictures:

macos:
![image](https://user-images.githubusercontent.com/26913796/153545598-e5dd94bd-c8e5-49d0-93b8-38f6b5d9bd47.png)

jdk version:
![image](https://user-images.githubusercontent.com/26913796/153545664-acdc3d33-45ed-4734-8f8e-223e0c32ad89.png)


error 
![image](https://user-images.githubusercontent.com/26913796/153545774-6356b667-205c-48a6-a70e-97e0b70a080b.png)

**Comment by microhardsmith** [comment]
using 6.28.2 and still got the same problem,waiting for 6.29.x now

**Comment by dongjoon-hyun** [comment]
Actually, 6.29.3 was released 12 days ago but `RocksDB JNI` is still not published to the Maven Central.
- https://github.com/facebook/rocksdb/releases/tag/v6.29.3

**Comment by microhardsmith** [comment]
so when can we get RocksDB JNI 6.29.3?

**Comment by dongjoon-hyun** [comment]
According to their cadence, +1 month from the tag creation.

**Comment by dongjoon-hyun** [comment]
Let me correct me. Here is the official answer link.
- https://github.com/facebook/rocksdb/issues/7720#issuecomment-1040091300
> As mentioned above we can indeed expect the fix in the 6.29.x release. Past releases suggest a RocksDB java release every 1 or 2 months. So likely March or April.

**Comment by jurmous** [comment]
As mentioned later in the issue: There is an issue with creating the jars for the release. That needs to be fixed first and then needs to land in another future version...

**Comment by dongjoon-hyun** [comment]
Oh, thank you for informing that, @jurmous .

**Comment by ajkr** [comment]
> Actually, 6.29.3 was released 12 days ago but `RocksDB JNI` is still not published to the Maven Central.
> 
> * https://github.com/facebook/rocksdb/releases/tag/v6.29.3

#9689 for tracking this.
