### ISSUE TITLE
rocksdb with rusty_v8 aborts

### ISSUE THREAD

**Issue by OfekShochat** [facebook/rocksdb#9555]
Im using the rust-rocksdb crate and rusty_v8 in an application (which is in rust). they both work fine on separate projects, but when I try to call new_default_platform which is in rusty_v8, and try to load the db (the db loads first) the resulting executable throws a SIGABRT.
expected behavior: doesnt abort
actual behavior: aborts
minimal code to reproduce (in rust):
`main.rs`:
```rust
use rusty_v8 as v8;
use rocksdb::{DB, Options};

fn main() {
    let mut options = Options::default(); // Just using anything from the library makes it abort. Probably because of init stuff
                                         // it would make sense if it was the allocator, but I think it isnt because v8 actually makes 
                                         // its own allocator for array buffers and for other stuff it just uses the standard one.

    let platform = v8::new_default_platform(0, false).make_shared();
}
```
`Cargo.toml`
```
[package]
name = "test"
version = "0.1.0"
edition = "2021"

[dependencies]
rusty_v8 = "0.32"
rocksdb = "0.17"
```

Ive looked at #6845 but it seems that the [library Im using](https://github.com/rust-rocksdb/rust-rocksdb) doesnt build with jemalloc on default and I dont know if the rusty_v8 library uses any other allocator (also didnt see any mentions of it).

my question is, is there anything that can do that apart from allocator mismatch? 
also, it crashes when I try to make new Options to open a database too, without anything else. also, tried to run this in a container. same thing.

output from gdb `backtrace full`:
```(gdb) backtrace full
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
        tid = <optimized out>
        ret = 0
        pd = <optimized out>
        old_mask = {__val = {140725866307336, 140725866307344, 140725866307352, 0, 140725866307368, 0, 0, 0, 0, 94297435492160, 4611686018427387904, 0, 0, 0, 0, 0}}
        ret = <optimized out>
#1  0x00007f5be9a998b3 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
No locals.
#2  0x00007f5be9a4c6a6 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
        ret = <optimized out>
#3  0x00007f5be9a367d3 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0x0, sa_sigaction = 0x0}, sa_mask = {__val = {0 <repeats 16 times>}}, sa_flags = 0, sa_restorer = 0x0}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#4  0x000055c35572f728 in std::__terminate(void (*)()) () at ../../../../buildtools/third_party/libc++abi/trunk/src/cxa_handlers.cpp:59
No locals.
#5  0x000055c35572f21b in __cxxabiv1::failed_throw(__cxxabiv1::__cxa_exception*) () at ../../../../buildtools/third_party/libc++abi/trunk/src/cxa_exception.cpp:152
No locals.
#6  0x000055c35572f195 in __cxa_throw () at ../../../../buildtools/third_party/libc++abi/trunk/src/cxa_exception.cpp:283
No locals.
#7  0x000055c35572efa1 in __cxa_bad_cast () at ../../../../buildtools/third_party/libc++abi/trunk/src/cxa_aux_runtime.cpp:20
No locals.
#8  0x000055c3554a154c in std::use_facet<std::ctype<char> const> (__loc=...) at /usr/include/c++/11/bits/locale_classes.tcc:139
        __i = 0
        __facets = 0x7f5be9f28ac0 <(anonymous namespace)::facet_vec>
#9  0x000055c3554a0a89 in std::__detail::_Scanner<char>::_Scanner (this=0x7ffd4b459a28, __begin=0x7ffd4b459e50 "posix://.*", __end=0x7ffd4b459e5a "", __flags=(unknown: 0x10), __loc=...) at /usr/include/c++/11/bits/regex_scanner.tcc:62
No locals.
#10 0x000055c3554a0543 in std::__detail::_Compiler<std::__cxx11::regex_traits<char> >::_Compiler (this=0x7ffd4b459a20, __b=0x7ffd4b459e50 "posix://.*", __e=0x7ffd4b459e5a "", __loc=..., __flags=(unknown: 0x10))
    at /usr/include/c++/11/bits/regex_compiler.tcc:77
        __r = <optimized out>
#11 0x000055c3554a028d in std::__detail::__compile_nfa<std::__cxx11::regex_traits<char>, char const*> (__first=0x7ffd4b459e50 "posix://.*", __last=0x7ffd4b459e5a "", __loc=..., __flags=(unknown: 0x10))
    at /usr/include/c++/11/bits/regex_compiler.h:183
        __len = 10
        __cfirst = 0x7ffd4b459e50 "posix://.*"
#12 0x000055c35549fdb7 in std::__cxx11::basic_regex<char, std::__cxx11::regex_traits<char> >::basic_regex<char const*> (this=0x55c355c3ec18, __first=0x7ffd4b459e50 "posix://.*", __last=0x7ffd4b459e5a "", __loc=..., __f=(unknown: 0x10))
    at /usr/include/c++/11/bits/regex.h:764
No locals.
#13 0x000055c35549f7e2 in std::__cxx11::basic_regex<char, std::__cxx11::regex_traits<char> >::basic_regex<char const*> (this=0x55c355c3ec18, __first=0x7ffd4b459e50 "posix://.*", __last=0x7ffd4b459e5a "", __f=(unknown: 0x10))
    at /usr/include/c++/11/bits/regex.h:508
No locals.
#14 0x000055c35549ebdb in std::__cxx11::basic_regex<char, std::__cxx11::regex_traits<char> >::basic_regex<std::char_traits<char>, std::allocator<char> > (this=0x55c355c3ec18, __s="posix://.*", __f=(unknown: 0x10))
    at /usr/include/c++/11/bits/regex.h:489
No locals.
#15 0x000055c35549dd86 in rocksdb::ObjectLibrary::FactoryEntry<rocksdb::FileSystem>::FactoryEntry(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<rocksdb::FileSystem* (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::unique_ptr<rocksdb::FileSystem, std::default_delete<rocksdb::FileSystem> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)>)
    (this=0x55c355c3ebf0, name="posix://.*", f=...) at rocksdb/include/rocksdb/utilities/object_registry.h:49
No locals.
#16 0x000055c35549d336 in rocksdb::ObjectLibrary::Register<rocksdb::FileSystem>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<rocksdb::FileSystem* (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::unique_ptr<rocksdb::FileSystem, std::default_delete<rocksdb::FileSystem> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)> const&) (
    this=0x55c355c3e4e0, pattern="posix://.*", factory=...) at rocksdb/include/rocksdb/utilities/object_registry.h:75
        entry = std::unique_ptr<rocksdb::ObjectLibrary::Entry> = {get() = 0x1}
#17 0x000055c3554be34f in __static_initialization_and_destruction_0 (__initialize_p=1, __priority=65535) at rocksdb/env/fs_posix.cc:1090
--Type <RET> for more, q to quit, c to continue without paging--
No locals.
#18 0x000055c3554c5f4d in _GLOBAL__sub_I_fs_posix.cc(void) () at rocksdb/env/fs_posix.cc:1099
No locals.
#19 0x00007f5be9a3768d in call_init (env=<optimized out>, argv=0x7ffd4b459f38, argc=1) at ../csu/libc-start.c:145
        j = 0
        jm = <optimized out>
        addrs = <optimized out>
        l = <optimized out>
        init_array = <optimized out>
#20 __libc_start_main_impl (main=0x55c355268f40 <main>, argc=1, argv=0x7ffd4b459f38, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffd4b459f28) at ../csu/libc-start.c:379
No locals.
#21 0x000055c355254f65 in _start ()
No symbol table info available.
```

**Comment by OfekShochat** [comment]
lol tried to reproduce this in c++. but this is just a mess. rocksdb is so easy to build and v8 needs so many more steps and their build-depenency installer thing doesnt even support redhat distributions.

**Comment by OfekShochat** [comment]
Btw, the code I posted on my issue is directly translatable to c++.

**Comment by OfekShochat** [comment]
Anyone...?

**Comment by ajkr** [comment]
Hi, rust-rocksdb crate and rusty_v8 are not part of this repository.

**Comment by OfekShochat** [comment]
yeah, but this is crashing on your code
