### ISSUE TITLE
Core dump occurs while performing put() operation in java

### ISSUE THREAD

**Issue by shrenikkjain** [facebook/rocksdb#9614]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

Maven rocksDB version:  <rocksdb.version>6.4.6</rocksdb.version>
OS: RHEL

### Actual behavior
Program terminated with signal 6, Aborted.
#0  0x00007fd35e49c387 in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install glibc-2.17-325.el7_9.x86_64 java-1.8.0-openjdk-headless-1.8.0.302.b08-0.el7_9.x86_64 libgcc-4.8.5-44.el7.x86_64 libstdc++-4.8.5-44.el7.x86_64 zlib-1.2.7-19.el7_9.x86_64
(gdb) bt
#0  0x00007fd35e49c387 in raise () from /lib64/libc.so.6
#1  0x00007fd35e49da78 in abort () from /lib64/libc.so.6
#2  0x00007fd2f4ad056b in ?? () from /opt/fm/data/receiver/librocksdbjni-linux64.so
#3  0x00007fd2f4d5a302 in rocksdb::port::Mutex::Lock() () from /opt/fm/data/receiver/librocksdbjni-linux64.so
#4  0x00007fd2f4d24f98 in rocksdb::InstrumentedMutex::Lock() () from /opt/fm/data/receiver/librocksdbjni-linux64.so
#5  0x00007fd2f4c23a9d in rocksdb::DBImpl::WriteImpl(rocksdb::WriteOptions const&, rocksdb::WriteBatch*, rocksdb::WriteCallback*, unsigned long*, unsigned long, bool, unsigned long*, unsigned long, rocksdb::PreReleaseCallback*) () from /opt/fm/data/receiver/librocksdbjni-linux64.so
#6  0x00007fd2f4c25a91 in rocksdb::DBImpl::Write(rocksdb::WriteOptions const&, rocksdb::WriteBatch*) ()
   from /opt/fm/data/receiver/librocksdbjni-linux64.so
#7  0x00007fd2f4c25ca2 in rocksdb::DB::Put(rocksdb::WriteOptions const&, rocksdb::ColumnFamilyHandle*, rocksdb::Slice const&, rocksdb::Slice const&) ()
   from /opt/fm/data/receiver/librocksdbjni-linux64.so
#8  0x00007fd2f4c25d61 in rocksdb::DBImpl::Put(rocksdb::WriteOptions const&, rocksdb::ColumnFamilyHandle*, rocksdb::Slice const&, rocksdb::Slice const&)
    () from /opt/fm/data/receiver/librocksdbjni-linux64.so
#9  0x00007fd2f4b2a17d in rocksdb::DB::Put(rocksdb::WriteOptions const&, rocksdb::Slice const&, rocksdb::Slice const&) ()
   from /opt/fm/data/receiver/librocksdbjni-linux64.so
#10 0x00007fd2f4b1f55c in rocksdb_put_helper(JNIEnv_*, rocksdb::DB*, rocksdb::WriteOptions const&, rocksdb::ColumnFamilyHandle*, _jbyteArray*, int, int, _jbyteArray*, int, int) () from /opt/fm/data/receiver/librocksdbjni-linux64.so

**Comment by shrenikkjain** [comment]
[hs_err_pid10593.log](https://github.com/facebook/rocksdb/files/8116190/hs_err_pid10593.log)
