### ISSUE TITLE
Core dumped at assert() in LevelCompactionBuilder::SetupInitialFiles()

### ISSUE THREAD

**Issue by ChrisZMF** [facebook/rocksdb#9681]
I got a core at `assert(!level_and_file.second->being_compacted);` in function `LevelCompactionBuilder::SetupInitialFiles()`. The detailed stack is shown blow. It is a same bug as issue #5747.

**Rocksdb version**: 5.15

### Analysis
Related code as following:
```
void LevelCompactionBuilder::SetupInitialFiles() {
  ......
    for (i = 0; i < vstorage_->BottommostFilesMarkedForCompaction().size();
         ++i) {
      auto& level_and_file = vstorage_->BottommostFilesMarkedForCompaction()[i];
      assert(!level_and_file.second->being_compacted);   // core dumped here
      start_level_inputs_.level = output_level_ = start_level_ =
          level_and_file.first;
      start_level_inputs_.files = {level_and_file.second};
      if (compaction_picker_->ExpandInputsToCleanCut(cf_name_, vstorage_,
                                                     &start_level_inputs_)) {
        break;
      }
    }
  ......
}
```

This bug is triggered due to re-compact the bottommost SST files. The bottommost SST files marked for compaction are stored in `bottommost_files_marked_for_compaction_` which can be obtained by `vstorage_->BottommostFilesMarkedForCompaction`. `bottommost_files_marked_for_compaction_` is filled by function `ComputeBottommostFilesMarkedForCompaction` which will guarantee files appended to `bottommost_files_marked_for_compaction_` are not in state `being_compacted`. However, as shown in codes above, the file in `being_compacted` state is gotten at new compaction picking which triggers this bug. 
By the way, I got many logs for manual compactions , as `[default] Manual compaction starting`, before the bug happened.

Do you have any idea about this bug or any suggestion to fix it?

### Stack Backtrace
```
(gdb) bt
#0  __pthread_kill (threadid=<optimized out>, signo=signo@entry=6) at ../sysdeps/unix/sysv/linux/pthread_kill.c:61
#1  0x0000000000903f0a in my_write_core (sig=sig@entry=6) at /home/mysql/output/mysql/mysys/stacktrace.c:422
#2  0x000000000069461e in handle_fatal_signal (sig=6) at /home/mysql/output/mysql/sql/signal_handler.cc:233
#3  <signal handler called>
#4  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
#5  0x00007f7d80c1d2d9 in __GI_abort () at abort.c:89
#6  0x00007f7d80c1d1af in __assert_fail_base (fmt=0x7f7d80d67db0 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x7f7d6c71ff70 "!level_and_file.second->being_compacted",
    file=0x7f7d6c71f400 "/home/mysql/output/mysql/storage/rocksdb/rocksdb/db/compaction_picker.cc", line=1249, function=<optimized out>) at assert.c:92
#7  0x00007f7d80c2a992 in __GI___assert_fail (assertion=assertion@entry=0x7f7d6c71ff70 "!level_and_file.second->being_compacted",
    file=file@entry=0x7f7d6c71f400 "/home/mysql/output/mysql/storage/rocksdb/rocksdb/db/compaction_picker.cc", line=line@entry=1249,
    function=function@entry=0x7f7d6c720600 <rocksdb::(anonymous namespace)::LevelCompactionBuilder::SetupInitialFiles()::__PRETTY_FUNCTION__> "void rocksdb::{anonymous}::LevelCompactionBuilder::SetupInitialFiles()") at assert.c:101
#8  0x00007f7d6c5dcf17 in rocksdb::(anonymous namespace)::LevelCompactionBuilder::SetupInitialFiles (this=<optimized out>) at /home/opt/compiler/gcc-8.2/gcc-8.2/include/c++/8.2.0/bits/stl_vector.h:1654
#9  rocksdb::(anonymous namespace)::LevelCompactionBuilder::PickCompaction (this=0x7f71707fc210) at /home/mysql/output/mysql/storage/rocksdb/rocksdb/db/compaction_picker.cc:1322
#10 rocksdb::LevelCompactionPicker::PickCompaction (this=<optimized out>, cf_name=..., mutable_cf_options=..., vstorage=<optimized out>, log_buffer=<optimized out>)
    at /home/mysql/output/mysql/storage/rocksdb/rocksdb/db/compaction_picker.cc:1525
#11 0x00007f7d6c5b45db in rocksdb::ColumnFamilyData::PickCompaction (this=this@entry=0x7f7d6bd73400, mutable_options=..., log_buffer=log_buffer@entry=0x7f71707fccb0)
    at /home/mysql/output/mysql/storage/rocksdb/rocksdb/db/column_family.h:166
#12 0x00007f7d6c3d5412 in rocksdb::DBImpl::BackgroundCompaction (this=0x7f7d6c016000, made_progress=0x7f71707fc9b5, job_context=0x7f71707fc9d0, log_buffer=0x7f71707fccb0, prepicked_compaction=<optimized out>)
    at /home/mysql/output/mysql/storage/rocksdb/rocksdb/db/db_impl_compaction_flush.cc:1709
#13 0x00007f7d6c3d689f in rocksdb::DBImpl::BackgroundCallCompaction (this=0x7f7d6c016000, prepicked_compaction=0x0, bg_thread_pri=rocksdb::Env::LOW)
    at /home/mysql/output/mysql/storage/rocksdb/rocksdb/db/db_impl_compaction_flush.cc:1504
#14 0x00007f7d6c3d6e7d in rocksdb::DBImpl::BGWorkCompaction (arg=<optimized out>) at /home/mysql/output/mysql/storage/rocksdb/rocksdb/db/db_impl_compaction_flush.cc:1317
#15 0x00007f7d6c612ce4 in std::function<void ()>::operator()() const (this=0x7f71707fd640) at /home/opt/compiler/gcc-8.2/gcc-8.2/include/c++/8.2.0/bits/std_function.h:682
#16 rocksdb::ThreadPoolImpl::Impl::BGThread (this=0x7f7d806bd380, thread_id=5) at /home/mysql/output/mysql/storage/rocksdb/rocksdb/util/threadpool_imp.cc:265
#17 0x00007f7d6c612ead in rocksdb::ThreadPoolImpl::Impl::BGThreadWrapper (arg=0x7f7d80633210) at /home/mysql/output/mysql/storage/rocksdb/rocksdb/util/threadpool_imp.cc:303
#18 0x00007f7d80f8716f in ?? () from /opt/compiler/gcc-8.2/lib/libstdc++.so.6
#19 0x00007f7d8109fda4 in start_thread (arg=<optimized out>) at pthread_create.c:333
#20 0x00007f7d80ce832d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

**Comment by ajkr** [comment]
Does it happen on newer versions (6.29.x or 7.0.x)? If so we can reopen.
