### ISSUE TITLE
java.lang.UnsatisfiedLinkError: org.rocksdb.HdfsEnv.createHdfsEnv(Ljava/lang/String;)J

### ISSUE THREAD

**Issue by foreverneverer** [facebook/rocksdb#9864]
# Version 6.6.4

I use rocksdbjava with hdfs-env(I compile it in my own os env, java=1.8, gcc=4.8) in following pom(**spark 2.1 env**) running well:
```xml
<dependency>
      <groupId>org.apache.hadoop</groupId>
      <artifactId>hadoop-hdfs</artifactId>
      <version>2.6.0</version>
    </dependency>
    <dependency>
      <groupId>org.apache.hadoop</groupId>
      <artifactId>hadoop-common</artifactId>
      <version>2.6.0</version>
    </dependency>
    <!--Scala-->
    <dependency>
      <groupId>org.scala-lang</groupId>
      <artifactId>scala-library</artifactId>
      <version>2.11.12</version>
    </dependency>
    <!--Spark-->
    <dependency>
      <groupId>org.apache.spark</groupId>
      <artifactId>spark-core_2.11</artifactId>
      <version>2.1.0</version>
    </dependency>
    <dependency>
      <groupId>org.apache.spark</groupId>
      <artifactId>spark-sql_2.11</artifactId>
      <version>2.1.0</version>
    </dependency>
```
But when I use the following pom(**spark3.1 env**):
```xml
 <dependency>
      <groupId>org.apache.hadoop</groupId>
      <artifactId>hadoop-hdfs</artifactId>
      <version>3.1.0</version>
    </dependency>
    <dependency>
      <groupId>org.apache.hadoop</groupId>
      <artifactId>hadoop-hdfs-client</artifactId>
      <version>3.1.0</version>
    </dependency>
    <dependency>
      <groupId>org.apache.hadoop</groupId>
      <artifactId>hadoop-common</artifactId>
      <version>3.1.0</version>
    </dependency>
    <!--Scala-->
    <dependency>
      <groupId>org.scala-lang</groupId>
      <artifactId>scala-library</artifactId>
      <version>2.12.10</version>
    </dependency>
    <!--Spark-->
    <dependency>
      <groupId>org.apache.spark</groupId>
      <artifactId>spark-core_2.12</artifactId>
      <version>3.1.2</version>
    </dependency>
    <dependency>
      <groupId>org.apache.spark</groupId>
      <artifactId>spark-sql_2.12</artifactId>
      <version>3.1.2</version>
    </dependency>
```

The code is call:
```java
 env = new HdfsEnv(remoteFs);
```
and it report error: 
```xml
java.lang.UnsatisfiedLinkError: org.rocksdb.HdfsEnv.createHdfsEnv(Ljava/lang/String;)J
	at org.rocksdb.HdfsEnv.createHdfsEnv(Native Method)
	at org.rocksdb.HdfsEnv.<init>(HdfsEnv.java:22)
....(the own code stack trace)
```
I was confused that it just report `UnsatisfiedLinkError` but no any other more message. I try add debug info as follow:
```java
jlong Java_org_rocksdb_HdfsEnv_createHdfsEnv(
    JNIEnv* env, jclass, jstring jfsname) {
  fprintf(stderr, "DEBUG\n");// add the debug code
  jboolean has_exception = JNI_FALSE;
  auto fsname = rocksdb::JniUtil::copyStdString(env, jfsname, &has_exception);
```

I even can't find the log that is seem to say it crush before link c++ code. I don't have debug jni experience. could you help me resolve it or tell me how to debug it

**Comment by foreverneverer** [comment]
@adamretter Hi, I have see some related issue but not found the resolution, and I found you should have enough experience to jni module, could you give me some suggestion?

**Comment by adamretter** [comment]
Can you try with a newer version 6. Also be aware that for version 7 Hadoop support has been moved out of the project into a plugin

**Comment by foreverneverer** [comment]
Our [project](https://github.com/XiaoMi/pegasus-rocksdb) has compatibility problems above 6.6.4, so I can't upgrade to the latest to test.

**Comment by adamretter** [comment]
Can you check that the native signature of `createHdfsEnv` here - https://github.com/facebook/rocksdb/blob/v6.6.4/java/rocksjni/env.cc#L182
matches your generated `java/include/org_rocksdb_HdfsEnv`?

**Comment by foreverneverer** [comment]
I check it and find it is right

```c++
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_rocksdb_HdfsEnv */

#ifndef _Included_org_rocksdb_HdfsEnv
#define _Included_org_rocksdb_HdfsEnv
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_rocksdb_HdfsEnv
 * Method:    createHdfsEnv
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_rocksdb_HdfsEnv_createHdfsEnv
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_rocksdb_HdfsEnv
 * Method:    disposeInternal
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_HdfsEnv_disposeInternal
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
```

**Comment by adamretter** [comment]
Did you build with `USE_HDFS=1` set? See https://github.com/facebook/rocksdb/blob/v6.6.4/build_tools/build_detect_platform#L519

**Comment by foreverneverer** [comment]
Yeah, the jni library can be used for `spark2.1`, but can't run on `spark3.1`

**Comment by adamretter** [comment]
@foreverneverer Sorry, but I don't understand why there is a problem with different spark versions? Surely that would point to a Spark issue rather than a Rocks isue?

**Comment by foreverneverer** [comment]
OK, thanks a lot! I will try it!

**Comment by foreverneverer** [comment]
I have found the problem that is our spark3.1 cluster env include `iceberg` which contains the `rocksdbjava-jni` dependency, so the cluster ignore my own `rocksdbjava-jni` version.

I exclude the cluster's `rocksdbjava-jni` and resolve it
